[phases.setup]
nixPkgs = ["python312", "gcc", "postgresql"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "python run_server.py"

[variables]
PYTHONUNBUFFERED = "1"
PORT = "8080"
