[build]
builder = "NIXPACKS"
watchPatterns = ["**"]

# Force rebuild - 2026-07-05

[deploy]
startCommand = "python run_server.py"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
DEBUG = "False"
PORT = "8080"
CUSTOM_DOMAIN = "daluailiraq.com"
SECURE_SSL_REDIRECT = "False"
PYTHONUNBUFFERED = "1"
DJANGO_SETTINGS_MODULE = "dalal_project.settings"
