# Generated by Django 6.0.4 on 2026-05-03 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('land', 'قطعة أرض'), ('house', 'بيت'), ('building', 'بناية')], max_length=20, verbose_name='نوع العقار')),
                ('status', models.CharField(choices=[('ready', 'جاهز'), ('under-construction', 'قيد الإنشاء'), ('sold', 'مباع')], default='ready', max_length=20, verbose_name='الحالة')),
                ('location', models.CharField(max_length=200, verbose_name='الموقع')),
                ('area', models.IntegerField(verbose_name='المساحة (متر مربع)')),
                ('price', models.BigIntegerField(verbose_name='السعر (د.ع)')),
                ('description', models.TextField(verbose_name='وصف العقار')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم التواصل')),
                ('images', models.TextField(blank=True, help_text='رابط الصور مفصولة بفاصلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'عقار',
                'verbose_name_plural': 'العقارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='تم القراءة')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'ordering': ['-created_at'],
            },
        ),
    ]
