# Generated by Django 4.2.7 on 2026-05-04 15:20

from django.db import migrations, models
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_message_id_alter_property_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الحمامات'),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الغرف'),
        ),
        migrations.AddField(
            model_name='property',
            name='floors',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الطوابق'),
        ),
        migrations.AddField(
            model_name='property',
            name='furnished',
            field=models.BooleanField(default=False, verbose_name='مفروش'),
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=properties.models.property_image_path, verbose_name='الصورة الرئيسية'),
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='موقف سيارة'),
        ),
        migrations.AddField(
            model_name='property',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات'),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.IntegerField(blank=True, null=True, verbose_name='سنة البناء'),
        ),
        migrations.AlterField(
            model_name='property',
            name='images',
            field=models.TextField(blank=True, help_text='روابط الصور الإضافية مفصولة بفاصلة'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('ready', 'جاهز'), ('under-construction', 'قيد الإنشاء'), ('sold', 'مباع'), ('rent', 'للإيجار')], default='ready', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('land', 'قطعة أرض'), ('house', 'بيت'), ('building', 'بناية'), ('apartment', 'شقة'), ('store', 'محل تجاري'), ('warehouse', 'مستودع')], max_length=20, verbose_name='نوع العقار'),
        ),
    ]
