# Generated by Django 6.0.4 on 2026-06-01 22:02

import django.db.models.deletion
import properties.models
from django.db import migrations, models
from django.utils.text import slugify


def populate_property_slugs(apps, schema_editor):
    Property = apps.get_model('properties', 'Property')
    for prop in Property.objects.all():
        city = prop.city or (prop.location[:100] if prop.location else 'بغداد')
        title = prop.title or f'عقار-{prop.pk}'
        base = slugify(f'{title}-{city}-{prop.pk}', allow_unicode=True) or f'property-{prop.pk}'
        Property.objects.filter(pk=prop.pk).update(city=city, title=title, slug=base)


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_bathrooms_property_bedrooms_property_floors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=properties.models.property_image_path, verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='تعليق')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_primary', models.BooleanField(default=False, verbose_name='رئيسية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'صورة عقار',
                'verbose_name_plural': 'صور العقارات',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='دلال', max_length=100, verbose_name='اسم الموقع')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='الشعار')),
                ('broker_phone', models.CharField(default='07701234567', max_length=30, verbose_name='هاتف التواصل')),
                ('broker_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد')),
                ('broker_address', models.CharField(blank=True, max_length=300, verbose_name='العنوان')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='واتساب')),
                ('about_title', models.CharField(default='من نحن', max_length=200, verbose_name='عنوان من نحن')),
                ('about_content', models.TextField(blank=True, verbose_name='محتوى من نحن')),
                ('mission', models.TextField(blank=True, verbose_name='رسالتنا')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='وصف SEO')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-is_featured', '-is_promoted', '-created_at'], 'verbose_name': 'عقار', 'verbose_name_plural': 'العقارات'},
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='بغداد', max_length=100, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='المنطقة'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='عقار مميز'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_promoted',
            field=models.BooleanField(default=False, verbose_name='إعلان خاص'),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='property',
            name='promotion_until',
            field=models.DateField(blank=True, null=True, verbose_name='انتهاء الترويج'),
        ),
        migrations.AddField(
            model_name='property',
            name='province',
            field=models.CharField(choices=[('baghdad', 'بغداد'), ('basra', 'البصرة'), ('nineveh', 'نينوى'), ('erbil', 'أربيل'), ('sulaymaniyah', 'السليمانية'), ('duhok', 'دهوك'), ('kirkuk', 'كركوك'), ('diyala', 'ديالى'), ('anbar', 'الأنبار'), ('babylon', 'بابل'), ('karbala', 'كربلاء'), ('najaf', 'النجف'), ('wasit', 'واسط'), ('maysan', 'ميسان'), ('dhi_qar', 'ذي قار'), ('muthanna', 'المثنى'), ('qadisiyyah', 'القادسية'), ('salahuddin', 'صلاح الدين')], default='baghdad', max_length=30, verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='عنوان الإعلان'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.PositiveIntegerField(verbose_name='المساحة (م²)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد الحمامات'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد الغرف'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='floors',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد الطوابق'),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='property',
            name='images',
            field=models.TextField(blank=True, help_text='روابط صور إضافية (قديم)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=200, verbose_name='العنوان التفصيلي'),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='year_built',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سنة البناء'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['province', 'city'], name='properties__provinc_14c1b1_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['type', 'status'], name='properties__type_d3d96a_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='properties__price_32e7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['-created_at'], name='properties__created_9ef325_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_featured', 'is_promoted'], name='properties__is_feat_b56ef4_idx'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='properties.property', verbose_name='العقار'),
        ),
        migrations.RunPython(populate_property_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', max_length=220, unique=True),
        ),
    ]
