# Generated by Django 6.0.4 on 2026-06-11
# Database Optimization Migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_propertyimage_sitesettings_alter_property_options_and_more'),
    ]

    operations = [
        # Property model indexes
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city'], name='properties__city_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['district'], name='properties__district_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['views_count'], name='properties__views_count_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['promotion_until'], name='properties__promotion_until_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['phone'], name='properties__phone_idx'),
        ),
        # Composite index for common query pattern: province + city + type + status
        migrations.AddIndex(
            model_name='property',
            index=models.Index(
                fields=['province', 'city', 'type', 'status'],
                name='properties__search_idx'
            ),
        ),
        # Composite index for featured/promoted filtering
        migrations.AddIndex(
            model_name='property',
            index=models.Index(
                fields=['is_featured', 'is_promoted', 'created_at'],
                name='properties__featured_promoted_idx'
            ),
        ),
        
        # PropertyImage model indexes
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property'], name='properties__propertyimage_property_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['is_primary'], name='properties__propertyimage_is_primary_idx'),
        ),
        # Unique constraint to prevent duplicate sort orders per property
        migrations.AddConstraint(
            model_name='propertyimage',
            constraint=models.UniqueConstraint(
                fields=['property', 'sort_order'],
                name='unique_property_sort_order',
                violation_error_message='A property image with this sort order already exists.'
            ),
        ),
        
        # Message model indexes
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['property'], name='properties__message_property_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='properties__message_is_read_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='properties__message_created_at_idx'),
        ),
        # Composite index for dashboard queries
        migrations.AddIndex(
            model_name='message',
            index=models.Index(
                fields=['is_read', 'created_at'],
                name='properties__message_dashboard_idx'
            ),
        ),
        
        # SiteSettings unique constraint to enforce singleton pattern
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.UniqueConstraint(
                fields=['id'],
                condition=models.Q(id=1),
                name='sitesettings_singleton_enforce',
                violation_error_message='Only one SiteSettings record with id=1 is allowed.'
            ),
        ),
    ]
