# Generated by Django 6.0.6 on 2026-06-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_database_optimization'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='propertyimage',
            name='unique_property_sort_order',
        ),
        migrations.RemoveConstraint(
            model_name='sitesettings',
            name='sitesettings_singleton_enforce',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='properties__message_property_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='properties__message_is_read_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='properties__message_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='properties__message_dashboard_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties__provinc_14c1b1_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties__city_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties__views_count_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties__promotion_until_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties__phone_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties__search_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties__featured_promoted_idx',
        ),
        migrations.RemoveIndex(
            model_name='propertyimage',
            name='properties__propertyimage_property_idx',
        ),
        migrations.RemoveIndex(
            model_name='propertyimage',
            name='properties__propertyimage_is_primary_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='properties__distric_2e026e_idx',
            old_name='properties__district_idx',
        ),
        migrations.AddField(
            model_name='property',
            name='street',
            field=models.CharField(blank=True, help_text='اسم الشارع', max_length=100, verbose_name='الشارع'),
        ),
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.CharField(help_text='اسم الحي في الناصرية', max_length=100, verbose_name='الحي'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(help_text='العنوان الكامل', max_length=200, verbose_name='العنوان التفصيلي'),
        ),
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
        migrations.RemoveField(
            model_name='property',
            name='province',
        ),
    ]
