# Generated by Django 6.0.6 on 2026-06-13 01:21

import django.db.models.deletion
import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_remove_province_add_nasiriyah_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=properties.models.property_video_path, verbose_name='الفيديو')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='تعليق')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_videos', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'فيديو عقار',
                'verbose_name_plural': 'فيديوهات العقارات',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
