# Generated by Django 6.0.6 on 2026-06-15 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_propertyvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('urgent', 'عاجل')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتمل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='properties.property')),
            ],
            options={
                'verbose_name': 'ملاحظة عقار',
                'verbose_name_plural': 'ملاحظات العقارات',
                'ordering': ['-created_at'],
            },
        ),
    ]
