# Generated by Django 6.0.6 on 2026-06-15 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_propertynote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertynote',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='properties.property'),
        ),
    ]
