# Generated by Django 6.0.6 on 2026-06-15 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_notifications', models.BooleanField(default=True, verbose_name='تفعيل الإشعارات')),
                ('notify_new_property', models.BooleanField(default=True, verbose_name='إشعارات العقارات الجديدة')),
                ('notify_property_update', models.BooleanField(default=True, verbose_name='إشعارات تحديثات العقارات')),
                ('notify_price_change', models.BooleanField(default=True, verbose_name='إشعارات تغيير الأسعار')),
                ('notify_messages', models.BooleanField(default=True, verbose_name='إشعارات الرسائل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إعدادات المستخدم',
                'verbose_name_plural': 'إعدادات المستخدمين',
            },
        ),
    ]
