# Generated by Django 6.0.6 on 2026-06-17 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualTour360',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('image', models.ImageField(upload_to='virtual_tours/', verbose_name='صورة 360°')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_tours', to='properties.property')),
            ],
            options={
                'verbose_name': 'جولة افتراضية',
                'verbose_name_plural': 'الجولات الافتراضية',
                'ordering': ['order'],
            },
        ),
    ]
