# Generated by Django 6.0.6 on 2026-06-17 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_virtualtour360_delete_usersettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المزاد')),
                ('description', models.TextField(verbose_name='وصف المزاد')),
                ('starting_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='سعر البداية')),
                ('minimum_increment', models.DecimalField(decimal_places=0, default=100000, max_digits=15, verbose_name='أقل زيادة')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('upcoming', 'قادم'), ('active', 'نشط'), ('ended', 'منتهي'), ('cancelled', 'ملغي')], default='upcoming', max_length=20, verbose_name='الحالة')),
                ('deposit_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ التأمين')),
                ('terms', models.TextField(verbose_name='شروط المزاد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='properties.property')),
            ],
            options={
                'verbose_name': 'مزاد',
                'verbose_name_plural': 'المزادات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='المبلغ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المزايدة')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='properties.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مزايدة',
                'verbose_name_plural': 'المزايدات',
                'ordering': ['-amount', '-created_at'],
            },
        ),
    ]
