# Generated by Django 6.0.6 on 2026-06-17 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_auction_bid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('full', 'بناء كامل (تسليم مفتاح)'), ('design', 'تصميم معماري فقط'), ('supervision', 'إشراف هندسي فقط')], default='full', max_length=20, verbose_name='نوع الطلب')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('active', 'نشط'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('owner_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('owner_phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('owner_district', models.CharField(max_length=100, verbose_name='المنطقة')),
                ('owner_location', models.CharField(max_length=200, verbose_name='الموقع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'طلب بناء',
                'verbose_name_plural': 'طلبات البناء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuildingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floors', models.IntegerField(verbose_name='عدد الطوابق')),
                ('rooms', models.IntegerField(verbose_name='عدد الغرف')),
                ('bathrooms', models.IntegerField(verbose_name='عدد الحمامات')),
                ('has_garage', models.BooleanField(default=False, verbose_name='وجود كراج')),
                ('has_garden', models.BooleanField(default=False, verbose_name='وجود حديقة')),
                ('has_elevator', models.BooleanField(default=False, verbose_name='وجود مصعد')),
                ('architectural_style', models.CharField(choices=[('modern', 'مودرن'), ('classic', 'كلاسيكي'), ('contemporary', 'حديث')], max_length=20, verbose_name='النمط المعماري')),
                ('building_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='building_details', to='properties.buildingrequest')),
            ],
            options={
                'verbose_name': 'تفاصيل البناء',
                'verbose_name_plural': 'تفاصيل البناء',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_budget', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='الميزانية التقريبية')),
                ('finishing_level', models.CharField(choices=[('economy', 'اقتصادي'), ('medium', 'متوسط'), ('luxury', 'فاخر'), ('super_deluxe', 'سوبر ديلوكس')], max_length=20, verbose_name='مستوى التشطيب')),
                ('building_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='properties.buildingrequest')),
            ],
            options={
                'verbose_name': 'الميزانية',
                'verbose_name_plural': 'الميزانيات',
            },
        ),
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('pdf', 'مخطط PDF'), ('image', 'صور توضيحية'), ('autocad', 'ملف AutoCAD')], max_length=20, verbose_name='نوع الملف')),
                ('file', models.FileField(upload_to='building_blueprints/', verbose_name='الملف')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='الوصف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('building_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprints', to='properties.buildingrequest')),
            ],
            options={
                'verbose_name': 'مخطط',
                'verbose_name_plural': 'المخططات',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractorBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_name', models.CharField(max_length=200, verbose_name='اسم المقاول')),
                ('bid_amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ المزايدة')),
                ('bid_description', models.TextField(blank=True, verbose_name='وصف العرض')),
                ('is_winning', models.BooleanField(default=False, verbose_name='الفائز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المزايدة')),
                ('building_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_bids', to='properties.buildingrequest')),
            ],
            options={
                'verbose_name': 'مزايدة مقاول',
                'verbose_name_plural': 'مزايدات المقاولين',
                'ordering': ['-bid_amount', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_name', models.CharField(max_length=200, verbose_name='اسم المقاول')),
                ('rating', models.IntegerField(verbose_name='التقييم (1-5)')),
                ('review', models.TextField(verbose_name='التقييم المفصل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقييم')),
                ('building_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_ratings', to='properties.buildingrequest')),
            ],
            options={
                'verbose_name': 'تقييم مقاول',
                'verbose_name_plural': 'تقييمات المقاولين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('structure', 'استلام الهيكل'), ('finishing', 'استلام التشطيبات'), ('utilities', 'استلام الكهرباء والماء'), ('final', 'استلام المفتاح النهائي')], max_length=20, verbose_name='نوع المرحلة')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتمل')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإنجاز')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('building_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_milestones', to='properties.buildingrequest')),
            ],
            options={
                'verbose_name': 'مرحلة تسليم',
                'verbose_name_plural': 'مراحل التسليم',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LandInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_location', models.CharField(max_length=200, verbose_name='موقع القطعة')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مساحة الأرض (متر مربع)')),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='العرض (متر)')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الطول (متر)')),
                ('land_type', models.CharField(choices=[('residential', 'سكني'), ('commercial', 'تجاري'), ('agricultural', 'زراعي')], max_length=20, verbose_name='نوع الأرض')),
                ('deed_image', models.ImageField(blank=True, null=True, upload_to='building_deeds/', verbose_name='صورة السند أو المخطط')),
                ('building_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='land_info', to='properties.buildingrequest')),
            ],
            options={
                'verbose_name': 'معلومات الأرض',
                'verbose_name_plural': 'معلومات الأراضي',
            },
        ),
        migrations.CreateModel(
            name='ProjectTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.IntegerField(default=0, verbose_name='نسبة الإنجاز')),
                ('weekly_photos', models.TextField(blank=True, verbose_name='صور أسبوعية للموقع')),
                ('engineer_reports', models.TextField(blank=True, verbose_name='تقارير المهندس')),
                ('payment_schedule', models.TextField(blank=True, verbose_name='جدول الدفعات')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('building_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_tracking', to='properties.buildingrequest')),
            ],
            options={
                'verbose_name': 'متابعة المشروع',
                'verbose_name_plural': 'متابعة المشاريع',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_type', models.CharField(choices=[('company', 'عرض من شركة بناء'), ('engineer', 'عرض من مهندس')], max_length=20, verbose_name='نوع العرض')),
                ('provider_name', models.CharField(max_length=200, verbose_name='اسم المزود')),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='السعر')),
                ('duration_days', models.IntegerField(verbose_name='مدة التنفيذ (أيام)')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='مقبول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العرض')),
                ('building_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='properties.buildingrequest')),
            ],
            options={
                'verbose_name': 'عرض سعر',
                'verbose_name_plural': 'عروض الأسعار',
                'ordering': ['-created_at'],
            },
        ),
    ]
