# Generated by Django 6.0.6 on 2026-06-19 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_usersettings'),
        ('properties', '0015_add_auction_and_financial_fields'),
    ]

    operations = [
    ]
