# Generated by Django 6.0.6 on 2026-06-20 03:11

import django.db.models.deletion
import properties.models
from django.conf import settings
from django.db import migrations, models


def delete_usersettings_if_exists(apps, schema_editor):
    """Conditionally delete UserSettings model if it exists"""
    try:
        UserSettings = apps.get_model('properties', 'UserSettings')
        UserSettings.objects.all().delete()
    except:
        # Model doesn't exist, skip deletion
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_broker_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_auto_extended',
            field=models.BooleanField(default=False, verbose_name='تم التمديد التلقائي'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='access_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='كود الدخول'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='auction_type',
            field=models.CharField(choices=[('home', 'مزاد بيع منزل'), ('land', 'مزاد بيع أرض'), ('shop', 'مزاد بيع محل تجاري'), ('building', 'مزاد بيع عمارة'), ('investment', 'مزاد استثماري')], default='home', max_length=20, verbose_name='نوع المزاد'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='auto_extend_minutes',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='تمديد تلقائي (دقائق)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to=properties.models.property_image_path, verbose_name='صورة الإيصال'),
        ),
        migrations.CreateModel(
            name='AuctionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('identity_verified', models.BooleanField(default=False, verbose_name='تم توثيق الهوية')),
                ('deposit_paid', models.BooleanField(default=False, verbose_name='تم دفع التأمين')),
                ('deposit_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ التأمين المدفوع')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='properties.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مشارك في المزاد',
                'verbose_name_plural': 'المشاركون في المزادات',
                'unique_together': {('auction', 'user')},
            },
        ),
        migrations.RunPython(delete_usersettings_if_exists, migrations.RunPython.noop, atomic=False),
    ]
