# Generated by Django 5.0.6 on 2026-06-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_bid_is_auto_extended_alter_auction_access_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='access_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='كود الدخول'),
        ),
    ]
