# Generated by Django 5.0.6 on 2026-06-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_alter_auction_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='subscription_type',
            field=models.CharField(choices=[('basic', 'أساسي (250 عقار)'), ('silver', 'فضي (500 عقار)'), ('gold', 'ذهبي (1000 عقار)'), ('platinum', 'بلاتيني (1500 عقار)'), ('diamond', 'ماسي (2000 عقار)'), ('trial', 'تجريبي (15 يوم)')], default='trial', max_length=10, verbose_name='نوع الاشتراك'),
        ),
    ]
