# Generated by Django 5.0.6 on 2026-06-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_alter_broker_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='is_suspended',
            field=models.BooleanField(default=False, verbose_name='مجمد'),
        ),
        migrations.AddField(
            model_name='broker',
            name='subscription_duration',
            field=models.CharField(choices=[('week', 'أسبوع'), ('month', 'شهر'), ('year', 'سنة'), ('5_years', '5 سنوات'), ('10_years', '10 سنوات')], default='month', max_length=10, verbose_name='مدة الاشتراك'),
        ),
        migrations.AddField(
            model_name='broker',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الاشتراك'),
        ),
        migrations.AddField(
            model_name='broker',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية الاشتراك'),
        ),
    ]
