# Generated by Django 5.0.6 on 2026-06-21 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_broker_is_suspended_broker_subscription_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('user', 'بلاغ على مستخدم'), ('office', 'بلاغ على مكتب عقاري'), ('comment', 'بلاغ على تعليق أو مراجعة'), ('technical', 'بلاغ تقني')], max_length=20, verbose_name='نوع البلاغ')),
                ('reason', models.CharField(max_length=50, verbose_name='سبب البلاغ')),
                ('description', models.TextField(verbose_name='وصف المشكلة')),
                ('reported_comment', models.TextField(blank=True, verbose_name='التعليق المُبلَّغ عنه')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='المرفقات')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('reviewing', 'قيد المراجعة'), ('waiting_reporter', 'بانتظار رد المبلغ'), ('waiting_reported', 'بانتظار رد الطرف الآخر'), ('resolved', 'تم الحل'), ('rejected', 'مرفوض'), ('closed', 'مغلق')], default='new', max_length=20, verbose_name='حالة البلاغ')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات الإدارة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
                ('reported_broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='properties.broker', verbose_name='الدلال المُبلَّغ عنه')),
                ('reported_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='properties.office', verbose_name='المكتب المُبلَّغ عنه')),
                ('reported_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='properties.property', verbose_name='العقار المُبلَّغ عنه')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المُبلَّغ عنه')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='المُبلِّغ')),
            ],
            options={
                'verbose_name': 'بلاغ',
                'verbose_name_plural': 'البلاغات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('delete_ad', 'حذف الإعلان'), ('hide_ad', 'إخفاء الإعلان مؤقتًا'), ('suspend_account', 'إيقاف الحساب'), ('send_warning', 'إرسال تحذير'), ('request_edit', 'طلب تعديل البيانات'), ('reject_report', 'رفض البلاغ'), ('close_report', 'إغلاق البلاغ بعد الحل')], max_length=50, verbose_name='الإجراء')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإجراء')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_actions', to=settings.AUTH_USER_MODEL, verbose_name='قام بالإجراء')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='properties.report', verbose_name='البلاغ')),
            ],
            options={
                'verbose_name': 'إجراء بلاغ',
                'verbose_name_plural': 'إجراءات البلاغات',
                'ordering': ['-created_at'],
            },
        ),
    ]
