# Generated by Django 5.0.6 on 2026-06-22 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_message_message_type_message_recipient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='meta_description',
            new_name='seo_description',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_registration',
            field=models.BooleanField(default=True, verbose_name='السماح بالتسجيل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_video_upload',
            field=models.BooleanField(default=True, verbose_name='السماح برفع الفيديو'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_virtual_tours',
            field=models.BooleanField(default=True, verbose_name='السماح بالجولات الافتراضية'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allowed_image_types',
            field=models.CharField(default='jpg,jpeg,png,webp', max_length=200, verbose_name='أنواع الصور المسموحة'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allowed_video_types',
            field=models.CharField(default='mp4,webm', max_length=200, verbose_name='أنواع الفيديو المسموحة'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='api_key_required',
            field=models.BooleanField(default=True, verbose_name='تطلب مفتاح API'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='api_rate_limit',
            field=models.IntegerField(default=1000, verbose_name='حد الطلبات'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='area_unit',
            field=models.CharField(choices=[('m2', 'متر مربع'), ('ft2', 'قدم مربع')], default='m2', max_length=10, verbose_name='وحدة المساحة'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='auto_activate_accounts',
            field=models.BooleanField(default=True, verbose_name='تفعيل الحساب تلقائياً'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='auto_backup_enabled',
            field=models.BooleanField(default=False, verbose_name='النسخ الاحتياطي التلقائي'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='auto_review_reports',
            field=models.BooleanField(default=False, verbose_name='مراجعة تلقائية للبلاغات'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='backup_frequency',
            field=models.CharField(default='daily', max_length=20, verbose_name='تكرار النسخ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='backup_retention_days',
            field=models.IntegerField(default=30, verbose_name='مدة الاحتفاظ بالنسخ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='button_style',
            field=models.CharField(default='rounded', max_length=20, verbose_name='شكل الأزرار'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='date_format',
            field=models.CharField(default='Y-m-d', max_length=20, verbose_name='تنسيق التاريخ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_currency',
            field=models.CharField(default='IQD', max_length=3, verbose_name='العملة الافتراضية'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_language',
            field=models.CharField(default='ar', max_length=10, verbose_name='اللغة الافتراضية'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_user_role',
            field=models.CharField(default='user', max_length=20, verbose_name='الدور الافتراضي'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_api',
            field=models.BooleanField(default=False, verbose_name='تفعيل API'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_email_notifications',
            field=models.BooleanField(default=True, verbose_name='إشعارات البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_invoices',
            field=models.BooleanField(default=True, verbose_name='تفعيل الفواتير'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_og_tags',
            field=models.BooleanField(default=True, verbose_name='تفعيل Open Graph'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_push_notifications',
            field=models.BooleanField(default=False, verbose_name='الإشعارات الفورية'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_reports',
            field=models.BooleanField(default=True, verbose_name='تفعيل البلاغات'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_site_notifications',
            field=models.BooleanField(default=True, verbose_name='إشعارات داخل الموقع'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_sms_notifications',
            field=models.BooleanField(default=False, verbose_name='إشعارات الرسائل النصية'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_subscriptions',
            field=models.BooleanField(default=True, verbose_name='تفعيل الاشتراكات'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_two_factor',
            field=models.BooleanField(default=False, verbose_name='المصادقة الثنائية'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='site/', verbose_name='الأيقونة (Favicon)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_properties_count',
            field=models.IntegerField(default=6, verbose_name='عدد العقارات المميزة'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='font_family',
            field=models.CharField(default='Cairo', max_length=50, verbose_name='نوع الخط'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='font_size',
            field=models.IntegerField(default=16, verbose_name='حجم الخط'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_banner_image',
            field=models.ImageField(blank=True, upload_to='site/', verbose_name='صورة البنر'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_banner_subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='عنوان فرعي للبنر'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_banner_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان البنر الرئيسي'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='latest_properties_count',
            field=models.IntegerField(default=12, verbose_name='عدد أحدث العقارات'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='layout_style',
            field=models.CharField(default='boxed', max_length=20, verbose_name='تخطيط الصفحة'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='license_key',
            field=models.CharField(blank=True, max_length=100, verbose_name='مفتاح الترخيص'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='لينكد إن'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='log_login_attempts',
            field=models.BooleanField(default=True, verbose_name='تسجيل محاولات الدخول'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_image_size',
            field=models.IntegerField(default=5242880, verbose_name='الحد الأقصى لحجم الصور (بايت)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_images_per_property',
            field=models.IntegerField(default=20, verbose_name='الحد الأقصى للصور'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_video_size',
            field=models.IntegerField(default=52428800, verbose_name='الحد الأقصى لحجم الفيديو (بايت)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='password_min_length',
            field=models.IntegerField(default=8, verbose_name='الحد الأدنى لكلمة المرور'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_methods',
            field=models.CharField(default='cash,bank_transfer', max_length=200, verbose_name='طرق الدفع'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#0d9488', max_length=7, verbose_name='اللون الرئيسي'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='report_priority_threshold',
            field=models.CharField(default='high', max_length=20, verbose_name='عتبة أولوية البلاغات'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='require_email_verification',
            field=models.BooleanField(default=False, verbose_name='التحقق من البريد'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='require_phone_verification',
            field=models.BooleanField(default=False, verbose_name='التحقق من الهاتف'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='require_special_chars',
            field=models.BooleanField(default=True, verbose_name='تطلب أحرف خاصة'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#f97316', max_length=7, verbose_name='اللون الثانوي'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='الكلمات المفتاحية'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان الموقع'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='session_timeout',
            field=models.IntegerField(default=3600, verbose_name='مدة الجلسة (ثواني)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_brokers_section',
            field=models.BooleanField(default=True, verbose_name='إظهار قسم الدلالين'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_featured_properties',
            field=models.BooleanField(default=True, verbose_name='إظهار العقارات المميزة'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_latest_properties',
            field=models.BooleanField(default=True, verbose_name='إظهار أحدث العقارات'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(blank=True, verbose_name='وصف الموقع'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='subscription_price_monthly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر الاشتراك الشهري'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='subscription_price_yearly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر الاشتراك السنوي'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='system_version',
            field=models.CharField(default='1.0.0', max_length=20, verbose_name='إصدار النظام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'فاتح'), ('dark', 'داكن')], default='light', max_length=10, verbose_name='الوضع'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='time_format',
            field=models.CharField(default='H:i', max_length=20, verbose_name='تنسيق الوقت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='timezone',
            field=models.CharField(default='Asia/Baghdad', max_length=50, verbose_name='المنطقة الزمنية'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='تويتر'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='external_service',
            field=models.CharField(blank=True, choices=[('matterport', 'Matterport'), ('kuula', 'Kuula'), ('google', 'Google Street View'), ('other', 'خدمة أخرى')], max_length=20, verbose_name='خدمة خارجية'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='external_url',
            field=models.URLField(blank=True, verbose_name='رابط خارجي'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='tour_file',
            field=models.FileField(blank=True, null=True, upload_to='virtual_tours/files/', verbose_name='ملف الجولة'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='tour_type',
            field=models.CharField(choices=[('image', 'صورة بانورامية 360°'), ('file', 'ملف جولة 360° جاهز'), ('external', 'رابط خارجي'), ('multi', 'جولة من عدة صور مترابطة')], default='image', max_length=20, verbose_name='نوع الجولة'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='فيسبوك'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='إنستغرام'),
        ),
        migrations.AlterField(
            model_name='virtualtour360',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='virtual_tours/', verbose_name='صورة 360°'),
        ),
        migrations.CreateModel(
            name='PropertyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوى التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعليق')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='properties.propertycomment', verbose_name='رد على')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='properties.property', verbose_name='العقار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_comments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تعليق',
                'verbose_name_plural': 'التعليقات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VirtualTourPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم النقطة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('image', models.ImageField(upload_to='virtual_tours/points/', verbose_name='صورة 360° للنقطة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('virtual_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_points', to='properties.virtualtour360')),
            ],
            options={
                'verbose_name': 'نقطة جولة',
                'verbose_name_plural': 'نقاط الجولة',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PropertyLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإعجاب')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='properties.property', verbose_name='العقار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_likes', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إعجاب',
                'verbose_name_plural': 'الإعجابات',
                'ordering': ['-created_at'],
                'unique_together': {('property', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PropertySave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحفظ')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='properties.property', verbose_name='العقار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_saves', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'حفظ',
                'verbose_name_plural': 'المحفوظات',
                'ordering': ['-created_at'],
                'unique_together': {('property', 'user')},
            },
        ),
        migrations.CreateModel(
            name='VirtualTourConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='التسمية')),
                ('from_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='properties.virtualtourpoint')),
                ('to_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='properties.virtualtourpoint')),
            ],
            options={
                'verbose_name': 'اتصال جولة',
                'verbose_name_plural': 'اتصالات الجولة',
                'unique_together': {('from_point', 'to_point')},
            },
        ),
    ]
