# Generated by Django 5.0.6 on 2026-06-22 03:06

from django.db import migrations


def noop(apps, schema_editor):
    """No-op migration - UserSettings table doesn't exist"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_add_favicon_field'),
    ]

    operations = [
        migrations.RunPython(noop, migrations.RunPython.noop),
    ]
