# Generated by Django 5.0.6 on 2026-06-22 14:19

from django.db import connection, migrations


def delete_usersettings_if_exists(apps, schema_editor):
    """Conditionally delete UserSettings rows if the table exists."""
    table_names = connection.introspection.table_names()
    if 'properties_usersettings' not in table_names:
        return
    UserSettings = apps.get_model('properties', 'UserSettings')
    UserSettings.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0025_delete_usersettings'),
    ]

    operations = [
        migrations.RunPython(delete_usersettings_if_exists, migrations.RunPython.noop),
    ]
