# Generated by Django 5.0.6 on 2026-06-22 16:58

from django.db import connection, migrations


def drop_usersettings_table_if_exists(apps, schema_editor):
    """Drop UserSettings table only when it exists (handles partial migration history)."""
    table_names = connection.introspection.table_names()
    if 'properties_usersettings' in table_names:
        schema_editor.execute('DROP TABLE "properties_usersettings"')


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0026_delete_usersettings'),
    ]

    operations = [
        migrations.RunPython(
            drop_usersettings_table_if_exists,
            migrations.RunPython.noop,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='UserSettings',
                ),
            ],
        ),
    ]
