# Generated by Django 5.0.6 on 2026-06-22 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0027_delete_usersettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], verbose_name='التقييم العام')),
                ('professionalism_rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5', null=True, verbose_name='الاحترافية')),
                ('responsiveness_rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5', null=True, verbose_name='سرعة الرد')),
                ('knowledge_rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5', null=True, verbose_name='المعرفة بالسوق')),
                ('honesty_rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5', null=True, verbose_name='الأمانة')),
                ('review', models.TextField(blank=True, verbose_name='مراجعة مفصلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقييم')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='properties.broker', verbose_name='الدلال')),
                ('property_dealt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_ratings', to='properties.property', verbose_name='العقار المتعامل معه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_ratings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تقييم دلال',
                'verbose_name_plural': 'تقييمات الدلالين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], verbose_name='التقييم')),
                ('location_rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5', null=True, verbose_name='تقييم الموقع')),
                ('price_rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5', null=True, verbose_name='تقييم السعر')),
                ('condition_rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5', null=True, verbose_name='تقييم الحالة')),
                ('communication_rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5', null=True, verbose_name='تقييم التواصل')),
                ('review', models.TextField(blank=True, verbose_name='مراجعة مفصلة')),
                ('is_verified', models.BooleanField(default=False, help_text='هل قام المستخدم بزيارة العقار فعلياً؟', verbose_name='مراجعة موثقة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقييم')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('property_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='properties.property', verbose_name='العقار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_ratings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تقييم عقار',
                'verbose_name_plural': 'تقييمات العقارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='brokerrating',
            index=models.Index(fields=['broker', 'rating'], name='properties__broker__bf1cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerrating',
            index=models.Index(fields=['-rating'], name='properties__rating_61200a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='brokerrating',
            unique_together={('broker', 'user')},
        ),
        migrations.AddIndex(
            model_name='propertyrating',
            index=models.Index(fields=['property_obj', 'rating'], name='properties__propert_d5eee1_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyrating',
            index=models.Index(fields=['-rating'], name='properties__rating_38a724_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyrating',
            unique_together={('property_obj', 'user')},
        ),
    ]
