# Generated by Django 5.0.6 on 2026-06-22 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0028_brokerrating_propertyrating_delete_usersettings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('totp', 'تطبيق المصادقة (TOTP)'), ('sms', 'رسالة نصية (SMS)'), ('email', 'بريد إلكتروني')], default='totp', max_length=10, verbose_name='طريقة المصادقة')),
                ('secret_key', models.CharField(blank=True, max_length=32, verbose_name='مفتاح سري')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='مفعل')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف للـ SMS')),
                ('backup_codes', models.JSONField(blank=True, default=list, verbose_name='رموز النسخ الاحتياطي')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='آخر استخدام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_auth', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مصادقة ثنائية',
                'verbose_name_plural': 'المصادقات الثنائية',
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'تسجيل دخول'), ('login_failed', 'فشل تسجيل الدخول'), ('logout', 'تسجيل خروج'), ('password_change', 'تغيير كلمة المرور'), ('2fa_enabled', 'تفعيل المصادقة الثنائية'), ('2fa_disabled', 'تعطيل المصادقة الثنائية'), ('2fa_verify', 'التحقق من المصادقة الثنائية'), ('password_reset', 'إعادة تعيين كلمة المرور'), ('suspicious_activity', 'نشاط مشبوه')], max_length=30, verbose_name='الإجراء')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='معلومات المتصفح')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='تفاصيل إضافية')),
                ('success', models.BooleanField(default=True, verbose_name='نجاح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل أمان',
                'verbose_name_plural': 'سجلات الأمان',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='properties__user_id_e3d879_idx'), models.Index(fields=['action', '-created_at'], name='properties__action_2c7dd5_idx'), models.Index(fields=['ip_address'], name='properties__ip_addr_c1777f_idx')],
            },
        ),
    ]
