# Generated by Django 6.0.6 on 2026-06-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0030_remove_image_field_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
        migrations.AlterField(
            model_name='broker',
            name='subscription_duration',
            field=models.CharField(choices=[('month', 'شهر'), ('3_months', '3 أشهر'), ('6_months', '6 أشهر'), ('year', 'سنة'), ('5_years', '5 سنوات'), ('unlimited', 'غير محدود')], default='month', max_length=10, verbose_name='مدة الاشتراك'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='subscription_type',
            field=models.CharField(choices=[('month', 'شهر (20 عقار)'), ('3_months', '3 أشهر (60 عقار)'), ('6_months', '6 أشهر (120 عقار)'), ('year', 'سنة (300 عقار)'), ('5_years', '5 سنوات (2000 عقار)'), ('unlimited', 'غير محدود')], default='month', max_length=10, verbose_name='نوع الاشتراك'),
        ),
    ]
