# Generated by Django 6.0.6 on 2026-06-28 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0031_remove_property_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicDallalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_properties', models.IntegerField(default=20, verbose_name='الحد الأقصى للعقارات')),
                ('duration_days', models.IntegerField(default=30, verbose_name='مدة الاشتراك بالأيام')),
                ('auto_renewal', models.BooleanField(default=False, verbose_name='التجديد التلقائي')),
                ('impressions_limit', models.IntegerField(default=1000, verbose_name='الحد الأقصى للظهور')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='التكلفة')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='تفعيل الدلال العادي')),
            ],
            options={
                'verbose_name': 'إعدادات الدلال العادي',
                'verbose_name_plural': 'إعدادات الدلال العادي',
            },
        ),
        migrations.CreateModel(
            name='DallalGlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dallal_system_enabled', models.BooleanField(default=True, verbose_name='تفعيل نظام الدلال')),
                ('max_brokers_per_user', models.IntegerField(default=1, verbose_name='الحد الأقصى للدلالات لكل مستخدم')),
                ('max_properties_per_dallal', models.IntegerField(default=100, verbose_name='الحد الأقصى للعقارات لكل دلال')),
                ('show_dallal_on_homepage', models.BooleanField(default=True, verbose_name='عرض الدلال في الصفحة الرئيسية')),
                ('dallal_display_order', models.CharField(choices=[('premium_first', 'المميز أولاً ثم العادي'), ('basic_first', 'العادي أولاً ثم المميز'), ('mixed', 'مختلط')], default='premium_first', max_length=20, verbose_name='ترتيب ظهور الدلال')),
                ('show_expired_dallal', models.BooleanField(default=False, verbose_name='عرض الدلال المنتهي')),
            ],
            options={
                'verbose_name': 'إعدادات الدلال العامة',
                'verbose_name_plural': 'إعدادات الدلال العامة',
            },
        ),
        migrations.CreateModel(
            name='DallalSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('basic', 'دلال عادي'), ('premium', 'دلال مميز')], max_length=10, verbose_name='نوع الاشتراك')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('properties_used', models.IntegerField(default=0, verbose_name='العقارات المستخدمة')),
                ('impressions_count', models.IntegerField(default=0, verbose_name='عدد الظهور')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('auto_renewal', models.BooleanField(default=False, verbose_name='التجديد التلقائي')),
            ],
            options={
                'verbose_name': 'اشتراك دلال',
                'verbose_name_plural': 'اشتراكات الدلال',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PremiumDallalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_properties', models.IntegerField(default=100, verbose_name='الحد الأقصى للعقارات')),
                ('duration_days', models.IntegerField(default=90, verbose_name='مدة الاشتراك بالأيام')),
                ('priority_display', models.BooleanField(default=True, verbose_name='أولوية الظهور')),
                ('impressions_limit', models.IntegerField(default=5000, verbose_name='الحد الأقصى للظهور')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='التكلفة')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='تفعيل الدلال المميز')),
                ('visual_badge', models.BooleanField(default=True, verbose_name='تمييز بصري (Badge)')),
                ('highlight_effect', models.BooleanField(default=True, verbose_name='تأثير التمييز (Glow)')),
            ],
            options={
                'verbose_name': 'إعدادات الدلال المميز',
                'verbose_name_plural': 'إعدادات الدلال المميز',
            },
        ),
        migrations.CreateModel(
            name='PropertyDallalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الربط')),
            ],
            options={
                'verbose_name': 'ربط عقار بدلال',
                'verbose_name_plural': 'ربط العقارات بالدلال',
            },
        ),
        migrations.RemoveIndex(
            model_name='securitylog',
            name='properties__user_id_e3d879_idx',
        ),
        migrations.RemoveIndex(
            model_name='securitylog',
            name='properties__action_2c7dd5_idx',
        ),
        migrations.RemoveIndex(
            model_name='securitylog',
            name='properties__ip_addr_c1777f_idx',
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='details',
            field=models.JSONField(blank=True, null=True, verbose_name='التفاصيل'),
        ),
        migrations.AddField(
            model_name='dallalsubscription',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dallal_subscriptions', to='properties.broker', verbose_name='الدلال'),
        ),
        migrations.AddField(
            model_name='propertydallalassignment',
            name='dallal_subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_assignments', to='properties.dallalsubscription', verbose_name='اشتراك الدلال'),
        ),
        migrations.AddField(
            model_name='propertydallalassignment',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dallal_assignments', to='properties.property', verbose_name='العقار'),
        ),
        migrations.AlterUniqueTogether(
            name='propertydallalassignment',
            unique_together={('property', 'dallal_subscription')},
        ),
    ]
