# Generated by Django 6.0.6 on 2026-06-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0032_basicdallalsettings_dallalglobalsettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('ready', 'جاهز'), ('under-construction', 'قيد الإنشاء'), ('sold', 'مباع'), ('rent', 'للإيجار'), ('sale', 'للبيع'), ('investment', 'استثمار')], default='ready', max_length=20, verbose_name='الحالة'),
        ),
    ]
