# Generated by Django 6.0.6 on 2026-06-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0033_alter_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='owner_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='المبلغ المستحق لصاحب العقار'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم صاحب العقار'),
        ),
    ]
