# Generated by Django 6.0.6 on 2026-06-28 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0034_alter_expense_amount_alter_expense_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildingrequest',
            options={'ordering': ['-created_at', '-priority'], 'verbose_name': 'طلب بناء', 'verbose_name_plural': 'طلبات البناء'},
        ),
        migrations.RemoveField(
            model_name='buildingrequest',
            name='owner_district',
        ),
        migrations.RemoveField(
            model_name='buildingrequest',
            name='owner_location',
        ),
        migrations.RemoveField(
            model_name='buildingrequest',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='buildingrequest',
            name='owner_phone',
        ),
        migrations.RemoveField(
            model_name='buildingrequest',
            name='request_type',
        ),
        migrations.AddField(
            model_name='buildingrequest',
            name='address',
            field=models.TextField(blank=True, verbose_name='العنوان التفصيلي'),
        ),
        migrations.AddField(
            model_name='buildingrequest',
            name='assigned_broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_building_requests', to='properties.broker', verbose_name='الدلال المكلف'),
        ),
        migrations.AddField(
            model_name='buildingrequest',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='buildingrequest',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف المشروع'),
        ),
        migrations.AddField(
            model_name='buildingrequest',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='المنطقة'),
        ),
        migrations.AddField(
            model_name='buildingrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='buildingrequest',
            name='estimated_area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='المساحة المقدرة (م²)'),
        ),
        migrations.AddField(
            model_name='buildingrequest',
            name='estimated_budget',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='الميزانية المقدرة'),
        ),
        migrations.AddField(
            model_name='buildingrequest',
            name='expected_completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الإنجاز المتوقع'),
        ),
        migrations.AddField(
            model_name='buildingrequest',
            name='expected_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ البدء المتوقع'),
        ),
        migrations.AddField(
            model_name='buildingrequest',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='الاسم الكامل'),
        ),
        migrations.AddField(
            model_name='buildingrequest',
            name='governorate',
            field=models.CharField(blank=True, choices=[('BAG', 'بغداد'), ('BAS', 'البصرة'), ('NIN', 'نينوى'), ('ERB', 'أربيل'), ('NAJ', 'النجف'), ('KAR', 'كربلاء'), ('BAB', 'بابل'), ('DHI', 'ذي قار'), ('DIA', 'ديالى'), ('KIR', 'كركوك'), ('ANB', 'الأنبار'), ('WAS', 'واسط'), ('MUT', 'ميسان'), ('MUTH', 'المثنى'), ('QAD', 'القادسية (الديوانية)'), ('SAL', 'صلاح الدين'), ('DUH', 'دهوك'), ('SUL', 'السليمانية'), ('HAL', 'حلبجة'), ('KIRKUK', 'كركوك')], max_length=100, verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='buildingrequest',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات الإدارة'),
        ),
        migrations.AddField(
            model_name='buildingrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='buildingrequest',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('urgent', 'عاجل')], default='medium', max_length=20, verbose_name='الأولوية'),
        ),
        migrations.AddField(
            model_name='buildingrequest',
            name='project_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='نوع المشروع'),
        ),
        migrations.AddField(
            model_name='buildingrequest',
            name='requirements',
            field=models.TextField(blank=True, verbose_name='المتطلبات الخاصة'),
        ),
        migrations.AlterField(
            model_name='buildingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_review', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='buildingrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_requests', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddIndex(
            model_name='buildingrequest',
            index=models.Index(fields=['governorate'], name='properties__governo_7eebd0_idx'),
        ),
        migrations.AddIndex(
            model_name='buildingrequest',
            index=models.Index(fields=['status'], name='properties__status_824dbb_idx'),
        ),
        migrations.AddIndex(
            model_name='buildingrequest',
            index=models.Index(fields=['priority'], name='properties__priorit_445f24_idx'),
        ),
        migrations.AddIndex(
            model_name='buildingrequest',
            index=models.Index(fields=['-created_at'], name='properties__created_e4c9e0_idx'),
        ),
    ]
