# Generated by Django 6.0.6 on 2026-06-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0035_alter_buildingrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, choices=[('residential', 'سكني'), ('commercial', 'تجاري'), ('investment', 'استثماري'), ('tourism', 'سياحي'), ('land', 'أراضي')], max_length=20, null=True, verbose_name='تصنيف العقار'),
        ),
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.CharField(help_text='اسم الحي', max_length=100, verbose_name='الحي'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('sale', 'بيع'), ('rent', 'إيجار'), ('investment', 'استثمار')], default='ready', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('house', 'بيت'), ('apartment', 'شقة'), ('villa', 'فيلا'), ('duplex', 'دوبلكس'), ('residential_complex', 'مجمع سكني'), ('shop', 'محل'), ('office', 'مكتب'), ('mall', 'مول / مركز تجاري'), ('car_showroom', 'معرض سيارات'), ('warehouse', 'مخزن'), ('residential_building', 'بناية سكنية'), ('commercial_building', 'عمارة تجارية'), ('investment_land', 'أرض للاستثمار'), ('apartment_complex', 'مجمع شقق'), ('small_hotel', 'فندق صغير'), ('chalet', 'شاليه'), ('resort', 'منتجع'), ('hotel', 'فندق'), ('hotel_apartment', 'شقق فندقية'), ('tourism_house', 'بيت سياحي'), ('residential_land', 'أرض سكنية'), ('agricultural_land', 'أرض زراعية'), ('commercial_land', 'أرض تجارية'), ('investment_land', 'أرض استثمارية')], max_length=50, verbose_name='نوع العقار'),
        ),
    ]
