# Generated by Django 6.0.6 on 2026-06-28 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0036_property_category_alter_property_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'يومي'), ('monthly', 'شهري'), ('yearly', 'سنوي'), ('5_years', '5 سنوات')], max_length=20, verbose_name='فترة الاشتراك')),
                ('ads_limit', models.PositiveIntegerField(verbose_name='حد الإعلانات')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الخطة')),
                ('color', models.CharField(max_length=50, verbose_name='اللون')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'خطة اشتراك',
                'verbose_name_plural': 'خطط الاشتراك',
                'ordering': ['period', 'ads_limit'],
            },
        ),
        migrations.RemoveField(
            model_name='broker',
            name='subscription_duration',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='subscription_type',
        ),
        migrations.AddField(
            model_name='broker',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brokers', to='properties.subscriptionplan', verbose_name='خطة الاشتراك'),
        ),
    ]
