# Generated by Django 6.0.6 on 2026-06-28 19:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0037_subscriptionplan_remove_broker_subscription_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_type', models.CharField(choices=[('sale', 'بيع عقار'), ('rent', 'إيجار عقار'), ('commission', 'عمولة'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الربح')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ الربح')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='اسم العميل')),
                ('client_phone', models.CharField(blank=True, max_length=20, verbose_name='رقم العميل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الربح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profits', to='properties.property', verbose_name='العقار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profits', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ربح',
                'verbose_name_plural': 'الأرباح',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
