# Generated by Django 6.0.6 on 2026-06-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0038_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='custom_ads_limit',
            field=models.PositiveIntegerField(blank=True, help_text='عدد العقارات المسموح به (يستخدم بدلاً من خطة الاشتراك إذا تم تحديده)', null=True, verbose_name='عدد العقارات المخصص'),
        ),
    ]
