# Generated by Django 6.0.6 on 2026-06-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0041_remove_notification_property_notification_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualtour360',
            name='auto_rotate',
            field=models.BooleanField(default=False, verbose_name='تدوير تلقائي'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='auto_rotate_speed',
            field=models.IntegerField(default=1, verbose_name='سرعة التدوير'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='autoplay_duration',
            field=models.IntegerField(default=10, verbose_name='مدة التشغيل التلقائي (ثواني)'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='enable_fullscreen',
            field=models.BooleanField(default=True, verbose_name='تفعيل ملء الشاشة'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='enable_vr',
            field=models.BooleanField(default=False, verbose_name='تفعيل دعم VR'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='enable_zoom',
            field=models.BooleanField(default=True, verbose_name='تفعيل التكبير'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='initial_view_pitch',
            field=models.FloatField(default=0, verbose_name='زاوية الميل الأولية'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='initial_view_yaw',
            field=models.FloatField(default=0, verbose_name='زاوية الدوران الأولية'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='max_zoom',
            field=models.FloatField(default=3.0, verbose_name='أقصى تكبير'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='min_zoom',
            field=models.FloatField(default=0.5, verbose_name='أدنى تكبير'),
        ),
        migrations.AddField(
            model_name='virtualtour360',
            name='start_in_autoplay',
            field=models.BooleanField(default=False, verbose_name='بدء التشغيل التلقائي'),
        ),
    ]
