# Generated by Django 6.0.6 on 2026-06-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0042_virtualtour360_auto_rotate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='can_add_properties',
            field=models.BooleanField(default=True, verbose_name='يمكن إضافة عقارات'),
        ),
        migrations.AddField(
            model_name='broker',
            name='can_delete_properties',
            field=models.BooleanField(default=False, verbose_name='يمكن حذف عقارات'),
        ),
        migrations.AddField(
            model_name='broker',
            name='can_edit_properties',
            field=models.BooleanField(default=True, verbose_name='يمكن تعديل عقارات'),
        ),
        migrations.AddField(
            model_name='broker',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='نسبة العمولة من مبيعات العقارات (0-100)', max_digits=5, null=True, verbose_name='نسبة العمولة'),
        ),
        migrations.AddField(
            model_name='broker',
            name='commission_type',
            field=models.CharField(choices=[('percentage', 'نسبة مئوية'), ('fixed', 'مبلغ ثابت')], default='percentage', max_length=20, verbose_name='نوع العمولة'),
        ),
        migrations.AddField(
            model_name='broker',
            name='fixed_commission',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='مبلغ العمولة الثابت لكل عقار', max_digits=10, null=True, verbose_name='العمولة الثابتة'),
        ),
        migrations.AddField(
            model_name='broker',
            name='max_properties',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأقصى للعقارات'),
        ),
        migrations.AddField(
            model_name='broker',
            name='paid_commissions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='العمولات المدفوعة'),
        ),
        migrations.AddField(
            model_name='broker',
            name='pending_commissions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='العمولات المعلقة'),
        ),
        migrations.AddField(
            model_name='broker',
            name='performance_rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='تقييم الأداء من 0 إلى 5', max_digits=3, null=True, verbose_name='تقييم الأداء'),
        ),
        migrations.AddField(
            model_name='broker',
            name='sales_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المبيعات'),
        ),
        migrations.AddField(
            model_name='broker',
            name='target_sales',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='هدف المبيعات'),
        ),
        migrations.AddField(
            model_name='broker',
            name='total_commissions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي العمولات'),
        ),
    ]
