# Generated by Django 6.0.6 on 2026-06-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0043_broker_can_add_properties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deleted_by_recipient',
            field=models.BooleanField(default=False, verbose_name='محذوف من المستلم'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted_by_sender',
            field=models.BooleanField(default=False, verbose_name='محذوف من المرسل'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='مقروء'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('property_inquiry', 'استفسار عن عقار'), ('broker_message', 'رسالة بين دلالين'), ('user_broker', 'رسالة بين مستخدم ودلال')], default='property_inquiry', max_length=20, verbose_name='نوع الرسالة'),
        ),
    ]
