# Generated by Django 6.0.6 on 2026-06-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0044_message_is_deleted_by_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='paid_view_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='عمولة المشاهدات المدفوعة'),
        ),
        migrations.AddField(
            model_name='property',
            name='pending_view_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='عمولة المشاهدات المعلقة'),
        ),
        migrations.AddField(
            model_name='property',
            name='total_view_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي عمولة المشاهدات'),
        ),
        migrations.AddField(
            model_name='property',
            name='view_commission_rate',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='عمولة كل مشاهدة للعقار', max_digits=10, verbose_name='عمولة المشاهدة (دينار)'),
        ),
    ]
