# Generated by Django 6.0.6 on 2026-06-29 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0045_property_paid_view_commission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم البحث')),
                ('filters', models.JSONField(verbose_name='الفلاتر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحفظ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'بحث محفوظ',
                'verbose_name_plural': 'عمليات البحث المحفوظة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('governorate', models.CharField(blank=True, choices=[('BAG', 'بغداد'), ('BAS', 'البصرة'), ('NIN', 'نينوى'), ('ERB', 'أربيل'), ('NAJ', 'النجف'), ('KAR', 'كربلاء'), ('BAB', 'بابل'), ('DHI', 'ذي قار'), ('DIA', 'ديالى'), ('KIR', 'كركوك'), ('ANB', 'الأنبار'), ('WAS', 'واسط'), ('MUT', 'ميسان'), ('MUTH', 'المثنى'), ('QAD', 'القادسية (الديوانية)'), ('SAL', 'صلاح الدين'), ('DUH', 'دهوك'), ('SUL', 'السليمانية'), ('HAL', 'حلبجة'), ('KIRKUK', 'كركوك')], max_length=50, verbose_name='المحافظة')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('bio', models.TextField(blank=True, verbose_name='نبذة قصيرة')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='المصادقة الثنائية مفعلة')),
                ('notification_new_properties', models.BooleanField(default=True, verbose_name='إشعارات العقارات الجديدة')),
                ('notification_messages', models.BooleanField(default=True, verbose_name='إشعارات الرسائل')),
                ('notification_offers', models.BooleanField(default=True, verbose_name='إشعارات العروض والخصومات')),
                ('notification_matching', models.BooleanField(default=True, verbose_name='إشعارات العقارات المطابقة')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='إشعارات البريد الإلكتروني')),
                ('app_notifications', models.BooleanField(default=True, verbose_name='إشعارات التطبيق')),
                ('show_phone', models.BooleanField(default=True, verbose_name='إظهار رقم الهاتف')),
                ('show_email', models.BooleanField(default=False, verbose_name='إظهار البريد الإلكتروني')),
                ('who_can_message', models.CharField(choices=[('everyone', 'الجميع'), ('favorites', 'المفضلة فقط'), ('none', 'لا أحد')], default='everyone', max_length=20, verbose_name='من يمكنه مراسلتي')),
                ('dark_mode', models.BooleanField(default=False, verbose_name='الوضع الليلي')),
                ('language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=5, verbose_name='اللغة')),
                ('currency', models.CharField(choices=[('IQD', 'دينار عراقي'), ('USD', 'دولار أمريكي')], default='IQD', max_length=3, verbose_name='العملة')),
                ('property_view_mode', models.CharField(choices=[('grid', 'شبكة'), ('list', 'قائمة')], default='grid', max_length=10, verbose_name='طريقة عرض العقارات')),
                ('properties_per_page', models.IntegerField(choices=[(6, 6), (12, 12), (24, 24), (48, 48)], default=12, verbose_name='عدد العقارات في الصفحة')),
                ('account_disabled', models.BooleanField(default=False, verbose_name='حساب معطل مؤقتاً')),
                ('disabled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التعطيل')),
                ('disabled_reason', models.TextField(blank=True, verbose_name='سبب التعطيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إعدادات المستخدم',
                'verbose_name_plural': 'إعدادات المستخدمين',
            },
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحظر')),
                ('reason', models.TextField(blank=True, verbose_name='السبب')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL, verbose_name='المحظور')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL, verbose_name='الحاجب')),
            ],
            options={
                'verbose_name': 'مستخدم محظور',
                'verbose_name_plural': 'المستخدمون المحظورون',
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
