# Generated by Django 6.0.6 on 2026-06-29 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0047_savedsearch_usersettings_blockeduser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficePresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', 'متواجد الآن في المكتب'), ('busy', 'مشغول مع عميل'), ('offline', 'غير متواجد'), ('out', 'خارج المكتب'), ('remote', 'يعمل عن بُعد'), ('closed', 'المكتب مغلق'), ('vacation', 'في إجازة')], default='offline', max_length=20, verbose_name='الحالة')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='آخر ظهور')),
                ('expected_return', models.DateTimeField(blank=True, null=True, verbose_name='العودة المتوقعة')),
                ('absence_reason', models.TextField(blank=True, verbose_name='سبب الغياب')),
                ('auto_update_enabled', models.BooleanField(default=True, verbose_name='تحديث تلقائي حسب ساعات العمل')),
                ('work_start', models.TimeField(blank=True, null=True, verbose_name='بداية العمل')),
                ('work_end', models.TimeField(blank=True, null=True, verbose_name='نهاية العمل')),
                ('work_days', models.JSONField(default=list, verbose_name='أيام العمل')),
                ('total_online_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي ساعات التواجد')),
                ('last_online_duration', models.DurationField(blank=True, null=True, verbose_name='مدة آخر تواجد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to='properties.office', verbose_name='المكتب')),
            ],
            options={
                'verbose_name': 'حالة تواجد المكتب',
                'verbose_name_plural': 'حالات تواجد المكاتب',
            },
        ),
        migrations.CreateModel(
            name='PresenceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notified', models.BooleanField(default=False, verbose_name='تم الإشعار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاشتراك')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإشعار')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_subscribers', to='properties.office', verbose_name='المكتب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار تواجد',
                'verbose_name_plural': 'إشعارات التواجد',
                'unique_together': {('user', 'office')},
            },
        ),
    ]
