# Generated by Django 6.0.6 on 2026-06-29 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0048_officepresence_presencenotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerSubscriptionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_subscribers', models.IntegerField(default=0, verbose_name='إجمالي المشتركين')),
                ('new_subscribers_today', models.IntegerField(default=0, verbose_name='المشتركون الجدد اليوم')),
                ('notification_enabled', models.IntegerField(default=0, verbose_name='المشتركون المفعلون للإشعارات')),
                ('property_views', models.IntegerField(default=0, verbose_name='مشاهدات العقارات')),
                ('notification_clicks', models.IntegerField(default=0, verbose_name='نقرات الإشعارات')),
                ('subscribers_history', models.JSONField(default=dict, verbose_name='تاريخ المشتركين')),
                ('notification_history', models.JSONField(default=dict, verbose_name='تاريخ الإشعارات')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('broker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_stats', to='properties.broker', verbose_name='الدلال')),
            ],
            options={
                'verbose_name': 'إحصائيات اشتراكات الدلال',
                'verbose_name_plural': 'إحصائيات اشتراكات الدلالين',
            },
        ),
        migrations.CreateModel(
            name='BrokerNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('all', 'جميع الإشعارات'), ('none', 'إيقاف جميع الإشعارات'), ('new_properties', 'العقارات الجديدة فقط'), ('featured', 'العقارات المميزة فقط'), ('offers', 'العروض والتخفيضات'), ('posts', 'البث والمنشورات')], default='all', max_length=20, verbose_name='نوع الإشعارات')),
                ('in_app_notifications', models.BooleanField(default=True, verbose_name='إشعارات داخل التطبيق')),
                ('browser_notifications', models.BooleanField(default=False, verbose_name='إشعارات المتصفح')),
                ('email_notifications', models.BooleanField(default=False, verbose_name='إشعارات البريد الإلكتروني')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='properties.broker', verbose_name='الدلال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إعدادات إشعارات الدلال',
                'verbose_name_plural': 'إعدادات إشعارات الدلالين',
                'unique_together': {('user', 'broker')},
            },
        ),
        migrations.CreateModel(
            name='BrokerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاشتراك')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إلغاء الاشتراك')),
                ('notifications_sent', models.IntegerField(default=0, verbose_name='الإشعارات المرسلة')),
                ('notifications_read', models.IntegerField(default=0, verbose_name='الإشعارات المقروءة')),
                ('last_notification_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر إشعار')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='properties.broker', verbose_name='الدلال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'اشتراك دلال',
                'verbose_name_plural': 'اشتراكات الدلالين',
                'unique_together': {('user', 'broker')},
            },
        ),
    ]
