# Generated by Django 6.0.6 on 2026-06-29 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0049_brokersubscriptionstats_brokernotificationsettings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionLiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_url', models.URLField(verbose_name='رابط البث')),
                ('stream_key', models.CharField(blank=True, max_length=100, verbose_name='مفتاح البث')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('facebook', 'Facebook'), ('twitch', 'Twitch'), ('custom', 'مخصص')], default='youtube', max_length=50, verbose_name='المنصة')),
                ('is_live', models.BooleanField(default=False, verbose_name='بث مباشر')),
                ('viewer_count', models.IntegerField(default=0, verbose_name='عدد المشاهدين')),
                ('chat_enabled', models.BooleanField(default=True, verbose_name='الشات مفعّل')),
                ('recording_enabled', models.BooleanField(default=True, verbose_name='التسجيل مفعّل')),
                ('recording_url', models.URLField(blank=True, verbose_name='رابط التسجيل')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت البدء')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_stream', to='properties.auction', verbose_name='المزاد')),
            ],
            options={
                'verbose_name': 'بث مباشر للمزاد',
                'verbose_name_plural': 'البث المباشر للمزادات',
            },
        ),
        migrations.CreateModel(
            name='AuctionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_bid', 'مزايدة جديدة'), ('outbid', 'تم تجاوز مزايدتك'), ('auction_starting', 'المزاد سيبدأ قريباً'), ('auction_ending', 'المزاد ينتهي قريباً'), ('auction_won', 'فزت بالمزاد'), ('auction_lost', 'خسرت المزاد'), ('price_reached', 'وصل السعر للحد المطلوب')], max_length=20, verbose_name='نوع الإشعار')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('amount', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='المبلغ')),
                ('is_read', models.BooleanField(default=False, verbose_name='تم القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='properties.auction', verbose_name='المزاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار مزاد',
                'verbose_name_plural': 'إشعارات المزادات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.IntegerField(default=0, verbose_name='إجمالي المشاهدات')),
                ('unique_visitors', models.IntegerField(default=0, verbose_name='الزوار الفريدين')),
                ('total_bids', models.IntegerField(default=0, verbose_name='إجمالي المزايدات')),
                ('unique_bidders', models.IntegerField(default=0, verbose_name='المزايدون الفريدون')),
                ('avg_bid_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='متوسط المزايدة')),
                ('peak_bid_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت ذروة المزايدة')),
                ('total_watchers', models.IntegerField(default=0, verbose_name='إجمالي المتابعين')),
                ('watchers_joined', models.IntegerField(default=0, verbose_name='المتابعون الذين انضموا للمزايدة')),
                ('auto_bid_count', models.IntegerField(default=0, verbose_name='عدد المزايدات الآلية')),
                ('extension_count', models.IntegerField(default=0, verbose_name='عدد التمديدات')),
                ('final_price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='السعر النهائي')),
                ('price_increase_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة زيادة السعر')),
                ('bids_by_hour', models.JSONField(default=dict, verbose_name='المزايدات بالساعة')),
                ('views_by_hour', models.JSONField(default=dict, verbose_name='المشاهدات بالساعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='properties.auction', verbose_name='المزاد')),
            ],
            options={
                'verbose_name': 'إحصائيات مزاد',
                'verbose_name_plural': 'إحصائيات المزادات',
            },
        ),
        migrations.CreateModel(
            name='FavoriteArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المنطقة')),
                ('south', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='الحد الجنوبي')),
                ('north', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='الحد الشمالي')),
                ('west', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='الحد الغربي')),
                ('east', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='الحد الشرقي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_areas', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'منطقة مفضلة',
                'verbose_name_plural': 'المناطق المفضلة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='التقييم')),
                ('comment', models.TextField(blank=True, verbose_name='التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقييم')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='properties.auction', verbose_name='المزاد')),
                ('rated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_ratings_received', to=settings.AUTH_USER_MODEL, verbose_name='المقيم')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_ratings_given', to=settings.AUTH_USER_MODEL, verbose_name='المقيم')),
            ],
            options={
                'verbose_name': 'تقييم مزاد',
                'verbose_name_plural': 'تقييمات المزادات',
                'unique_together': {('auction', 'rater', 'rated_user')},
            },
        ),
        migrations.CreateModel(
            name='AutoBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='الحد الأقصى للمزايدة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('current_bid', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='المزايدة الحالية')),
                ('total_bids_placed', models.IntegerField(default=0, verbose_name='إجمالي المزايدات الموضوعة')),
                ('last_bid_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزايدة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_bids', to='properties.auction', verbose_name='المزاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_bids', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مزايدة آلية',
                'verbose_name_plural': 'المزايدات الآلية',
                'unique_together': {('auction', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PropertyComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='properties.property', verbose_name='العقار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_comparisons', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مقارنة عقار',
                'verbose_name_plural': 'مقارنات العقارات',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'property')},
            },
        ),
    ]
