# Generated by Django 6.0.6 on 2026-06-29 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0050_auctionlivestream_auctionnotification_auctionstats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='advertisement_budget',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='ميزانية الإعلان'),
        ),
        migrations.AddField(
            model_name='auction',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='properties.broker', verbose_name='الدلال'),
        ),
        migrations.AddField(
            model_name='auction',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='بريد التواصل'),
        ),
        migrations.AddField(
            model_name='auction',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم التواصل'),
        ),
        migrations.AddField(
            model_name='auction',
            name='is_advertised',
            field=models.BooleanField(default=False, verbose_name='معلن عنه'),
        ),
        migrations.AddField(
            model_name='auction',
            name='max_participants',
            field=models.IntegerField(blank=True, null=True, verbose_name='الحد الأقصى للمشاركين'),
        ),
        migrations.AddField(
            model_name='auction',
            name='winner_announced',
            field=models.BooleanField(default=False, verbose_name='تم الإعلان عن الفائز'),
        ),
        migrations.AddField(
            model_name='auctionparticipant',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='رقم مرجع الدفع'),
        ),
        migrations.AddField(
            model_name='auctionparticipant',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('paid', 'مدفوع'), ('refunded', 'مسترد'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='حالة الدفع'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ التأمين للدخول'),
        ),
        migrations.CreateModel(
            name='AuctionAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'فيسبوك'), ('instagram', 'إنستغرام'), ('twitter', 'تويتر'), ('google', 'جوجل'), ('tiktok', 'تيك توك'), ('snapchat', 'سناب شات')], max_length=20, verbose_name='المنصة')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان الإعلان')),
                ('description', models.TextField(verbose_name='وصف الإعلان')),
                ('image_url', models.URLField(blank=True, verbose_name='رابط الصورة')),
                ('budget', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='الميزانية')),
                ('spent', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='المبلغ المصروف')),
                ('impressions', models.IntegerField(default=0, verbose_name='عدد الظهور')),
                ('clicks', models.IntegerField(default=0, verbose_name='عدد النقرات')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('active', 'نشط'), ('paused', 'موقوف'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='properties.auction', verbose_name='المزاد')),
            ],
            options={
                'verbose_name': 'إعلان مزاد',
                'verbose_name_plural': 'إعلانات المزادات',
                'ordering': ['-created_at'],
            },
        ),
    ]
