# Generated by Django 6.0.6 on 2026-06-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0051_auction_advertisement_budget_auction_broker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='is_360',
            field=models.BooleanField(default=False, verbose_name='صورة 360°'),
        ),
    ]
