# Generated by Django 6.0.6 on 2026-06-29 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0052_propertyimage_is_360'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الفندق')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('star_rating', models.IntegerField(choices=[(1, 'نجمة واحدة'), (2, 'نجمتان'), (3, 'ثلاث نجوم'), (4, 'أربع نجوم'), (5, 'خمس نجوم')], verbose_name='التصنيف')),
                ('price_range', models.CharField(choices=[('economy', 'اقتصادي'), ('medium', 'متوسط'), ('luxury', 'فاخر'), ('budget', 'حسب الميزانية')], max_length=20, verbose_name='السعر')),
                ('room_types', models.JSONField(default=list, verbose_name='أنواع الغرف')),
                ('meal_plan', models.CharField(blank=True, choices=[('breakfast', 'إفطار مجاني'), ('half_board', 'نصف إقامة'), ('full_board', 'إقامة كاملة')], max_length=20, verbose_name='خطة الوجبات')),
                ('services', models.JSONField(default=list, verbose_name='الخدمات')),
                ('suitable_for', models.JSONField(default=list, verbose_name='مناسب لـ')),
                ('governorate', models.CharField(choices=[('BAG', 'بغداد'), ('BAS', 'البصرة'), ('NIN', 'نينوى'), ('ERB', 'أربيل'), ('NAJ', 'النجف'), ('KAR', 'كربلاء'), ('BAB', 'بابل'), ('DHI', 'ذي قار'), ('DIA', 'ديالى'), ('KIR', 'كركوك'), ('ANB', 'الأنبار'), ('WAS', 'واسط'), ('MUT', 'ميسان'), ('MUTH', 'المثنى'), ('QAD', 'القادسية (الديوانية)'), ('SAL', 'صلاح الدين'), ('DUH', 'دهوك'), ('SUL', 'السليمانية'), ('HAL', 'حلبجة'), ('KIRKUK', 'كركوك')], max_length=50, verbose_name='المحافظة')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('image', models.ImageField(upload_to='hotels/', verbose_name='الصورة الرئيسية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'فندق',
                'verbose_name_plural': 'الفنادق',
                'ordering': ['-is_featured', '-star_rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المنتجع')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('resort_type', models.CharField(choices=[('beach', 'منتجع شاطئي'), ('mountain', 'منتجع جبلي'), ('desert', 'منتجع صحراوي'), ('rural', 'منتجع ريفي'), ('spa', 'منتجع صحي (Spa Resort)'), ('family', 'منتجع عائلي'), ('luxury', 'منتجع فاخر'), ('eco', 'منتجع بيئي')], max_length=20, verbose_name='نوع المنتجع')),
                ('facilities', models.JSONField(default=list, verbose_name='المرافق')),
                ('accommodation_types', models.JSONField(default=list, verbose_name='أنواع الإقامة')),
                ('suitable_for', models.JSONField(default=list, verbose_name='مناسب لـ')),
                ('governorate', models.CharField(choices=[('BAG', 'بغداد'), ('BAS', 'البصرة'), ('NIN', 'نينوى'), ('ERB', 'أربيل'), ('NAJ', 'النجف'), ('KAR', 'كربلاء'), ('BAB', 'بابل'), ('DHI', 'ذي قار'), ('DIA', 'ديالى'), ('KIR', 'كركوك'), ('ANB', 'الأنبار'), ('WAS', 'واسط'), ('MUT', 'ميسان'), ('MUTH', 'المثنى'), ('QAD', 'القادسية (الديوانية)'), ('SAL', 'صلاح الدين'), ('DUH', 'دهوك'), ('SUL', 'السليمانية'), ('HAL', 'حلبجة'), ('KIRKUK', 'كركوك')], max_length=50, verbose_name='المحافظة')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول')),
                ('price_range', models.CharField(choices=[('economy', 'اقتصادي'), ('medium', 'متوسط'), ('luxury', 'فاخر'), ('budget', 'حسب الميزانية')], max_length=20, verbose_name='السعر')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('image', models.ImageField(upload_to='resorts/', verbose_name='الصورة الرئيسية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'منتجع',
                'verbose_name_plural': 'المنتجعات',
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/gallery/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='التعليق')),
                ('is_primary', models.BooleanField(default=False, verbose_name='رئيسية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.hotel', verbose_name='الفندق')),
            ],
            options={
                'verbose_name': 'صورة فندق',
                'verbose_name_plural': 'صور الفنادق',
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResortImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='resorts/gallery/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='التعليق')),
                ('is_primary', models.BooleanField(default=False, verbose_name='رئيسية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.resort', verbose_name='المنتجع')),
            ],
            options={
                'verbose_name': 'صورة منتجع',
                'verbose_name_plural': 'صور المنتجعات',
                'ordering': ['-is_primary', 'id'],
            },
        ),
    ]
