# Generated by Django 6.0.6 on 2026-06-29 22:46

import django.db.models.deletion
import properties.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0053_hotel_resort_hotelimage_resortimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='معرف المحادثة')),
                ('conversation_type', models.CharField(choices=[('direct', 'محادثة مباشرة'), ('group', 'مجموعة'), ('support', 'دعم فني')], default='direct', max_length=20, verbose_name='نوع المحادثة')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='اسم المحادثة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('group_avatar', models.ImageField(blank=True, null=True, upload_to=properties.models.chat_image_path, verbose_name='صورة المجموعة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_archived', models.BooleanField(default=False, verbose_name='مؤرشف')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر رسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'محادثة',
                'verbose_name_plural': 'المحادثات',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_notifications', models.BooleanField(default=True, verbose_name='تفعيل الإشعارات')),
                ('enable_sound', models.BooleanField(default=True, verbose_name='تفعيل الصوت')),
                ('enable_typing_indicator', models.BooleanField(default=True, verbose_name='تفعيل مؤشر الكتابة')),
                ('enable_read_receipts', models.BooleanField(default=True, verbose_name='تفعيل إيصالات القراءة')),
                ('enable_online_status', models.BooleanField(default=True, verbose_name='تفعيل حالة الاتصال')),
                ('auto_archive_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='أرشفة تلقائية (أيام)')),
                ('message_retention_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='احتفاظ بالرسائل (أيام)')),
                ('theme', models.CharField(default='light', max_length=20, verbose_name='المظهر')),
                ('font_size', models.CharField(default='medium', max_length=10, verbose_name='حجم الخط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('blocked_users', models.ManyToManyField(blank=True, related_name='chat_blocked_by_settings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدمون المحجوبون')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('muted_conversations', models.ManyToManyField(blank=True, related_name='muted_by', to='properties.conversation', verbose_name='المحادثات المكتومة')),
            ],
            options={
                'verbose_name': 'إعدادات المحادثة',
                'verbose_name_plural': 'إعدادات المحادثات',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='معرف الرسالة')),
                ('message_type', models.CharField(choices=[('text', 'نص'), ('image', 'صورة'), ('video', 'فيديو'), ('audio', 'صوت'), ('file', 'ملف'), ('location', 'موقع'), ('property', 'عقار'), ('system', 'نظام')], default='text', max_length=20, verbose_name='نوع الرسالة')),
                ('content', models.TextField(blank=True, verbose_name='المحتوى')),
                ('is_edited', models.BooleanField(default=False, verbose_name='معدلة')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوفة')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='مثبتة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='properties.chatmessage', verbose_name='رد على')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='properties.conversation', verbose_name='المحادثة')),
            ],
            options={
                'verbose_name': 'رسالة محادثة',
                'verbose_name_plural': 'رسائل المحادثات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'مسؤول'), ('moderator', 'مشرف'), ('member', 'عضو')], default='member', max_length=20, verbose_name='الدور')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='الاسم المستعار')),
                ('is_muted', models.BooleanField(default=False, verbose_name='مكتوم')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='مثبت')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر قراءة')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_info', to='properties.conversation', verbose_name='المحادثة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_participations', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مشارك في المحادثة',
                'verbose_name_plural': 'المشاركون في المحادثات',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', through='properties.ConversationParticipant', to=settings.AUTH_USER_MODEL, verbose_name='المشاركون'),
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('image', 'صورة'), ('video', 'فيديو'), ('audio', 'صوت'), ('file', 'ملف')], max_length=20, verbose_name='نوع المرفق')),
                ('file', models.FileField(upload_to=properties.models.chat_attachment_path, verbose_name='الملف')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=properties.models.chat_image_path, verbose_name='الصورة المصغرة')),
                ('file_name', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('file_size', models.PositiveIntegerField(verbose_name='حجم الملف (بايت)')),
                ('mime_type', models.CharField(max_length=100, verbose_name='نوع MIME')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='العرض')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='الارتفاع')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='المدة (ثواني)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='properties.chatmessage', verbose_name='الرسالة')),
            ],
            options={
                'verbose_name': 'مرفق الرسالة',
                'verbose_name_plural': 'مرفقات الرسائل',
            },
        ),
        migrations.CreateModel(
            name='MessageReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت القراءة')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='properties.chatmessage', verbose_name='الرسالة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_read_statuses', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'حالة قراءة الرسالة',
                'verbose_name_plural': 'حالات قراءة الرسائل',
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='read_by',
            field=models.ManyToManyField(related_name='read_messages', through='properties.MessageReadStatus', to=settings.AUTH_USER_MODEL, verbose_name='مقروءة من قبل'),
        ),
        migrations.CreateModel(
            name='MessageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('spam', 'رسائل مزعجة'), ('harassment', 'مضايقة'), ('inappropriate', 'محتوى غير لائق'), ('scam', 'احتيال'), ('other', 'أخرى')], max_length=20, verbose_name='نوع البلاغ')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('reviewed', 'تمت المراجعة'), ('resolved', 'تم الحل'), ('dismissed', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات المسؤول')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البلاغ')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='properties.chatmessage', verbose_name='الرسالة')),
                ('reported_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_against', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المبلغ ضده')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_reports', to=settings.AUTH_USER_MODEL, verbose_name='المبلغ')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='راجع بواسطة')),
            ],
            options={
                'verbose_name': 'بلاغ عن رسالة',
                'verbose_name_plural': 'البلاغات عن الرسائل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['conversation', 'user'], name='properties__convers_68ee38_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['user', '-last_read_at'], name='properties__user_id_f5eb19_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['is_pinned', '-last_read_at'], name='properties__is_pinn_febf9a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationparticipant',
            unique_together={('conversation', 'user')},
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['conversation_id'], name='properties__convers_703b11_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-last_message_at'], name='properties__last_me_606498_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_active', '-last_message_at'], name='properties__is_acti_67ac69_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['message', 'attachment_type'], name='properties__message_6a51e5_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereadstatus',
            index=models.Index(fields=['message', 'user'], name='properties__message_c00ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereadstatus',
            index=models.Index(fields=['user', '-read_at'], name='properties__user_id_63b9b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereadstatus',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['message_id'], name='properties__message_b7c92a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', '-created_at'], name='properties__convers_fbbc80_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', '-created_at'], name='properties__sender__12c52f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['is_deleted', '-created_at'], name='properties__is_dele_c9efe7_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['is_pinned', '-created_at'], name='properties__is_pinn_afe90f_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereport',
            index=models.Index(fields=['status', '-created_at'], name='properties__status_25e8ad_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereport',
            index=models.Index(fields=['reporter', '-created_at'], name='properties__reporte_8ea57c_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereport',
            index=models.Index(fields=['reported_user', '-created_at'], name='properties__reporte_0fc3a9_idx'),
        ),
    ]
