# Generated by Django 6.0.6 on 2026-06-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0055_create_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_per_property',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='السعر الافتراضي: 50 دينار لكل عقار في اليوم', max_digits=10, verbose_name='سعر العقار اليومي (د.ع)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر الكلي'),
        ),
    ]
