# Generated by Django 6.0.6 on 2026-06-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0057_subscriptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='وصف العقار (English)'),
        ),
        migrations.AddField(
            model_name='property',
            name='description_ku',
            field=models.TextField(blank=True, default='', verbose_name='وصف العقار (كردی)'),
        ),
        migrations.AddField(
            model_name='property',
            name='description_tr',
            field=models.TextField(blank=True, default='', verbose_name='وصف العقار (Türkmençe)'),
        ),
        migrations.AddField(
            model_name='property',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='عنوان الإعلان (English)'),
        ),
        migrations.AddField(
            model_name='property',
            name='title_ku',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='عنوان الإعلان (كردی)'),
        ),
        migrations.AddField(
            model_name='property',
            name='title_tr',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='عنوان الإعلان (Türkmençe)'),
        ),
    ]
