# Generated by Django 6.0.6 on 2026-07-01 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0058_property_description_en_property_description_ku_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerSystemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_brokers', models.IntegerField(default=0, verbose_name='إجمالي الدلالين')),
                ('active_brokers', models.IntegerField(default=0, verbose_name='الدلالين النشطين')),
                ('suspended_brokers', models.IntegerField(default=0, verbose_name='الدلالين الموقوفين')),
                ('new_brokers_today', models.IntegerField(default=0, verbose_name='الدلالين الجدد اليوم')),
                ('new_brokers_this_month', models.IntegerField(default=0, verbose_name='الدلالين الجدد هذا الشهر')),
                ('main_brokers', models.IntegerField(default=0, verbose_name='الدلالين الرئيسيين')),
                ('sub_brokers', models.IntegerField(default=0, verbose_name='الدلالين الفرعيين')),
                ('total_properties_posted', models.IntegerField(default=0, verbose_name='إجمالي العقارات المنشورة')),
                ('total_messages_sent', models.IntegerField(default=0, verbose_name='إجمالي الرسائل المرسلة')),
                ('daily_history', models.JSONField(default=dict, verbose_name='تاريخ يومي')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إحصائيات نظام الدلالين',
                'verbose_name_plural': 'إحصائيات نظام الدلالين',
            },
        ),
        migrations.RemoveField(
            model_name='property',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='property',
            name='description_ku',
        ),
        migrations.RemoveField(
            model_name='property',
            name='description_tr',
        ),
        migrations.RemoveField(
            model_name='property',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='property',
            name='title_ku',
        ),
        migrations.RemoveField(
            model_name='property',
            name='title_tr',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='meal_plan',
            field=models.CharField(blank=True, choices=[('no_meals', 'بدون وجبات'), ('breakfast', 'إفطار مجاني'), ('half_board', 'نصف إقامة'), ('full_board', 'إقامة كاملة'), ('all_inclusive', 'شامل كلياً')], max_length=20, verbose_name='خطة الوجبات'),
        ),
        migrations.CreateModel(
            name='BrokerIndividualStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('properties_added', models.IntegerField(default=0, verbose_name='العقارات المضافة')),
                ('properties_deleted', models.IntegerField(default=0, verbose_name='العقارات المحذوفة')),
                ('properties_active', models.IntegerField(default=0, verbose_name='العقارات النشطة')),
                ('total_views', models.IntegerField(default=0, verbose_name='إجمالي المشاهدات')),
                ('views_today', models.IntegerField(default=0, verbose_name='المشاهدات اليوم')),
                ('views_this_month', models.IntegerField(default=0, verbose_name='المشاهدات هذا الشهر')),
                ('average_response_time', models.FloatField(default=0, verbose_name='متوسط وقت الاستجابة (دقيقة)')),
                ('fastest_response_time', models.FloatField(default=0, verbose_name='أسرع وقت استجابة (دقيقة)')),
                ('slowest_response_time', models.FloatField(default=0, verbose_name='أبطأ وقت استجابة (دقيقة)')),
                ('performance_score', models.FloatField(default=0, verbose_name='درجة الأداء')),
                ('rating', models.FloatField(default=0, verbose_name='التقييم')),
                ('total_ratings', models.IntegerField(default=0, verbose_name='إجمالي التقييمات')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='آخر تسجيل دخول')),
                ('last_property_added', models.DateTimeField(blank=True, null=True, verbose_name='آخر عقار مضاف')),
                ('last_message_sent', models.DateTimeField(blank=True, null=True, verbose_name='آخر رسالة مرسلة')),
                ('daily_stats', models.JSONField(default=dict, verbose_name='إحصائيات يومية')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('broker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual_stats', to='properties.broker', verbose_name='الدلال')),
            ],
            options={
                'verbose_name': 'إحصائيات الدلال',
                'verbose_name_plural': 'إحصائيات الدلالين',
            },
        ),
        migrations.CreateModel(
            name='BulkMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('all_users', 'جميع المستخدمين'), ('all_brokers', 'جميع الدلالين'), ('active_users', 'المستخدمين النشطين'), ('active_brokers', 'الدلالين النشطين'), ('specific_users', 'مستخدمين محددين'), ('specific_brokers', 'دلالين محددين')], default='all_users', max_length=20, verbose_name='نوع المستهدفين')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'قيد الإرسال'), ('sent', 'تم الإرسال'), ('failed', 'فشل الإرسال')], default='draft', max_length=20, verbose_name='الحالة')),
                ('total_recipients', models.IntegerField(default=0, verbose_name='إجمالي المستلمين')),
                ('sent_count', models.IntegerField(default=0, verbose_name='عدد الرسائل المرسلة')),
                ('failed_count', models.IntegerField(default=0, verbose_name='عدد الرسائل الفاشلة')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='موعد الإرسال المجدول')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_bulk_messages', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'رسالة جماعية',
                'verbose_name_plural': 'الرسائل الجماعية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_message_notifications', models.BooleanField(default=True, verbose_name='إشعارات الرسائل الجديدة')),
                ('mention_notifications', models.BooleanField(default=True, verbose_name='إشعارات الذكر')),
                ('reaction_notifications', models.BooleanField(default=False, verbose_name='إشعارات الردود الفعل')),
                ('reply_notifications', models.BooleanField(default=True, verbose_name='إشعارات الردود')),
                ('group_mention_notifications', models.BooleanField(default=True, verbose_name='إشعارات الذكر في المجموعات')),
                ('in_app_notifications', models.BooleanField(default=True, verbose_name='إشعارات داخل التطبيق')),
                ('browser_notifications', models.BooleanField(default=False, verbose_name='إشعارات المتصفح')),
                ('email_notifications', models.BooleanField(default=False, verbose_name='إشعارات البريد الإلكتروني')),
                ('sound_enabled', models.BooleanField(default=True, verbose_name='صوت الإشعارات')),
                ('quiet_hours_enabled', models.BooleanField(default=False, verbose_name='تفعيل الساعات الهادئة')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='بداية الساعات الهادئة')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='نهاية الساعات الهادئة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إعدادات إشعارات الرسائل',
                'verbose_name_plural': 'إعدادات إشعارات الرسائل',
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', '👍'), ('love', '❤️'), ('laugh', '😂'), ('sad', '😢'), ('angry', '😠'), ('thumbs_up', '👍'), ('thumbs_down', '👎'), ('clap', '👏')], max_length=20, verbose_name='نوع الرد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='properties.chatmessage', verbose_name='الرسالة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رد فعل',
                'verbose_name_plural': 'ردود الفعل',
                'indexes': [models.Index(fields=['message', 'reaction_type'], name='properties__message_534942_idx')],
                'unique_together': {('message', 'user', 'reaction_type')},
            },
        ),
        migrations.CreateModel(
            name='MutedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الكتم')),
                ('muted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_by', to=settings.AUTH_USER_MODEL, verbose_name='المكتوم')),
                ('muter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_users', to=settings.AUTH_USER_MODEL, verbose_name='الكاتم')),
            ],
            options={
                'verbose_name': 'مستخدم مكتوم',
                'verbose_name_plural': 'المستخدمون المكتومون',
                'indexes': [models.Index(fields=['muter', 'muted'], name='properties__muter_i_aec2e2_idx')],
                'unique_together': {('muter', 'muted')},
            },
        ),
    ]
