# Generated by Django 6.0.6 on 2026-07-04 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0060_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القناة')),
                ('description', models.TextField(blank=True, verbose_name='وصف القناة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='channels/logos/', verbose_name='شعار القناة')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='channels/covers/', verbose_name='صورة الغلاف')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('suspended', 'موقوف'), ('pending', 'بانتظار الموافقة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('is_verified', models.BooleanField(default=False, verbose_name='موثق')),
                ('followers_count', models.PositiveIntegerField(default=0, verbose_name='عدد المتابعين')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('broker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='properties.broker', verbose_name='الدلال')),
            ],
            options={
                'verbose_name': 'قناة دلال',
                'verbose_name_plural': 'قنوات الدلالين',
                'ordering': ['-created_at'],
            },
        ),
    ]
