# Generated by Django 6.0.6 on 2026-07-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0061_brokerchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='allow_admins_during_maintenance',
            field=models.BooleanField(default=True, verbose_name='السماح للمشرفين أثناء الصيانة'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت انتهاء الصيانة'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_message',
            field=models.TextField(default='الموقع تحت الصيانة، سنعود قريبًا. نعمل حاليًا على تحسين خدماتنا لتقديم تجربة أفضل.', verbose_name='رسالة الصيانة'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, verbose_name='وضع الصيانة'),
        ),
    ]
