# Generated by Django 6.0.6 on 2026-07-05 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0062_sitesettings_allow_admins_during_maintenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='properties.hotel', verbose_name='الفندق'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='properties.property', verbose_name='العقار'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='resort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='properties.resort', verbose_name='المنتجع'),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='folder',
            field=models.CharField(blank=True, choices=[('', 'الرئيسي'), ('inbox', 'الوارد'), ('sent', 'الصادر'), ('important', 'مهم'), ('spam', 'غير مرغوب')], max_length=20, verbose_name='المجلد'),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='مؤرشف'),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='is_starred',
            field=models.BooleanField(default=False, verbose_name='مميز'),
        ),
    ]
