# Generated by Django 6.0.6 on 2026-07-05 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0063_chatmessage_hotel_chatmessage_property_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'منطقة',
                'verbose_name_plural': 'المناطق',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('governorate_state', models.CharField(blank=True, max_length=100, verbose_name='المحافظة/الولاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مدينة',
                'verbose_name_plural': 'المدن',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('flag_emoji', models.CharField(max_length=10, verbose_name='علم الدولة')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='كود الدولة')),
                ('currency_code', models.CharField(max_length=3, verbose_name='كود العملة')),
                ('currency_name_ar', models.CharField(max_length=50, verbose_name='اسم العملة بالعربية')),
                ('currency_name_en', models.CharField(max_length=50, verbose_name='اسم العملة بالإنجليزية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'دولة',
                'verbose_name_plural': 'الدول',
                'ordering': ['order', 'name_ar'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='currency',
            field=models.CharField(blank=True, default='IQD', max_length=3, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='property',
            name='original_price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='السعر الأصلي بالعملة الأجنبية'),
        ),
        migrations.AddField(
            model_name='property',
            name='area_outside',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.area', verbose_name='المنطقة'),
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='properties.city', verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.city', verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='properties.country', verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.country', verbose_name='الدولة'),
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('city', 'name_ar')},
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('country', 'name_ar')},
        ),
    ]
