# Generated by Django 6.0.6 on 2026-07-05 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0064_area_city_country_property_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brokerchannel',
            options={'ordering': ['-is_verified', '-followers_count', '-created_at'], 'verbose_name': 'قناة دلال', 'verbose_name_plural': 'قنوات الدلالين'},
        ),
        migrations.RemoveField(
            model_name='brokerchannel',
            name='status',
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشطة'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='مؤرشفة'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=220, null=True, unique=True, verbose_name='الرابط'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='website',
            field=models.URLField(blank=True, verbose_name='الموقع الإلكتروني'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='واتساب'),
        ),
        migrations.AlterField(
            model_name='brokerchannel',
            name='description',
            field=models.TextField(blank=True, verbose_name='نبذة تعريفية'),
        ),
        migrations.AlterField(
            model_name='brokerchannel',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='موثقة'),
        ),
        migrations.CreateModel(
            name='ChannelFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المتابعة')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='properties.brokerchannel', verbose_name='القناة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_follows', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'متابعة قناة',
                'verbose_name_plural': 'متابعات القنوات',
                'ordering': ['-followed_at'],
                'unique_together': {('user', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='ChannelSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحفظ')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='properties.brokerchannel', verbose_name='القناة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_channels', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'قناة محفوظة',
                'verbose_name_plural': 'القنوات المحفوظة',
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'channel')},
            },
        ),
    ]
