# Generated by Django 6.0.6 on 2026-07-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0065_alter_brokerchannel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_advertised',
            field=models.BooleanField(default=False, verbose_name='معلن عنه'),
        ),
        migrations.AddField(
            model_name='auction',
            name='advertisement_budget',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='ميزانية الإعلان'),
        ),
    ]
