# Generated by Django 6.0.6 on 2026-07-05 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0067_auction_approval_status_auction_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('identity_verified', models.BooleanField(default=False, verbose_name='تم توثيق الهوية')),
                ('deposit_paid', models.BooleanField(default=False, verbose_name='تم دفع التأمين')),
                ('deposit_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ التأمين المدفوع')),
                ('payment_status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('paid', 'مدفوع'), ('refunded', 'مسترد'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='حالة الدفع')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='رقم مرجع الدفع')),
                ('approval_status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الموافقة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='properties.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_participations', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_participants', to=settings.AUTH_USER_MODEL, verbose_name='تمت الموافقة بواسطة')),
            ],
            options={
                'verbose_name': 'مشارك في المزاد',
                'verbose_name_plural': 'المشاركون في المزادات',
                'unique_together': {('auction', 'user')},
            },
        ),
    ]
