# Generated by Django 6.0.6 on 2026-07-05 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0068_auctionparticipant_approval_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='broker',
        ),
        migrations.RemoveField(
            model_name='message',
            name='email',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='message',
            name='property',
        ),
        migrations.RemoveField(
            model_name='message',
            name='replied_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='replied_by',
        ),
        migrations.RemoveField(
            model_name='message',
            name='reply',
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, verbose_name='المحتوى'),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='properties.conversation', verbose_name='المحادثة'),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AddField(
            model_name='message',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='message',
            name='link_description',
            field=models.TextField(blank=True, verbose_name='وصف الرابط'),
        ),
        migrations.AddField(
            model_name='message',
            name='link_image',
            field=models.URLField(blank=True, verbose_name='صورة الرابط'),
        ),
        migrations.AddField(
            model_name='message',
            name='link_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='عنوان الرابط'),
        ),
        migrations.AddField(
            model_name='message',
            name='link_url',
            field=models.URLField(blank=True, verbose_name='رابط'),
        ),
        migrations.AddField(
            model_name='message',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='اسم الموقع'),
        ),
        migrations.AddField(
            model_name='message',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت القراءة'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='properties.message', verbose_name='رد على'),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('sent', 'مرسلة'), ('delivered', 'مستلمة'), ('read', 'مقروءة'), ('failed', 'فشلت')], default='sent', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'نص'), ('image', 'صورة'), ('video', 'فيديو'), ('audio', 'صوت'), ('file', 'ملف'), ('location', 'موقع'), ('link', 'رابط'), ('property_card', 'بطاقة عقار'), ('system', 'نظام')], default='text', max_length=20, verbose_name='نوع الرسالة'),
        ),
    ]
