# Generated by Django 6.0.6 on 2026-07-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0069_remove_message_broker_remove_message_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagereport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
    ]
