# Generated by Django 6.0.6 on 2026-07-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0070_add_updated_at_to_messagereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagereport',
            name='resolution_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات الحل'),
        ),
    ]
