# Generated by Django 6.0.6 on 2026-07-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0071_add_resolution_notes_to_messagereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerchannel',
            name='status',
            field=models.CharField(
                choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('suspended', 'موقوف'), ('pending', 'بانتظار الموافقة')],
                default='pending',
                max_length=20,
                verbose_name='الحالة'
            ),
        ),
    ]
