# Generated by Django 6.0.6 on 2026-07-06 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0072_add_status_to_brokerchannel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokerchannel',
            name='city',
        ),
    ]
