# Generated by Django 6.0.6 on 2026-07-06 09:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0073_remove_city_from_brokerchannel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'نص'), ('image', 'صورة'), ('file', 'ملف'), ('payment_proof', 'إيصال دفع')], default='text', max_length=20, verbose_name='نوع الرسالة')),
                ('content', models.TextField(blank=True, verbose_name='المحتوى')),
                ('file', models.FileField(blank=True, null=True, upload_to='admin_chats/', verbose_name='الملف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='admin_chats/images/', verbose_name='الصورة')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'محادثة إدارة',
                'verbose_name_plural': 'محادثات الإدارة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('paypal', 'PayPal'), ('zain_cash', 'Zain Cash'), ('qi_card', 'Qi Card'), ('asia_hawala', 'Asia Hawala'), ('bank_transfer', 'التحويل البنكي'), ('cash', 'نقداً')], max_length=50, unique=True, verbose_name='طريقة الدفع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='أيقونة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'طريقة دفع',
                'verbose_name_plural': 'طرق الدفع',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('property_added', 'إضافة عقار'), ('payment_success', 'نجاح الدفع'), ('property_approved', 'قبول العقار'), ('property_rejected', 'رفض العقار'), ('publication_expiring', 'قرب انتهاء النشر'), ('publication_expired', 'انتهاء النشر'), ('publication_renewed', 'تجديد النشر')], max_length=50, verbose_name='نوع الإشعار')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'إشعار عقار',
                'verbose_name_plural': 'إشعارات العقارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_type', models.CharField(choices=[('normal', 'نشر عادي'), ('featured', 'نشر مميز')], default='normal', max_length=20, verbose_name='نوع النشر')),
                ('days', models.PositiveIntegerField(verbose_name='عدد الأيام')),
                ('daily_price', models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='سعر اليوم (د.ع)')),
                ('featured_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='سعر المميز (د.ع)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ الإجمالي (د.ع)')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('refunded', 'مسترد')], default='pending', max_length=20, verbose_name='الحالة')),
                ('transaction_id', models.CharField(blank=True, max_length=200, verbose_name='رقم العملية')),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='إيصال الدفع')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('publication_start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ بدء النشر')),
                ('publication_end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء النشر')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دفع نشر عقار',
                'verbose_name_plural': 'مدفوعات نشر العقارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='brokerchannel',
            options={'ordering': ['-created_at'], 'verbose_name': 'قناة دلال', 'verbose_name_plural': 'قنوات الدلالين'},
        ),
        migrations.AlterModelOptions(
            name='messageattachment',
            options={'ordering': ['-created_at'], 'verbose_name': 'مرفق رسالة', 'verbose_name_plural': 'مرفقات الرسائل'},
        ),
        migrations.AlterModelOptions(
            name='messagereaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'رد فعل', 'verbose_name_plural': 'ردود الفعل'},
        ),
        migrations.AlterModelOptions(
            name='messagereport',
            options={'ordering': ['-created_at'], 'verbose_name': 'بلاغ رسالة', 'verbose_name_plural': 'بلاغات الرسائل'},
        ),
        migrations.RemoveIndex(
            model_name='messageattachment',
            name='properties__message_6a51e5_idx',
        ),
        migrations.RemoveIndex(
            model_name='messagereaction',
            name='properties__message_534942_idx',
        ),
        migrations.RemoveIndex(
            model_name='messagereport',
            name='properties__status_25e8ad_idx',
        ),
        migrations.RemoveIndex(
            model_name='messagereport',
            name='properties__reporte_8ea57c_idx',
        ),
        migrations.RemoveIndex(
            model_name='messagereport',
            name='properties__reporte_0fc3a9_idx',
        ),
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='broker',
            name='custom_ads_limit',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='max_properties',
        ),
        migrations.RemoveField(
            model_name='brokerchannel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='brokerchannel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='brokerchannel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='brokerchannel',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='brokerchannel',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='brokerchannel',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='brokerchannel',
            name='website',
        ),
        migrations.RemoveField(
            model_name='subscriptionrequest',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='subscriptionrequest',
            name='current_plan',
        ),
        migrations.RemoveField(
            model_name='subscriptionrequest',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='subscriptionrequest',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionrequest',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='subscriptionrequest',
            name='request_type',
        ),
        migrations.RemoveField(
            model_name='subscriptionrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='فيسبوك'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='انستغرام'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='properties_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد العقارات'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='التقييم'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد التقييمات'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, verbose_name='تيليجرام'),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الرفع'),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='نوع الملف'),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='page_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الصفحات'),
        ),
        migrations.AddField(
            model_name='property',
            name='publication_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مدة النشر (أيام)'),
        ),
        migrations.AddField(
            model_name='property',
            name='publication_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء النشر'),
        ),
        migrations.AddField(
            model_name='property',
            name='publication_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ بدء النشر'),
        ),
        migrations.AddField(
            model_name='property',
            name='publication_type',
            field=models.CharField(choices=[('normal', 'عادي'), ('featured', 'مميز')], default='normal', max_length=20, verbose_name='نوع النشر'),
        ),
        migrations.AddField(
            model_name='property',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='سبب الرفض'),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='admin_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر المقترح'),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='admin_response',
            field=models.TextField(blank=True, verbose_name='رد الإدارة'),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة'),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_subscription_requests', to=settings.AUTH_USER_MODEL, verbose_name='وافق عليه'),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='properties.broker', verbose_name='الدلال'),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='custom_duration',
            field=models.CharField(blank=True, max_length=50, verbose_name='المدة المطلوبة'),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='custom_plan_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم الخطة المخصصة'),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر المطلوب'),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='custom_properties_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد العقارات المطلوب'),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='message',
            field=models.TextField(blank=True, verbose_name='الرسالة'),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='payment_details',
            field=models.TextField(blank=True, verbose_name='بيانات الدفع'),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='سبب الرفض'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, help_text='يتم تفعيل الاشتراك فقط بعد المحادثة مع الإدارة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brokers', to='properties.subscriptionplan', verbose_name='خطة الاشتراك'),
        ),
        migrations.AlterField(
            model_name='brokerchannel',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف القناة'),
        ),
        migrations.AlterField(
            model_name='brokerchannel',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='موثق'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'نص'), ('image', 'صورة'), ('video', 'فيديو'), ('audio', 'صوت'), ('file', 'ملف'), ('location', 'موقع'), ('link', 'رابط'), ('property_card', 'بطاقة عقار'), ('broker_message', 'رسالة دلال'), ('system', 'نظام')], default='text', max_length=20, verbose_name='نوع الرسالة'),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='attachment_type',
            field=models.CharField(choices=[('image', 'صورة'), ('video', 'فيديو'), ('audio', 'صوت'), ('file', 'ملف'), ('document', 'مستند')], max_length=20, verbose_name='نوع المرفق'),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(upload_to='message_attachments/%Y/%m/%d/', verbose_name='الملف'),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='file_size',
            field=models.BigIntegerField(verbose_name='حجم الملف (بايت)'),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='properties.message', verbose_name='الرسالة'),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='message_attachments/thumbnails/%Y/%m/%d/', verbose_name='الصورة المصغرة'),
        ),
        migrations.AlterField(
            model_name='messagereaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرد'),
        ),
        migrations.AlterField(
            model_name='messagereaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='properties.message', verbose_name='الرسالة'),
        ),
        migrations.AlterField(
            model_name='messagereaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'إعجاب'), ('love', 'حب'), ('haha', 'ضحك'), ('wow', 'دهشة'), ('sad', 'حزن'), ('angry', 'غضب'), ('thumbs_up', 'إبهام للأعلى'), ('thumbs_down', 'إبهام للأسفل')], max_length=20, verbose_name='نوع الرد'),
        ),
        migrations.AlterField(
            model_name='messagereport',
            name='description',
            field=models.TextField(verbose_name='وصف البلاغ'),
        ),
        migrations.AlterField(
            model_name='messagereport',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='properties.message', verbose_name='الرسالة'),
        ),
        migrations.AlterField(
            model_name='messagereport',
            name='report_type',
            field=models.CharField(choices=[('spam', 'رسائل مزعجة'), ('inappropriate', 'محتوى غير لائق'), ('harassment', 'مضايقة'), ('scam', 'احتيال'), ('other', 'أخرى')], max_length=20, verbose_name='نوع البلاغ'),
        ),
        migrations.AlterField(
            model_name='messagereport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reports', to=settings.AUTH_USER_MODEL, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='messagereport',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('reviewed', 'تمت المراجعة'), ('resolved', 'تم الحل'), ('dismissed', 'تم الرفض')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('paid', 'تم الدفع'), ('pending_approval', 'بانتظار الموافقة'), ('published', 'منشور'), ('rejected', 'مرفوض'), ('expired', 'منتهي'), ('renewed', 'مجدد')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('negotiating', 'قيد التفاوض')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together={('message', 'user')},
        ),
        migrations.AddField(
            model_name='adminchat',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_chats', to='properties.broker', verbose_name='الدلال'),
        ),
        migrations.AddField(
            model_name='adminchat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_admin_chats', to=settings.AUTH_USER_MODEL, verbose_name='المرسل'),
        ),
        migrations.AddField(
            model_name='adminchat',
            name='subscription_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='properties.subscriptionrequest', verbose_name='طلب الاشتراك'),
        ),
        migrations.AddField(
            model_name='propertynotification',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='properties.property', verbose_name='العقار'),
        ),
        migrations.AddField(
            model_name='propertynotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='propertypayment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL, verbose_name='وافق عليه'),
        ),
        migrations.AddField(
            model_name='propertypayment',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_payments', to='properties.broker', verbose_name='الدلال'),
        ),
        migrations.AddField(
            model_name='propertypayment',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.paymentmethod', verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='propertypayment',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='properties.property', verbose_name='العقار'),
        ),
        migrations.RemoveField(
            model_name='messageattachment',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='messageattachment',
            name='height',
        ),
        migrations.RemoveField(
            model_name='messageattachment',
            name='mime_type',
        ),
        migrations.RemoveField(
            model_name='messageattachment',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='messageattachment',
            name='width',
        ),
        migrations.RemoveField(
            model_name='messagereport',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='messagereport',
            name='reported_user',
        ),
    ]
