# Generated by Django 6.0.6 on 2026-07-06 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0075_alter_messagereport_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_views', models.JSONField(blank=True, default=dict, verbose_name='المشاهدات اليومية')),
                ('weekly_views', models.JSONField(blank=True, default=dict, verbose_name='المشاهدات الأسبوعية')),
                ('monthly_views', models.JSONField(blank=True, default=dict, verbose_name='المشاهدات الشهرية')),
                ('daily_followers', models.JSONField(blank=True, default=dict, verbose_name='المتابعين اليوميين')),
                ('weekly_followers', models.JSONField(blank=True, default=dict, verbose_name='المتابعين الأسبوعيين')),
                ('monthly_followers', models.JSONField(blank=True, default=dict, verbose_name='المتابعين الشهريين')),
                ('total_shares', models.PositiveIntegerField(default=0, verbose_name='إجمالي المشاركات')),
                ('total_saves', models.PositiveIntegerField(default=0, verbose_name='إجمالي الحفظ')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='إجمالي المراجعات')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='متوسط التقييم')),
                ('response_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='نسبة الرد')),
                ('average_response_time', models.PositiveIntegerField(default=0, verbose_name='متوسط وقت الرد (دقيقة)')),
                ('properties_viewed', models.PositiveIntegerField(default=0, verbose_name='عقارات تمت مشاهدتها')),
                ('properties_contacted', models.PositiveIntegerField(default=0, verbose_name='عقارات تم التواصل بشأنها')),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='نسبة التحويل')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='properties.brokerchannel', verbose_name='القناة')),
            ],
            options={
                'verbose_name': 'إحصائيات قناة',
                'verbose_name_plural': 'إحصائيات القنوات',
            },
        ),
        migrations.CreateModel(
            name='ChannelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المراجعة')),
                ('content', models.TextField(verbose_name='محتوى المراجعة')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='صور المراجعة')),
                ('would_recommend', models.BooleanField(default=True, verbose_name='يوصي بالقناة')),
                ('overall_rating', models.PositiveSmallIntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], verbose_name='التقييم العام')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='عدد الإعجابات')),
                ('reply_count', models.PositiveIntegerField(default=0, verbose_name='عدد الردود')),
                ('is_approved', models.BooleanField(default=False, verbose_name='موافق عليه')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مراجعة مميزة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.brokerchannel', verbose_name='القناة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_reviews', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مراجعة قناة',
                'verbose_name_plural': 'مراجعات القنوات',
                'ordering': ['-is_featured', '-helpful_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوى الرد')),
                ('is_channel_owner', models.BooleanField(default=False, verbose_name='رد من صاحب القناة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='properties.channelreview', verbose_name='المراجعة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_replies', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رد مراجعة',
                'verbose_name_plural': 'ردود المراجعات',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('whatsapp', 'واتساب'), ('facebook', 'فيسبوك'), ('twitter', 'تويتر'), ('telegram', 'تيليجرام'), ('email', 'بريد إلكتروني'), ('link', 'نسخ الرابط')], max_length=20, verbose_name='منصة المشاركة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المشاركة')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='properties.brokerchannel', verbose_name='القناة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_shares', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مشاركة قناة',
                'verbose_name_plural': 'مشاركات القنوات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('followers', 'عدد المتابعين'), ('views', 'عدد المشاهدات'), ('properties', 'عدد العقارات'), ('reviews', 'عدد المراجعات'), ('rating', 'التقييم'), ('years', 'سنوات النشاط')], max_length=20, verbose_name='نوع الإنجاز')),
                ('target_value', models.PositiveIntegerField(verbose_name='القيمة المستهدفة')),
                ('current_value', models.PositiveIntegerField(default=0, verbose_name='القيمة الحالية')),
                ('is_achieved', models.BooleanField(default=False, verbose_name='تم تحقيقه')),
                ('achieved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإنجاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='properties.brokerchannel', verbose_name='القناة')),
            ],
            options={
                'verbose_name': 'إنجاز قناة',
                'verbose_name_plural': 'إنجازات القنوات',
                'ordering': ['-achieved_at', '-created_at'],
                'unique_together': {('channel', 'milestone_type', 'target_value')},
            },
        ),
        migrations.CreateModel(
            name='ChannelNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_property', 'عقار جديد'), ('price_drop', 'انخفاض السعر'), ('featured_property', 'عقار مميز'), ('channel_update', 'تحديث القناة'), ('new_review', 'مراجعة جديدة'), ('reply_to_review', 'رد على مراجعة'), ('milestone', 'إنجاز')], max_length=30, verbose_name='نوع الإشعار')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('link', models.URLField(blank=True, verbose_name='رابط')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='properties.brokerchannel', verbose_name='القناة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار قناة',
                'verbose_name_plural': 'إشعارات القنوات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='properties__user_id_3b0e74_idx'), models.Index(fields=['channel', '-created_at'], name='properties__channel_305e46_idx'), models.Index(fields=['is_read'], name='properties__is_read_6f47cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChannelRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], verbose_name='التقييم العام')),
                ('content_quality_rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5', null=True, verbose_name='جودة المحتوى')),
                ('response_speed_rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5', null=True, verbose_name='سرعة الرد')),
                ('trust_rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5', null=True, verbose_name='الثقة')),
                ('variety_rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5', null=True, verbose_name='تنوع العقارات')),
                ('review', models.TextField(blank=True, verbose_name='مراجعة مفصلة')),
                ('is_verified', models.BooleanField(default=False, verbose_name='مراجعة موثقة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقييم')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='properties.brokerchannel', verbose_name='القناة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_ratings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تقييم قناة',
                'verbose_name_plural': 'تقييمات القنوات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', 'rating'], name='properties__channel_0214df_idx'), models.Index(fields=['-rating'], name='properties__rating_f2a8ba_idx'), models.Index(fields=['is_verified'], name='properties__is_veri_fcd446_idx')],
                'unique_together': {('channel', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='channelreview',
            index=models.Index(fields=['channel', '-created_at'], name='properties__channel_0f5f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='channelreview',
            index=models.Index(fields=['is_approved'], name='properties__is_appr_465de1_idx'),
        ),
        migrations.AddIndex(
            model_name='channelreview',
            index=models.Index(fields=['is_featured'], name='properties__is_feat_29543d_idx'),
        ),
        migrations.AddIndex(
            model_name='channelshare',
            index=models.Index(fields=['channel', '-created_at'], name='properties__channel_4cee72_idx'),
        ),
        migrations.AddIndex(
            model_name='channelshare',
            index=models.Index(fields=['platform'], name='properties__platfor_7f34ce_idx'),
        ),
    ]
