# Generated by Django 6.0.6 on 2026-07-06 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0076_channelanalytics_channelreview_channelreviewreply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='balconies',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد الشرفات'),
        ),
        migrations.AddField(
            model_name='property',
            name='building_area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مساحة البناء (م²)'),
        ),
        migrations.AddField(
            model_name='property',
            name='building_condition',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='حالة البناء'),
        ),
        migrations.AddField(
            model_name='property',
            name='city_outside',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.city', verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='property',
            name='dining_rooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد غرف الطعام'),
        ),
        migrations.AddField(
            model_name='property',
            name='direction',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الاتجاه'),
        ),
        migrations.AddField(
            model_name='property',
            name='facade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الواجهة'),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='رقم الطابق'),
        ),
        migrations.AddField(
            model_name='property',
            name='governorate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_alarm',
            field=models.BooleanField(default=False, verbose_name='نظام الإنذار'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_cctv',
            field=models.BooleanField(default=False, verbose_name='كاميرات المراقبة'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_cooling',
            field=models.BooleanField(default=False, verbose_name='التبريد'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_elevator',
            field=models.BooleanField(default=False, verbose_name='مصعد'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_garden',
            field=models.BooleanField(default=False, verbose_name='حديقة'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_generator',
            field=models.BooleanField(default=False, verbose_name='مولد'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_heating',
            field=models.BooleanField(default=False, verbose_name='التدفئة'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_internet',
            field=models.BooleanField(default=False, verbose_name='الإنترنت'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_national_electricity',
            field=models.BooleanField(default=False, verbose_name='الكهرباء الوطنية'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_pool',
            field=models.BooleanField(default=False, verbose_name='مسبح'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_security_system',
            field=models.BooleanField(default=False, verbose_name='نظام الأمان'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_sewerage',
            field=models.BooleanField(default=False, verbose_name='المجاري'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_solar_power',
            field=models.BooleanField(default=False, verbose_name='نظام الطاقة الشمسية'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_water',
            field=models.BooleanField(default=False, verbose_name='الماء'),
        ),
        migrations.AddField(
            model_name='property',
            name='kitchens',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد المطابخ'),
        ),
        migrations.AddField(
            model_name='property',
            name='landmark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='أقرب نقطة دالة'),
        ),
        migrations.AddField(
            model_name='property',
            name='living_rooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد الصالات'),
        ),
        migrations.AddField(
            model_name='property',
            name='nahiyah',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الناحية'),
        ),
        migrations.AddField(
            model_name='property',
            name='negotiable',
            field=models.BooleanField(default=False, verbose_name='قابل للتفاوض'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المالك (اختياري)'),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_spaces',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد مواقف السيارات'),
        ),
        migrations.AddField(
            model_name='property',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='الرمز البريدي'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم الإعلان'),
        ),
        migrations.AddField(
            model_name='property',
            name='subdistrict',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='القضاء'),
        ),
        migrations.AddField(
            model_name='property',
            name='total_area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='المساحة الكلية (م²)'),
        ),
        migrations.AddField(
            model_name='property',
            name='total_floors',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد الطوابق'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('house', 'بيت'), ('apartment', 'شقة'), ('villa', 'فيلا'), ('duplex', 'دوبلكس'), ('residential_complex', 'مجمع سكني'), ('shop', 'محل'), ('office', 'مكتب'), ('mall', 'مول / مركز تجاري'), ('car_showroom', 'معرض سيارات'), ('warehouse', 'مخزن'), ('residential_building', 'بناية سكنية'), ('commercial_building', 'عمارة تجارية'), ('investment_land', 'أرض للاستثمار'), ('apartment_complex', 'مجمع شقق'), ('small_hotel', 'فندق صغير'), ('chalet', 'شاليه'), ('resort', 'منتجع'), ('hotel', 'فندق'), ('hotel_apartment', 'شقق فندقية'), ('tourism_house', 'بيت سياحي'), ('residential_land', 'أرض سكنية'), ('agricultural_land', 'أرض زراعية'), ('commercial_land', 'أرض تجارية'), ('investment_land', 'أرض استثمارية'), ('outside_apartment', 'شقة خارج العراق'), ('outside_villa', 'فيلا خارج العراق'), ('outside_palace', 'قصر خارج العراق'), ('outside_house', 'منزل خارج العراق'), ('outside_land', 'أرض خارج العراق'), ('outside_commercial', 'عقار تجاري خارج العراق')], max_length=50, verbose_name='نوع العقار'),
        ),
    ]
