# Generated by Django 6.0.6 on 2026-07-06 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0077_property_balconies_property_building_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutsideProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_province', models.CharField(blank=True, max_length=100, null=True, verbose_name='الولاية أو المحافظة')),
                ('local_currency', models.CharField(blank=True, max_length=3, null=True, verbose_name='العملة المحلية')),
                ('taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الضرائب')),
                ('registration_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='رسوم التسجيل')),
                ('foreign_ownership_laws', models.TextField(blank=True, verbose_name='قوانين التملك للأجانب')),
                ('hoa_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='رسوم جمعية المالكين')),
                ('property_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ضريبة العقار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outside_details', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'عقار خارج العراق',
                'verbose_name_plural': 'عقارات خارج العراق',
            },
        ),
        migrations.CreateModel(
            name='PropertyHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200, verbose_name='اسم الفندق')),
                ('star_rating', models.PositiveSmallIntegerField(choices=[(1, '1 نجوم'), (2, '2 نجوم'), (3, '3 نجوم'), (4, '4 نجوم'), (5, '5 نجوم')], verbose_name='عدد النجوم')),
                ('classification', models.CharField(blank=True, max_length=50, null=True, verbose_name='التصنيف')),
                ('total_rooms', models.PositiveIntegerField(verbose_name='عدد الغرف')),
                ('suites', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='الأجنحة')),
                ('family_rooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='الغرف العائلية')),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر لليلة')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='العملة')),
                ('has_restaurant', models.BooleanField(default=False, verbose_name='مطاعم')),
                ('has_cafe', models.BooleanField(default=False, verbose_name='مقاهي')),
                ('has_pool', models.BooleanField(default=False, verbose_name='مسابح')),
                ('has_gym', models.BooleanField(default=False, verbose_name='نادي رياضي')),
                ('has_spa', models.BooleanField(default=False, verbose_name='سبا')),
                ('has_conference_hall', models.BooleanField(default=False, verbose_name='قاعة مؤتمرات')),
                ('direct_booking', models.BooleanField(default=False, verbose_name='الحجز المباشر')),
                ('booking_url', models.URLField(blank=True, verbose_name='رابط الحجز')),
                ('overall_rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='التقييم العام')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='عدد التقييمات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_details', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'فندق عقاري',
                'verbose_name_plural': 'فنادق عقارية',
            },
        ),
        migrations.CreateModel(
            name='PropertyResort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resort_type', models.CharField(choices=[('resort', 'منتجع'), ('chalet', 'شاليه'), ('cabin', 'كوخ'), ('tourism_farm', 'مزرعة سياحية'), ('beach', 'شاطئ'), ('rest_house', 'استراحة'), ('camp', 'مخيم'), ('tourism_city', 'مدينة سياحية')], max_length=20, verbose_name='نوع المنتجع')),
                ('resort_name', models.CharField(max_length=200, verbose_name='اسم المنتجع')),
                ('max_guests', models.PositiveIntegerField(verbose_name='عدد الأشخاص الأقصى')),
                ('min_guests', models.PositiveSmallIntegerField(default=1, verbose_name='عدد الأشخاص الأدنى')),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر لليلة')),
                ('price_per_week', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر للأسبوع')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='العملة')),
                ('min_booking_duration', models.PositiveSmallIntegerField(default=1, verbose_name='مدة الحجز الدنيا (أيام)')),
                ('max_booking_duration', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='مدة الحجز القصوى (أيام)')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='واي فاي')),
                ('has_kitchen', models.BooleanField(default=False, verbose_name='مطبخ')),
                ('has_bbq', models.BooleanField(default=False, verbose_name='شواء')),
                ('has_playground', models.BooleanField(default=False, verbose_name='ملعب أطفال')),
                ('has_parking', models.BooleanField(default=False, verbose_name='موقف سيارات')),
                ('activities', models.TextField(blank=True, verbose_name='الأنشطة المتاحة')),
                ('overall_rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='التقييم العام')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='عدد التقييمات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resort_details', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'منتجع عقاري',
                'verbose_name_plural': 'المنتجعات العقارية',
            },
        ),
    ]
