# Generated by Django 6.0.6 on 2026-07-06 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0078_outsideproperty_propertyhotel_propertyresort'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='image_type',
            field=models.CharField(choices=[('photo', 'صورة عادية'), ('360', 'صورة 360°'), ('floor_plan', 'مخطط طابق'), ('site_plan', 'مخطط موقع'), ('drone', 'تصوير جوي')], default='photo', max_length=20, verbose_name='نوع الصورة'),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='المدة (ثواني)'),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='video_type',
            field=models.CharField(choices=[('regular', 'فيديو عادي'), ('drone', 'فيديو Drone'), ('intro', 'فيديو تعريفي'), ('virtual_tour', 'جولة افتراضية')], default='regular', max_length=20, verbose_name='نوع الفيديو'),
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('pdf', 'ملف PDF'), ('ownership', 'وثيقة الملكية'), ('contract', 'عقد'), ('floor_plan', 'مخطط الطابق'), ('site_plan', 'مخطط الموقع'), ('other', 'أخرى')], max_length=20, verbose_name='نوع المستند')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المستند')),
                ('file', models.FileField(upload_to='property_documents/', verbose_name='الملف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'مستند عقار',
                'verbose_name_plural': 'مستندات العقارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyMediaStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_images', models.PositiveIntegerField(default=0, verbose_name='عدد الصور')),
                ('image_views', models.PositiveIntegerField(default=0, verbose_name='مشاهدات الصور')),
                ('total_videos', models.PositiveIntegerField(default=0, verbose_name='عدد الفيديوهات')),
                ('video_views', models.PositiveIntegerField(default=0, verbose_name='مشاهدات الفيديوهات')),
                ('total_360_tours', models.PositiveIntegerField(default=0, verbose_name='عدد الجولات 360°')),
                ('tour_views', models.PositiveIntegerField(default=0, verbose_name='مشاهدات الجولات')),
                ('total_documents', models.PositiveIntegerField(default=0, verbose_name='عدد المستندات')),
                ('document_downloads', models.PositiveIntegerField(default=0, verbose_name='تحميلات المستندات')),
                ('vr_views', models.PositiveIntegerField(default=0, verbose_name='مشاهدات VR')),
                ('ar_views', models.PositiveIntegerField(default=0, verbose_name='مشاهدات AR')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media_stats', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'إحصائيات الوسائط',
                'verbose_name_plural': 'إحصائيات الوسائط',
            },
        ),
    ]
