# Generated by Django 6.0.6 on 2026-07-06 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0079_propertyimage_image_type_propertyvideo_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('client_phone', models.CharField(max_length=20, verbose_name='رقم هاتف العميل')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('appointment_date', models.DateTimeField(verbose_name='تاريخ الموعد')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحجز')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'حجز موعد',
                'verbose_name_plural': 'حجوز المواعيد',
                'ordering': ['-appointment_date'],
            },
        ),
        migrations.CreateModel(
            name='PropertyInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_type', models.CharField(choices=[('general', 'استفسار عام'), ('price', 'استفسار عن السعر'), ('viewing', 'طلب مشاهدة'), ('financing', 'استفسار عن التمويل'), ('documents', 'طلب مستندات'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الاستفسار')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('preferred_contact_method', models.CharField(choices=[('email', 'البريد الإلكتروني'), ('phone', 'الهاتف'), ('whatsapp', 'واتساب')], default='email', max_length=20, verbose_name='طريقة التواصل المفضلة')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تم الحل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'استفسار',
                'verbose_name_plural': 'الاستفسارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100, verbose_name='اسم المرسل')),
                ('sender_username', models.CharField(blank=True, max_length=100, verbose_name='اسم المستخدم')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_messages', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'رسالة تيليجرام',
                'verbose_name_plural': 'رسائل تيليجرام',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100, verbose_name='اسم المرسل')),
                ('sender_phone', models.CharField(max_length=20, verbose_name='رقم هاتف المرسل')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'رسالة واتساب',
                'verbose_name_plural': 'رسائل الواتساب',
                'ordering': ['-sent_at'],
            },
        ),
    ]
