# Generated by Django 6.0.6 on 2026-07-06 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0080_appointmentbooking_propertyinquiry_telegrammessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyConversionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_leads', models.PositiveIntegerField(default=0, verbose_name='إجمالي العملاء المحتملين')),
                ('qualified_leads', models.PositiveIntegerField(default=0, verbose_name='العملاء المؤهلين')),
                ('converted_leads', models.PositiveIntegerField(default=0, verbose_name='العملاء المحولين')),
                ('total_appointments', models.PositiveIntegerField(default=0, verbose_name='إجمالي المواعيد')),
                ('completed_appointments', models.PositiveIntegerField(default=0, verbose_name='المواعيد المكتملة')),
                ('cancelled_appointments', models.PositiveIntegerField(default=0, verbose_name='المواعيد الملغاة')),
                ('total_offers', models.PositiveIntegerField(default=0, verbose_name='إجمالي العروض')),
                ('accepted_offers', models.PositiveIntegerField(default=0, verbose_name='العروض المقبولة')),
                ('rejected_offers', models.PositiveIntegerField(default=0, verbose_name='العروض المرفوضة')),
                ('total_sales', models.PositiveIntegerField(default=0, verbose_name='إجمالي المبيعات')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الإيرادات')),
                ('view_to_inquiry_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='معدل التحويل من مشاهدة لاستفسار (%)')),
                ('inquiry_to_appointment_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='معدل التحويل من استفسار لموعد (%)')),
                ('appointment_to_sale_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='معدل التحويل من موعد لبيع (%)')),
                ('avg_time_to_first_contact', models.PositiveIntegerField(default=0, verbose_name='متوسط الوقت للتواصل الأول (ساعات)')),
                ('avg_time_to_appointment', models.PositiveIntegerField(default=0, verbose_name='متوسط الوقت للموعد (أيام)')),
                ('avg_time_to_sale', models.PositiveIntegerField(default=0, verbose_name='متوسط الوقت للبيع (أيام)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_stats', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'إحصائيات التحويل',
                'verbose_name_plural': 'إحصائيات التحويل',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyEngagementStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_favorites', models.PositiveIntegerField(default=0, verbose_name='إجمالي المفضلة')),
                ('active_favorites', models.PositiveIntegerField(default=0, verbose_name='المفضلة النشطة')),
                ('total_shares', models.PositiveIntegerField(default=0, verbose_name='إجمالي المشاركات')),
                ('shares_whatsapp', models.PositiveIntegerField(default=0, verbose_name='مشاركات واتساب')),
                ('shares_facebook', models.PositiveIntegerField(default=0, verbose_name='مشاركات فيسبوك')),
                ('shares_twitter', models.PositiveIntegerField(default=0, verbose_name='مشاركات تويتر')),
                ('shares_telegram', models.PositiveIntegerField(default=0, verbose_name='مشاركات تيليجرام')),
                ('total_calls', models.PositiveIntegerField(default=0, verbose_name='إجمالي المكالمات')),
                ('total_messages', models.PositiveIntegerField(default=0, verbose_name='إجمالي الرسائل')),
                ('total_inquiries', models.PositiveIntegerField(default=0, verbose_name='إجمالي الاستفسارات')),
                ('added_to_comparison', models.PositiveIntegerField(default=0, verbose_name='أضيف للمقارنة')),
                ('avg_time_on_page', models.PositiveIntegerField(default=0, verbose_name='متوسط الوقت على الصفحة (ثواني)')),
                ('bounce_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='معدل الارتداد (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_stats', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'إحصائيات التفاعل',
                'verbose_name_plural': 'إحصائيات التفاعل',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyViewStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='إجمالي المشاهدات')),
                ('unique_views', models.PositiveIntegerField(default=0, verbose_name='المشاهدات الفريدة')),
                ('views_today', models.PositiveIntegerField(default=0, verbose_name='مشاهدات اليوم')),
                ('views_yesterday', models.PositiveIntegerField(default=0, verbose_name='مشاهدات الأمس')),
                ('views_this_week', models.PositiveIntegerField(default=0, verbose_name='مشاهدات هذا الأسبوع')),
                ('views_this_month', models.PositiveIntegerField(default=0, verbose_name='مشاهدات هذا الشهر')),
                ('peak_hour', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ساعة الذروة')),
                ('peak_day', models.CharField(blank=True, max_length=20, verbose_name='يوم الذروة')),
                ('views_from_search', models.PositiveIntegerField(default=0, verbose_name='مشاهدات من البحث')),
                ('views_from_direct', models.PositiveIntegerField(default=0, verbose_name='مشاهدات مباشرة')),
                ('views_from_social', models.PositiveIntegerField(default=0, verbose_name='مشاهدات من التواصل الاجتماعي')),
                ('views_from_referral', models.PositiveIntegerField(default=0, verbose_name='مشاهدات من إحالات')),
                ('views_desktop', models.PositiveIntegerField(default=0, verbose_name='مشاهدات من سطح المكتب')),
                ('views_mobile', models.PositiveIntegerField(default=0, verbose_name='مشاهدات من الجوال')),
                ('views_tablet', models.PositiveIntegerField(default=0, verbose_name='مشاهدات من الأجهزة اللوحية')),
                ('top_viewing_locations', models.JSONField(blank=True, default=dict, verbose_name='أهم مواقع المشاهدة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_stats', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'إحصائيات المشاهدات',
                'verbose_name_plural': 'إحصائيات المشاهدات',
                'ordering': ['-updated_at'],
            },
        ),
    ]
