# Generated by Django 6.0.6 on 2026-07-06 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0081_propertyconversionstats_propertyengagementstats_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ai_generated_description',
            field=models.TextField(blank=True, verbose_name='وصف مولد بالذكاء الاصطناعي'),
        ),
        migrations.AddField(
            model_name='property',
            name='ai_image_enhanced',
            field=models.BooleanField(default=False, verbose_name='تم تحسين الصور'),
        ),
        migrations.AddField(
            model_name='property',
            name='ai_keywords',
            field=models.TextField(blank=True, verbose_name='كلمات مفتاحية مقترحة'),
        ),
        migrations.AddField(
            model_name='property',
            name='ai_suggested_price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='السعر المقترح'),
        ),
        migrations.AddField(
            model_name='property',
            name='ar_available',
            field=models.BooleanField(default=False, verbose_name='دعم الواقع المعزز'),
        ),
        migrations.AddField(
            model_name='property',
            name='booking_available',
            field=models.BooleanField(default=False, verbose_name='الحجز متاح'),
        ),
        migrations.AddField(
            model_name='property',
            name='booking_url',
            field=models.URLField(blank=True, verbose_name='رابط الحجز'),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_airport',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='المسافة للمطار (كم)'),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_city_center',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='المسافة لمركز المدينة (كم)'),
        ),
        migrations.AddField(
            model_name='property',
            name='energy_efficient',
            field=models.BooleanField(default=False, verbose_name='موفر للطاقة'),
        ),
        migrations.AddField(
            model_name='property',
            name='foreign_ownership_laws',
            field=models.TextField(blank=True, verbose_name='قوانين التملك للأجانب'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_airport_shuttle',
            field=models.BooleanField(default=False, verbose_name='نقل من المطار'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_cafe',
            field=models.BooleanField(default=False, verbose_name='مقهى'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_conference_hall',
            field=models.BooleanField(default=False, verbose_name='قاعة مؤتمرات'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_double_glazing',
            field=models.BooleanField(default=False, verbose_name='زجاج مزدوج'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_elevator_accessibility',
            field=models.BooleanField(default=False, verbose_name='مصعد متاح'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_green_building_cert',
            field=models.BooleanField(default=False, verbose_name='شهادة بناء أخضر'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_gym',
            field=models.BooleanField(default=False, verbose_name='نادي رياضي'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_insulation',
            field=models.BooleanField(default=False, verbose_name='عزل حراري'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_laundry',
            field=models.BooleanField(default=False, verbose_name='خدمة الغسيل'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='موقف سيارات'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_ramp',
            field=models.BooleanField(default=False, verbose_name='منحدر'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_restaurant',
            field=models.BooleanField(default=False, verbose_name='مطعم'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_room_service',
            field=models.BooleanField(default=False, verbose_name='خدمة الغرف'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_smart_home',
            field=models.BooleanField(default=False, verbose_name='منزل ذكي'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_spa',
            field=models.BooleanField(default=False, verbose_name='سبا'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_swimming_pool',
            field=models.BooleanField(default=False, verbose_name='مسبح'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_wifi',
            field=models.BooleanField(default=False, verbose_name='واي فاي'),
        ),
        migrations.AddField(
            model_name='property',
            name='hoa_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='رسوم الجمعية'),
        ),
        migrations.AddField(
            model_name='property',
            name='hotel_family_rooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='الغرف العائلية'),
        ),
        migrations.AddField(
            model_name='property',
            name='hotel_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='التقييم'),
        ),
        migrations.AddField(
            model_name='property',
            name='hotel_rooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد الغرف'),
        ),
        migrations.AddField(
            model_name='property',
            name='hotel_stars',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد النجوم'),
        ),
        migrations.AddField(
            model_name='property',
            name='hotel_suites',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد الأجنحة'),
        ),
        migrations.AddField(
            model_name='property',
            name='last_renovation',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سنة آخر ترميم'),
        ),
        migrations.AddField(
            model_name='property',
            name='live_stream_enabled',
            field=models.BooleanField(default=False, verbose_name='تفعيل البث المباشر'),
        ),
        migrations.AddField(
            model_name='property',
            name='live_stream_scheduled',
            field=models.DateTimeField(blank=True, null=True, verbose_name='موعد البث المجدول'),
        ),
        migrations.AddField(
            model_name='property',
            name='live_stream_status',
            field=models.CharField(blank=True, choices=[('scheduled', 'مجدول'), ('live', 'مباشر'), ('ended', 'منتهي'), ('cancelled', 'ملغي')], max_length=20, verbose_name='حالة البث'),
        ),
        migrations.AddField(
            model_name='property',
            name='live_stream_url',
            field=models.URLField(blank=True, verbose_name='رابط البث المباشر'),
        ),
        migrations.AddField(
            model_name='property',
            name='maintenance_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='رسوم الصيانة الشهرية'),
        ),
        migrations.AddField(
            model_name='property',
            name='max_booking_duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='أقصى مدة حجز (أيام)'),
        ),
        migrations.AddField(
            model_name='property',
            name='min_booking_duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='أقل مدة حجز (أيام)'),
        ),
        migrations.AddField(
            model_name='property',
            name='nearest_landmark',
            field=models.CharField(blank=True, max_length=200, verbose_name='أقرب معلم'),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_type',
            field=models.CharField(blank=True, choices=[('covered', 'مغطى'), ('open', 'مفتوح'), ('underground', 'تحت الأرض'), ('garage', 'مرآب')], max_length=20, verbose_name='نوع الموقف'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عمر العقار (سنوات)'),
        ),
        migrations.AddField(
            model_name='property',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Code'),
        ),
        migrations.AddField(
            model_name='property',
            name='registration_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='رسوم التسجيل'),
        ),
        migrations.AddField(
            model_name='property',
            name='resort_activities',
            field=models.TextField(blank=True, verbose_name='الأنشطة المتاحة'),
        ),
        migrations.AddField(
            model_name='property',
            name='resort_capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سعة الاستيعاب'),
        ),
        migrations.AddField(
            model_name='property',
            name='short_share_code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='رمز المشاركة المختصر'),
        ),
        migrations.AddField(
            model_name='property',
            name='taxes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الضرائب (%)'),
        ),
        migrations.AddField(
            model_name='property',
            name='view_type',
            field=models.CharField(blank=True, choices=[('city', 'إطلالة مدينة'), ('sea', 'إطلالة بحر'), ('mountain', 'إطلالة جبل'), ('garden', 'إطلالة حديقة'), ('street', 'إطلالة شارع'), ('park', 'إطلالة حديقة عامة'), ('none', 'لا يوجد')], max_length=50, verbose_name='نوع الإطلالة'),
        ),
        migrations.AddField(
            model_name='property',
            name='virtual_tour_url',
            field=models.URLField(blank=True, verbose_name='رابط الجولة الافتراضية'),
        ),
        migrations.AddField(
            model_name='property',
            name='vr_tour_url',
            field=models.URLField(blank=True, verbose_name='رابط جولة VR'),
        ),
        migrations.AddField(
            model_name='property',
            name='wheelchair_accessible',
            field=models.BooleanField(default=False, verbose_name='مخصص للكراسي المتحركة'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('house', 'بيت'), ('apartment', 'شقة'), ('villa', 'فيلا'), ('duplex', 'دوبلكس'), ('residential_complex', 'مجمع سكني'), ('penthouse', 'بنتهاوس'), ('studio', 'ستوديو'), ('townhouse', 'تاون هاوس'), ('shop', 'محل'), ('office', 'مكتب'), ('mall', 'مول / مركز تجاري'), ('car_showroom', 'معرض سيارات'), ('warehouse', 'مخزن'), ('tower', 'برج'), ('factory', 'معمل'), ('clinic', 'عيادة'), ('pharmacy', 'صيدلية'), ('restaurant', 'مطعم'), ('cafe', 'مقهى'), ('residential_building', 'بناية سكنية'), ('commercial_building', 'عمارة تجارية'), ('investment_land', 'أرض للاستثمار'), ('apartment_complex', 'مجمع شقق'), ('small_hotel', 'فندق صغير'), ('investment_property', 'عقار استثماري'), ('chalet', 'شاليه'), ('resort', 'منتجع'), ('hotel', 'فندق'), ('hotel_apartment', 'شقق فندقية'), ('tourism_house', 'بيت سياحي'), ('tourist_farm', 'مزرعة سياحية'), ('beach_house', 'بيت شاطئي'), ('rest_house', 'استراحة'), ('camp_site', 'مخيم'), ('tourist_city', 'مدينة سياحية'), ('cabin', 'كوخ'), ('residential_land', 'أرض سكنية'), ('agricultural_land', 'أرض زراعية'), ('commercial_land', 'أرض تجارية'), ('investment_land', 'أرض استثمارية'), ('outside_apartment', 'شقة خارج العراق'), ('outside_villa', 'فيلا خارج العراق'), ('outside_palace', 'قصر خارج العراق'), ('outside_house', 'منزل خارج العراق'), ('outside_land', 'أرض خارج العراق'), ('outside_commercial', 'عقار تجاري خارج العراق')], max_length=50, verbose_name='نوع العقار'),
        ),
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان البث')),
                ('description', models.TextField(blank=True, verbose_name='وصف البث')),
                ('stream_url', models.URLField(verbose_name='رابط البث')),
                ('stream_key', models.CharField(blank=True, max_length=200, verbose_name='مفتاح البث')),
                ('platform', models.CharField(choices=[('youtube', 'يوتيوب'), ('facebook', 'فيسبوك'), ('instagram', 'إنستغرام'), ('tiktok', 'تيك توك'), ('twitch', 'توتش'), ('custom', 'مخصص')], default='youtube', max_length=20, verbose_name='منصة البث')),
                ('scheduled_start', models.DateTimeField(verbose_name='موعد البدء المجدول')),
                ('scheduled_end', models.DateTimeField(blank=True, null=True, verbose_name='موعد الانتهاء المجدول')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='وقت البدء الفعلي')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء الفعلي')),
                ('status', models.CharField(choices=[('scheduled', 'مجدول'), ('live', 'مباشر'), ('ended', 'منتهي'), ('cancelled', 'ملغي')], default='scheduled', max_length=20, verbose_name='الحالة')),
                ('is_active', models.BooleanField(default=False, verbose_name='نشط')),
                ('viewers_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدين')),
                ('peak_viewers', models.PositiveIntegerField(default=0, verbose_name='أقصى عدد مشاهدين')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='عدد التعليقات')),
                ('shares_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاركات')),
                ('is_recorded', models.BooleanField(default=False, verbose_name='تم التسجيل')),
                ('recording_url', models.URLField(blank=True, verbose_name='رابط التسجيل')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='live_streams/', verbose_name='صورة مصغرة')),
                ('notify_subscribers', models.BooleanField(default=True, verbose_name='إشعار المشتركين')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='تم إرسال الإشعار')),
                ('notification_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإشعار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_streams', to='properties.broker', verbose_name='الدلال')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_streams', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'بث مباشر',
                'verbose_name_plural': 'البثوث المباشرة',
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='LiveStreamComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='اسم الكاتب')),
                ('author_phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('comment', models.TextField(verbose_name='التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('live_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='properties.livestream', verbose_name='البث المباشر')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تعليق بث مباشر',
                'verbose_name_plural': 'تعليقات البث المباشر',
                'ordering': ['-created_at'],
            },
        ),
    ]
