# Generated by Django 6.0.6 on 2026-07-06 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0082_property_ai_generated_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('text', 'نص'), ('image', 'صورة'), ('video', 'فيديو'), ('property', 'عقار'), ('ad', 'إعلان')], default='text', max_length=20, verbose_name='نوع المنشور')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('image', models.ImageField(blank=True, null=True, upload_to='channel_posts/images/', verbose_name='صورة')),
                ('video', models.FileField(blank=True, null=True, upload_to='channel_posts/videos/', verbose_name='فيديو')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='عدد الإعجابات')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='عدد التعليقات')),
                ('shares_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاركات')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='مثبت')),
                ('is_advertisement', models.BooleanField(default=False, verbose_name='إعلان مدفوع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='properties.brokerchannel', verbose_name='القناة')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_posts', to='properties.property', verbose_name='العقار المرتبط')),
            ],
            options={
                'verbose_name': 'منشور قناة',
                'verbose_name_plural': 'منشورات القنوات',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعليق')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='properties.channelpostcomment', verbose_name='الرد على')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='properties.channelpost', verbose_name='المنشور')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_post_comments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تعليق منشور',
                'verbose_name_plural': 'تعليقات المنشورات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الفيديو')),
                ('description', models.TextField(blank=True, verbose_name='وصف الفيديو')),
                ('video_file', models.FileField(upload_to='channel_videos/', verbose_name='ملف الفيديو')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='channel_videos/thumbnails/', verbose_name='صورة مصغرة')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='مدة الفيديو (ثانية)')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='عدد الإعجابات')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='عدد التعليقات')),
                ('shares_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاركات')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='الوسوم (مفصولة بفاصلة)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='properties.brokerchannel', verbose_name='القناة')),
            ],
            options={
                'verbose_name': 'فيديو قناة',
                'verbose_name_plural': 'فيديوهات القنوات',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelVideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعليق')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='properties.channelvideocomment', verbose_name='الرد على')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_video_comments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='properties.channelvideo', verbose_name='الفيديو')),
            ],
            options={
                'verbose_name': 'تعليق فيديو',
                'verbose_name_plural': 'تعليقات الفيديوهات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإعجاب')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='properties.channelpost', verbose_name='المنشور')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_post_likes', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إعجاب منشور',
                'verbose_name_plural': 'إعجابات المنشورات',
                'unique_together': {('user', 'post')},
            },
        ),
        migrations.CreateModel(
            name='ChannelVideoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإعجاب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_video_likes', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='properties.channelvideo', verbose_name='الفيديو')),
            ],
            options={
                'verbose_name': 'إعجاب فيديو',
                'verbose_name_plural': 'إعجابات الفيديوهات',
                'unique_together': {('user', 'video')},
            },
        ),
    ]
