# Generated by Django 6.0.6 on 2026-07-06 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0083_channelpost_channelpostcomment_channelvideo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingrequest',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building_requests', to='properties.broker', verbose_name='الدلال'),
        ),
        migrations.AlterField(
            model_name='buildingrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building_requests', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
