# Generated by Django 6.0.6 on 2026-07-06 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('properties', '0085_auction_winner_auction_winning_bid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('warning', 'إنذار'), ('suspend', 'تعطيل'), ('unsuspend', 'رفع التعطيل'), ('delete', 'حذف'), ('ban', 'حظر'), ('unban', 'رفع الحظر'), ('mute', 'كتم'), ('unmute', 'رفع الكتم'), ('flag', 'إشارة'), ('unflag', 'إزالة الإشارة')], max_length=20, verbose_name='الإجراء')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف المحتوى المرتبط')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='المدة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإجراء')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions_taken', to=settings.AUTH_USER_MODEL, verbose_name='المشرف')),
                ('related_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='نوع المحتوى المرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إجراء مراقبة',
                'verbose_name_plural': 'إجراءات المراقبة',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='properties__user_id_09e548_idx'), models.Index(fields=['action', '-created_at'], name='properties__action_0e1c6c_idx'), models.Index(fields=['moderator', '-created_at'], name='properties__moderat_437120_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('violation', 'انتهاك القواعد'), ('spam', 'رسائل مزعجة'), ('fraud', 'احتيال'), ('harassment', 'مضايقة'), ('inappropriate', 'محتوى غير لائق'), ('multiple_warnings', 'إنذارات متعددة'), ('admin_decision', 'قرار إداري'), ('other', 'أخرى')], max_length=20, verbose_name='السبب')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('expired', 'منتهي'), ('lifted', 'مرفوع')], default='active', max_length=20, verbose_name='الحالة')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البدء')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('lifted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرفع')),
                ('lift_reason', models.TextField(blank=True, verbose_name='سبب الرفع')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('lifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifted_suspensions', to=settings.AUTH_USER_MODEL, verbose_name='مرفوع من قبل')),
                ('suspended_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_users', to=settings.AUTH_USER_MODEL, verbose_name='معطل من قبل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تعطيل مستخدم',
                'verbose_name_plural': 'تعطيلات المستخدمين',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['user', '-start_date'], name='properties__user_id_864cc3_idx'), models.Index(fields=['status', '-start_date'], name='properties__status_1c549c_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_type', models.CharField(choices=[('spam', 'رسائل مزعجة'), ('inappropriate', 'محتوى غير لائق'), ('harassment', 'مضايقة'), ('fraud', 'احتيال'), ('violation', 'انتهاك القواعد'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الإنذار')),
                ('severity', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('critical', 'حرج')], default='medium', max_length=20, verbose_name='الشدة')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف المحتوى المرتبط')),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='تم الاعتراف')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتراف')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_warnings', to=settings.AUTH_USER_MODEL, verbose_name='صادر من')),
                ('related_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='نوع المحتوى المرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إنذار مستخدم',
                'verbose_name_plural': 'إنذارات المستخدمين',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='properties__user_id_d8ccd9_idx'), models.Index(fields=['severity', '-created_at'], name='properties__severit_3c362e_idx'), models.Index(fields=['is_acknowledged'], name='properties__is_ackn_5d3eb4_idx')],
            },
        ),
    ]
