# Generated by Django 6.0.6 on 2026-07-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0086_usermoderationaction_usersuspension_userwarning'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyresort',
            name='address',
            field=models.TextField(blank=True, verbose_name='العنوان التفصيلي'),
        ),
        migrations.AddField(
            model_name='propertyresort',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت تسجيل الدخول'),
        ),
        migrations.AddField(
            model_name='propertyresort',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت تسجيل الخروج'),
        ),
        migrations.AddField(
            model_name='propertyresort',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='propertyresort',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='propertyresort',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='القضاء'),
        ),
        migrations.AddField(
            model_name='propertyresort',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='propertyresort',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='مميز'),
        ),
        migrations.AddField(
            model_name='propertyresort',
            name='governorate',
            field=models.CharField(blank=True, max_length=100, verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='propertyresort',
            name='has_ac',
            field=models.BooleanField(default=False, verbose_name='تكييف'),
        ),
        migrations.AddField(
            model_name='propertyresort',
            name='has_concierge',
            field=models.BooleanField(default=False, verbose_name='خدمة الاستقبال'),
        ),
        migrations.AddField(
            model_name='propertyresort',
            name='has_gym',
            field=models.BooleanField(default=False, verbose_name='نادي رياضي'),
        ),
        migrations.AddField(
            model_name='propertyresort',
            name='has_heating',
            field=models.BooleanField(default=False, verbose_name='تدفئة'),
        ),
        migrations.AddField(
            model_name='propertyresort',
            name='has_laundry',
            field=models.BooleanField(default=False, verbose_name='خدمة غسيل'),
        ),
        migrations.AddField(
            model_name='propertyresort',
            name='has_pool',
            field=models.BooleanField(default=False, verbose_name='مسبح'),
        ),
        migrations.AddField(
            model_name='propertyresort',
            name='has_restaurant',
            field=models.BooleanField(default=False, verbose_name='مطعم'),
        ),
        migrations.AddField(
            model_name='propertyresort',
            name='has_room_service',
            field=models.BooleanField(default=False, verbose_name='خدمة الغرف'),
        ),
        migrations.AddField(
            model_name='propertyresort',
            name='has_security',
            field=models.BooleanField(default=False, verbose_name='أمن وحراسة'),
        ),
        migrations.AddField(
            model_name='propertyresort',
            name='has_spa',
            field=models.BooleanField(default=False, verbose_name='سبا'),
        ),
        migrations.AddField(
            model_name='propertyresort',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='propertyresort',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='propertyresort',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='propertyresort',
            name='max_rooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد الغرف'),
        ),
        migrations.AddField(
            model_name='propertyresort',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='propertyresort',
            name='price_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر للشهر'),
        ),
        migrations.AddField(
            model_name='propertyresort',
            name='rules',
            field=models.TextField(blank=True, verbose_name='القواعد والشروط'),
        ),
        migrations.AddField(
            model_name='propertyresort',
            name='website',
            field=models.URLField(blank=True, verbose_name='الموقع الإلكتروني'),
        ),
        migrations.AddField(
            model_name='propertyresort',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الواتساب'),
        ),
    ]
