# Generated by Django 6.0.6 on 2026-07-06 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0087_propertyresort_address_propertyresort_check_in_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('super_admin', 'مسؤول النظام'), ('admin', 'مسؤول'), ('main_broker', 'دلال رئيسي'), ('sub_broker', 'دلال فرعي'), ('verified_broker', 'دلال موثق'), ('regular_broker', 'دلال عادي'), ('premium_user', 'مستخدم مميز'), ('regular_user', 'مستخدم عادي')], max_length=50, unique=True, verbose_name='اسم الدور')),
                ('display_name', models.CharField(max_length=100, verbose_name='الاسم المعروض')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('priority', models.IntegerField(default=0, verbose_name='الأولوية')),
                ('can_access_admin_panel', models.BooleanField(default=False, verbose_name='الوصول للوحة الإدارة')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='إدارة المستخدمين')),
                ('can_manage_brokers', models.BooleanField(default=False, verbose_name='إدارة الدلالين')),
                ('can_manage_properties', models.BooleanField(default=False, verbose_name='إدارة العقارات')),
                ('can_manage_auctions', models.BooleanField(default=False, verbose_name='إدارة المزادات')),
                ('can_manage_building_requests', models.BooleanField(default=False, verbose_name='إدارة طلبات البناء')),
                ('can_approve_content', models.BooleanField(default=False, verbose_name='الموافقة على المحتوى')),
                ('can_view_statistics', models.BooleanField(default=False, verbose_name='عرض الإحصائيات')),
                ('can_export_data', models.BooleanField(default=False, verbose_name='تصدير البيانات')),
                ('can_manage_settings', models.BooleanField(default=False, verbose_name='إدارة الإعدادات')),
                ('can_send_notifications', models.BooleanField(default=False, verbose_name='إرسال إشعارات')),
                ('can_moderate_users', models.BooleanField(default=False, verbose_name='مراقبة المستخدمين')),
                ('can_issue_warnings', models.BooleanField(default=False, verbose_name='إصدار إنذارات')),
                ('can_suspend_users', models.BooleanField(default=False, verbose_name='تعطيل المستخدمين')),
                ('can_delete_users', models.BooleanField(default=False, verbose_name='حذف المستخدمين')),
                ('can_add_properties', models.BooleanField(default=False, verbose_name='إضافة عقارات')),
                ('can_edit_own_properties', models.BooleanField(default=False, verbose_name='تعديل عقاراته')),
                ('can_edit_all_properties', models.BooleanField(default=False, verbose_name='تعديل جميع العقارات')),
                ('can_delete_own_properties', models.BooleanField(default=False, verbose_name='حذف عقاراته')),
                ('can_delete_all_properties', models.BooleanField(default=False, verbose_name='حذف جميع العقارات')),
                ('can_feature_properties', models.BooleanField(default=False, verbose_name='تمييز العقارات')),
                ('can_verify_brokers', models.BooleanField(default=False, verbose_name='توثيق الدلالين')),
                ('can_assign_roles', models.BooleanField(default=False, verbose_name='تعيين الأدوار')),
                ('can_manage_sub_brokers', models.BooleanField(default=False, verbose_name='إدارة الدلالين الفرعيين')),
                ('can_view_broker_stats', models.BooleanField(default=False, verbose_name='عرض إحصائيات الدلالين')),
                ('can_view_financial_data', models.BooleanField(default=False, verbose_name='عرض البيانات المالية')),
                ('can_manage_payments', models.BooleanField(default=False, verbose_name='إدارة المدفوعات')),
                ('can_manage_subscriptions', models.BooleanField(default=False, verbose_name='إدارة الاشتراكات')),
                ('can_view_commissions', models.BooleanField(default=False, verbose_name='عرض العمولات')),
                ('can_create_posts', models.BooleanField(default=False, verbose_name='إنشاء منشورات')),
                ('can_edit_all_posts', models.BooleanField(default=False, verbose_name='تعديل جميع المنشورات')),
                ('can_delete_posts', models.BooleanField(default=False, verbose_name='حذف المنشورات')),
                ('can_upload_videos', models.BooleanField(default=False, verbose_name='رفع فيديوهات')),
                ('can_send_messages', models.BooleanField(default=False, verbose_name='إرسال رسائل')),
                ('can_view_all_messages', models.BooleanField(default=False, verbose_name='عرض جميع الرسائل')),
                ('can_broadcast_messages', models.BooleanField(default=False, verbose_name='بث رسائل')),
                ('allowed_governorates', models.JSONField(blank=True, default=list, verbose_name='المحافظات المسموحة')),
                ('can_access_all_regions', models.BooleanField(default=False, verbose_name='الوصول لجميع المناطق')),
                ('max_properties', models.IntegerField(blank=True, null=True, verbose_name='الحد الأقصى للعقارات')),
                ('max_sub_brokers', models.IntegerField(blank=True, null=True, verbose_name='الحد الأقصى للدلالين الفرعيين')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'دور',
                'verbose_name_plural': 'الأدوار',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PermissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('assigned', 'تعيين'), ('revoked', 'إلغاء'), ('modified', 'تعديل'), ('expired', 'انتهاء')], max_length=20, verbose_name='الإجراء')),
                ('changes', models.JSONField(default=dict, verbose_name='التغييرات')),
                ('reason', models.TextField(blank=True, verbose_name='السبب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التغيير')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permitted_logs', to=settings.AUTH_USER_MODEL, verbose_name='نفذ بواسطة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_logs', to='properties.role', verbose_name='الدور')),
            ],
            options={
                'verbose_name': 'سجل صلاحية',
                'verbose_name_plural': 'سجلات الصلاحيات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعيين')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL, verbose_name='عين بواسطة')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_users', to='properties.role', verbose_name='الدور')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'دور مستخدم',
                'verbose_name_plural': 'أدوار المستخدمين',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
