# Generated by Django 6.0.6 on 2026-07-06 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0088_role_permissionlog_userrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedSubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الخطة')),
                ('plan_type', models.CharField(choices=[('properties_iraq', 'عقارات داخل العراق'), ('properties_outside', 'عقارات خارج العراق'), ('hotels', 'فنادق'), ('resorts', 'منتجعات'), ('building_requests', 'طلبات بناء'), ('auctions', 'مزادات'), ('combined', 'اشتراك مركب')], max_length=30, verbose_name='نوع الخطة')),
                ('tier', models.CharField(choices=[('regular', 'عادي'), ('premium', 'مميز')], max_length=20, verbose_name='المستوى')),
                ('price_per_day', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='السعر باليوم')),
                ('price_per_month', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='السعر بالشهر')),
                ('price_per_year', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='السعر بالسنة')),
                ('max_properties', models.IntegerField(default=1, verbose_name='الحد الأقصى للعقارات')),
                ('max_auctions', models.IntegerField(default=0, verbose_name='الحد الأقصى للمزادات')),
                ('max_building_requests', models.IntegerField(default=0, verbose_name='الحد الأقصى لطلبات البناء')),
                ('allow_property_replacement', models.BooleanField(default=True, verbose_name='السماح باستبدال العقارات')),
                ('allow_subscription_renewal', models.BooleanField(default=True, verbose_name='السماح بتجديد الاشتراك')),
                ('allow_expired_renewal', models.BooleanField(default=True, verbose_name='السماح بالتجديد على اشتراك منتهي')),
                ('extend_on_property_display', models.BooleanField(default=False, verbose_name='تمديد الوقت عند عرض العقار')),
                ('extend_days_per_display', models.IntegerField(default=0, verbose_name='أيام التمديد لكل عرض')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'خطة اشتراك متقدمة',
                'verbose_name_plural': 'خطط الاشتراك المتقدمة',
                'ordering': ['plan_type', 'tier'],
            },
        ),
        migrations.CreateModel(
            name='AuctionSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_auction', models.DecimalField(decimal_places=0, default=100000, max_digits=15, verbose_name='السعر لكل مزاد')),
                ('auctions_used', models.IntegerField(default=0, verbose_name='المزادات المستخدمة')),
                ('auctions_paid', models.IntegerField(default=0, verbose_name='المزادات المدفوعة')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('expired', 'منتهي'), ('suspended', 'معلق'), ('pending', 'قيد الانتظار')], default='active', max_length=20, verbose_name='الحالة')),
                ('total_paid', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='المبلغ المدفوع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_plan_subscriptions', to='properties.broker', verbose_name='الدلال')),
            ],
            options={
                'verbose_name': 'اشتراك مزادات',
                'verbose_name_plural': 'اشتراكات المزادات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrokerPlanSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ النهاية')),
                ('actual_end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء الفعلي')),
                ('properties_used', models.IntegerField(default=0, verbose_name='العقارات المستخدمة')),
                ('properties_replaced', models.IntegerField(default=0, verbose_name='العقارات المستبدلة')),
                ('auctions_used', models.IntegerField(default=0, verbose_name='المزادات المستخدمة')),
                ('building_requests_used', models.IntegerField(default=0, verbose_name='طلبات البناء المستخدمة')),
                ('last_replaced_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر استبدال')),
                ('replacement_history', models.JSONField(blank=True, default=list, verbose_name='تاريخ الاستبدال')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('expired', 'منتهي'), ('suspended', 'معلق'), ('pending', 'قيد الانتظار')], default='active', max_length=20, verbose_name='الحالة')),
                ('is_auto_renew', models.BooleanField(default=False, verbose_name='تجديد تلقائي')),
                ('total_paid', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='المبلغ المدفوع')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='طريقة الدفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_subscriptions', to='properties.broker', verbose_name='الدلال')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_subscriptions', to='properties.advancedsubscriptionplan', verbose_name='الخطة')),
            ],
            options={
                'verbose_name': 'اشتراك خطة دلال',
                'verbose_name_plural': 'اشتراكات خطط الدلالين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuildingRequestSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_price', models.DecimalField(decimal_places=0, default=1500000, max_digits=15, verbose_name='السعر السنوي')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ النهاية')),
                ('requests_used', models.IntegerField(default=0, verbose_name='الطلبات المستخدمة')),
                ('max_requests', models.IntegerField(default=1, verbose_name='الحد الأقصى للطلبات')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('expired', 'منتهي'), ('suspended', 'معلق'), ('pending', 'قيد الانتظار')], default='active', max_length=20, verbose_name='الحالة')),
                ('total_paid', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='المبلغ المدفوع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_plan_subscriptions', to='properties.broker', verbose_name='الدلال')),
            ],
            options={
                'verbose_name': 'اشتراك طلبات بناء',
                'verbose_name_plural': 'اشتراكات طلبات البناء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionRenewalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_requested', models.IntegerField(verbose_name='الأيام المطلوبة')),
                ('property_types', models.JSONField(default=list, verbose_name='أنواع العقارات المطلوبة')),
                ('estimated_cost', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='التكلفة التقديرية')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_renewals', to=settings.AUTH_USER_MODEL, verbose_name='تمت الموافقة بواسطة')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_requests', to='properties.broker', verbose_name='الدلال')),
                ('current_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_requests', to='properties.brokerplansubscription', verbose_name='الاشتراك الحالي')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.advancedsubscriptionplan', verbose_name='الخطة المطلوبة')),
            ],
            options={
                'verbose_name': 'طلب تجديد اشتراك',
                'verbose_name_plural': 'طلبات تجديد الاشتراكات',
                'ordering': ['-created_at'],
            },
        ),
    ]
