# Generated by Django 6.0.6 on 2026-07-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0089_advancedsubscriptionplan_auctionsubscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingrequestsubscription',
            name='annual_price',
            field=models.DecimalField(decimal_places=0, default=150000, max_digits=15, verbose_name='السعر السنوي'),
        ),
    ]
