# Generated by Django 6.0.6 on 2026-07-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0090_alter_buildingrequestsubscription_annual_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrenewalrequest',
            name='property_count',
            field=models.IntegerField(default=1, verbose_name='عدد العقارات'),
        ),
    ]
