# Generated by Django 6.0.6 on 2026-07-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0091_subscriptionrenewalrequest_property_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrenewalrequest',
            name='premium_count',
            field=models.IntegerField(default=0, verbose_name='عدد العقارات المميزة'),
        ),
        migrations.AddField(
            model_name='subscriptionrenewalrequest',
            name='regular_count',
            field=models.IntegerField(default=0, verbose_name='عدد العقارات العادية'),
        ),
        migrations.AlterField(
            model_name='subscriptionrenewalrequest',
            name='property_count',
            field=models.IntegerField(default=1, verbose_name='عدد العقارات الإجمالي'),
        ),
    ]
