# Generated by Django 6.0.6 on 2026-07-07 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('properties', '0092_subscriptionrenewalrequest_premium_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sent', models.IntegerField(default=0, verbose_name='العدد المرسل')),
                ('total_delivered', models.IntegerField(default=0, verbose_name='العدد المستلم')),
                ('total_read', models.IntegerField(default=0, verbose_name='العدد المقروء')),
                ('total_clicked', models.IntegerField(default=0, verbose_name='عدد النقرات')),
                ('total_failed', models.IntegerField(default=0, verbose_name='عدد الفشل')),
                ('delivery_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة التسليم')),
                ('read_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة القراءة')),
                ('click_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة النقر')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'سجل إشعار',
                'verbose_name_plural': 'سجلات الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('is_clicked', models.BooleanField(default=False, verbose_name='تم النقر')),
                ('is_archived', models.BooleanField(default=False, verbose_name='مؤرشفة')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القراءة')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النقر')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الأرشفة')),
                ('delivery_status', models.CharField(default='pending', max_length=20, verbose_name='حالة التسليم')),
                ('sent_via_email', models.BooleanField(default=False, verbose_name='أرسلت عبر البريد')),
                ('sent_via_push', models.BooleanField(default=False, verbose_name='أرسلت كإشعار دفع')),
                ('sent_via_sms', models.BooleanField(default=False, verbose_name='أرسلت عبر SMS')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'مستلم إشعار',
                'verbose_name_plural': 'مستلمو الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القالب')),
                ('title_template', models.CharField(max_length=200, verbose_name='قالب العنوان')),
                ('description_template', models.TextField(verbose_name='قالب الوصف')),
                ('notification_type', models.CharField(choices=[('info', 'معلومة'), ('success', 'نجاح'), ('warning', 'تحذير'), ('error', 'خطأ'), ('property', 'عقار'), ('message', 'رسالة'), ('rating', 'تقييم'), ('subscription', 'اشتراك'), ('auction', 'مزاد'), ('building', 'بناء'), ('system', 'نظام')], default='info', max_length=20, verbose_name='النوع')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='الأيقونة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قالب إشعار',
                'verbose_name_plural': 'قوالب الإشعارات',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='properties__user_id_e04696_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='properties__is_read_fd535c_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='button_link',
            field=models.URLField(blank=True, verbose_name='رابط الزر'),
        ),
        migrations.AddField(
            model_name='notification',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='نص الزر'),
        ),
        migrations.AddField(
            model_name='notification',
            name='color',
            field=models.CharField(default='#0d9488', max_length=7, verbose_name='اللون'),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة'),
        ),
        migrations.AddField(
            model_name='notification',
            name='description',
            field=models.TextField(default='', verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تنتهي في'),
        ),
        migrations.AddField(
            model_name='notification',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='الأيقونة'),
        ),
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.ImageField(blank=True, upload_to='notifications/', verbose_name='الصورة'),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفضة'), ('normal', 'عادية'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='normal', max_length=20, verbose_name='الأولوية'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='نوع المحتوى المرتبط'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف المحتوى المرتبط'),
        ),
        migrations.AddField(
            model_name='notification',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True, verbose_name='مجدولة للإرسال في'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال'),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('scheduled', 'مجدولة'), ('sent', 'مرسلة'), ('failed', 'فشلت')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='notification',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='الوسوم'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_active_users',
            field=models.BooleanField(default=False, verbose_name='المستخدمين النشطين'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_all_admins',
            field=models.BooleanField(default=False, verbose_name='جميع المشرفين'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_all_brokers',
            field=models.BooleanField(default=False, verbose_name='جميع الدلالين'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_all_users',
            field=models.BooleanField(default=False, verbose_name='جميع المستخدمين'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_area',
            field=models.CharField(blank=True, max_length=100, verbose_name='المنطقة'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_governorate',
            field=models.CharField(blank=True, max_length=100, verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_inactive_users',
            field=models.BooleanField(default=False, verbose_name='المستخدمين غير النشطين'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_min_properties',
            field=models.IntegerField(blank=True, null=True, verbose_name='أقل عدد عقارات'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_min_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='أقل تقييم'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_new_users',
            field=models.BooleanField(default=False, verbose_name='المستخدمين الجدد'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_premium_brokers',
            field=models.BooleanField(default=False, verbose_name='الدلالين المميزين'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_property_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='نوع العقار'),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'معلومة'), ('success', 'نجاح'), ('warning', 'تحذير'), ('error', 'خطأ'), ('property', 'عقار'), ('message', 'رسالة'), ('rating', 'تقييم'), ('subscription', 'اشتراك'), ('auction', 'مزاد'), ('building', 'بناء'), ('system', 'نظام')], default='info', max_length=20, verbose_name='النوع'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', '-created_at'], name='properties__status_5bd47c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority', '-created_at'], name='properties__priorit_bd3861_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['scheduled_for'], name='properties__schedul_edd16e_idx'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='properties.notification', verbose_name='الإشعار'),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='properties.notification', verbose_name='الإشعار'),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['user', '-created_at'], name='properties__user_id_5d4b08_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['user', 'is_read'], name='properties__user_id_f93c38_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['notification', 'is_read'], name='properties__notific_dc2089_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationrecipient',
            unique_together={('notification', 'user')},
        ),
    ]
