# Generated by Django 6.0.6 on 2026-07-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0093_notificationlog_notificationrecipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='delivery_type',
            field=models.CharField(choices=[('in_app', 'داخلي فقط'), ('push', 'Push Notification فقط'), ('both', 'كلاهما')], default='in_app', max_length=20, verbose_name='نوع الإرسال'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_account_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='حالة الحساب'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_account_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='نوع الحساب'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_has_properties',
            field=models.BooleanField(blank=True, null=True, verbose_name='لديه عقارات'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_managers',
            field=models.BooleanField(default=False, verbose_name='المدراء'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_office_owners',
            field=models.BooleanField(default=False, verbose_name='أصحاب المكاتب'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_subscription_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='نوع الاشتراك'),
        ),
    ]
