# Generated by Django 6.0.6 on 2026-07-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0094_notification_delivery_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brokerchannel',
            options={'ordering': ['-is_featured', '-followers_count', '-created_at'], 'verbose_name': 'قناة دلال', 'verbose_name_plural': 'قنوات الدلالين'},
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='about_me',
            field=models.TextField(blank=True, verbose_name='عني'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='achievements',
            field=models.TextField(blank=True, verbose_name='الإنجازات'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='address',
            field=models.TextField(blank=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='average_session_duration',
            field=models.PositiveIntegerField(default=0, verbose_name='متوسط مدة الجلسة (ثانية)'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='channel_type',
            field=models.CharField(choices=[('basic', 'أساسي'), ('premium', 'مميز'), ('elite', 'نخبوي')], default='basic', max_length=20, verbose_name='نوع القناة'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='contact_clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='نقرات التواصل'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='engagement_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='معدل التفاعل'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='experience_years',
            field=models.IntegerField(blank=True, null=True, verbose_name='سنوات الخبرة'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='featured_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تمييز حتى'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='قناة مميزة'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='كلمات مفتاحية'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='languages',
            field=models.CharField(blank=True, max_length=200, verbose_name='اللغات'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='last_analytics_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر تحليل'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='وصف SEO'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='عنوان SEO'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='phone_clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='نقرات الهاتف'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='profile_views',
            field=models.PositiveIntegerField(default=0, verbose_name='مشاهدات الملف الشخصي'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='property_inquiries',
            field=models.PositiveIntegerField(default=0, verbose_name='استفسارات العقارات'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='saves_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الحفظ'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='shares_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المشاركات'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='الرابط المختصر'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, verbose_name='التخصص'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='انتهاء الاشتراك'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='tiktok',
            field=models.URLField(blank=True, verbose_name='تيك توك'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='whatsapp_clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='نقرات واتساب'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='work_area',
            field=models.CharField(blank=True, max_length=200, verbose_name='منطقة العمل'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='working_hours',
            field=models.CharField(blank=True, max_length=100, verbose_name='ساعات العمل'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='youtube',
            field=models.URLField(blank=True, verbose_name='يوتيوب'),
        ),
        migrations.AddIndex(
            model_name='brokerchannel',
            index=models.Index(fields=['slug'], name='properties__slug_08ea73_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerchannel',
            index=models.Index(fields=['status'], name='properties__status_0d3010_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerchannel',
            index=models.Index(fields=['channel_type'], name='properties__channel_719184_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerchannel',
            index=models.Index(fields=['is_verified'], name='properties__is_veri_b183b0_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerchannel',
            index=models.Index(fields=['-followers_count'], name='properties__followe_32d037_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerchannel',
            index=models.Index(fields=['-rating'], name='properties__rating_8f1097_idx'),
        ),
    ]
