# Generated by Django 6.0.6 on 2026-07-08 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0095_alter_brokerchannel_options_brokerchannel_about_me_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelContentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('property', 'عقار'), ('hotel', 'فندق'), ('resort', 'منتجع'), ('post', 'منشور'), ('video', 'فيديو')], max_length=20, verbose_name='نوع المحتوى')),
                ('content_id', models.PositiveIntegerField(verbose_name='معرف المحتوى')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الموافقة'), ('approved', 'مقبول'), ('rejected', 'مرفوض'), ('expired', 'منتهي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('shared_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المشاركة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='المشاهدات')),
                ('clicks_count', models.PositiveIntegerField(default=0, verbose_name='النقرات')),
                ('shares_count', models.PositiveIntegerField(default=0, verbose_name='المشاركات')),
                ('source_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_content', to='properties.brokerchannel', verbose_name='قناة المصدر')),
                ('target_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_content', to='properties.brokerchannel', verbose_name='قناة الهدف')),
            ],
            options={
                'verbose_name': 'مشاركة محتوى',
                'verbose_name_plural': 'مشاركات المحتوى',
                'ordering': ['-shared_at'],
                'unique_together': {('content_type', 'content_id', 'target_channel')},
            },
        ),
    ]
