# Generated by Django 6.0.6 on 2026-07-08 02:05

import django.db.models.deletion
import properties.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0096_channelcontentshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResortAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_type', models.CharField(choices=[('parking', 'موقف سيارات'), ('wifi', 'واي فاي'), ('pool', 'مسبح'), ('playground', 'ألعاب أطفال'), ('restaurant', 'مطعم'), ('cafeteria', 'كافتيريا'), ('family_seating', 'جلسات عائلية'), ('private_seating', 'جلسات خاصة'), ('ac', 'تكييف'), ('elevator', 'مصعد'), ('event_hall', 'قاعة مناسبات'), ('conference_hall', 'قاعة مؤتمرات'), ('beach', 'شاطئ'), ('gym', 'صالة رياضية'), ('spa', 'سبا'), ('sauna', 'ساونا'), ('jacuzzi', 'جاكوزي'), ('security', 'أمن وحراسة'), ('cctv', 'كاميرات مراقبة'), ('generator', 'مولد كهرباء'), ('disability_access', 'خدمات لذوي الإعاقة')], max_length=50, verbose_name='نوع المرفق')),
                ('is_available', models.BooleanField(default=True, verbose_name='متوفر')),
                ('description', models.TextField(blank=True, verbose_name='وصف المرفق')),
            ],
            options={
                'verbose_name': 'مرفق منتجع',
                'verbose_name_plural': 'مرافق المنتجع',
            },
        ),
        migrations.CreateModel(
            name='ResortBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='تاريخ الوصول')),
                ('check_out', models.DateField(verbose_name='تاريخ المغادرة')),
                ('guests', models.PositiveIntegerField(default=1, verbose_name='عدد الضيوف')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر الإجمالي')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الموافقة'), ('confirmed', 'مؤكد'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('special_requests', models.TextField(blank=True, verbose_name='طلبات خاصة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحجز')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'حجز منتجع',
                'verbose_name_plural': 'حجوزات المنتجع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResortGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=properties.models.resort_gallery_path, verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='الوصف')),
                ('is_primary', models.BooleanField(default=False, verbose_name='صورة رئيسية')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'صورة منتجع',
                'verbose_name_plural': 'صور المنتجع',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResortLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإعجاب')),
            ],
            options={
                'verbose_name': 'إعجاب منتجع',
                'verbose_name_plural': 'إعجابات المنتجع',
            },
        ),
        migrations.CreateModel(
            name='ResortOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان العرض')),
                ('description', models.TextField(verbose_name='وصف العرض')),
                ('discount_percentage', models.PositiveIntegerField(verbose_name='نسبة الخصم')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر الأصلي')),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر بعد الخصم')),
                ('valid_from', models.DateTimeField(verbose_name='صالح من')),
                ('valid_until', models.DateTimeField(verbose_name='صالح حتى')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'عرض منتجع',
                'verbose_name_plural': 'عروض المنتجع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResortReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(verbose_name='التقييم بالنجوم')),
                ('comment', models.TextField(verbose_name='التعليق')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='صور من الزائر')),
                ('is_approved', models.BooleanField(default=False, verbose_name='موافق عليه')),
                ('owner_reply', models.TextField(blank=True, verbose_name='رد المالك')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقييم')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تقييم منتجع',
                'verbose_name_plural': 'تقييمات المنتجع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResortService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('online_booking', 'الحجز الإلكتروني'), ('online_payment', 'الدفع الإلكتروني'), ('offers_discounts', 'العروض والخصومات'), ('events', 'الفعاليات'), ('trips', 'الرحلات'), ('hall_rental', 'تأجير القاعات'), ('cabin_rental', 'تأجير الأكواخ'), ('chalet_rental', 'تأجير الشاليهات')], max_length=50, verbose_name='نوع الخدمة')),
                ('is_available', models.BooleanField(default=True, verbose_name='متوفر')),
                ('description', models.TextField(blank=True, verbose_name='وصف الخدمة')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر')),
            ],
            options={
                'verbose_name': 'خدمة منتجع',
                'verbose_name_plural': 'خدمات المنتجع',
            },
        ),
        migrations.AlterUniqueTogether(
            name='channelcontentshare',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='channelcontentshare',
            name='source_channel',
        ),
        migrations.RemoveField(
            model_name='channelcontentshare',
            name='target_channel',
        ),
        migrations.RemoveField(
            model_name='resortimage',
            name='resort',
        ),
        migrations.AlterModelOptions(
            name='resort',
            options={'ordering': ['-is_verified', '-rating', '-created_at'], 'verbose_name': 'منتجع سياحي', 'verbose_name_plural': 'المنتجعات السياحية'},
        ),
        migrations.RemoveField(
            model_name='resort',
            name='accommodation_types',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='address',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='image',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='price_range',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='suitable_for',
        ),
        migrations.AddField(
            model_name='resort',
            name='advance_booking',
            field=models.BooleanField(default=True, verbose_name='الحجز المسبق'),
        ),
        migrations.AddField(
            model_name='resort',
            name='bookings_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الحجوزات'),
        ),
        migrations.AddField(
            model_name='resort',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resorts', to='properties.broker', verbose_name='الدلال'),
        ),
        migrations.AddField(
            model_name='resort',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=properties.models.resort_cover_path, verbose_name='صورة الغلاف'),
        ),
        migrations.AddField(
            model_name='resort',
            name='currency',
            field=models.CharField(default='د.ع', max_length=10, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='resort',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='المنطقة'),
        ),
        migrations.AddField(
            model_name='resort',
            name='featured_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تمييز حتى'),
        ),
        migrations.AddField(
            model_name='resort',
            name='full_address',
            field=models.TextField(blank=True, verbose_name='العنوان الكامل'),
        ),
        migrations.AddField(
            model_name='resort',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='موثق'),
        ),
        migrations.AddField(
            model_name='resort',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='كلمات مفتاحية'),
        ),
        migrations.AddField(
            model_name='resort',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الإعجابات'),
        ),
        migrations.AddField(
            model_name='resort',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=properties.models.resort_logo_path, verbose_name='الشعار'),
        ),
        migrations.AddField(
            model_name='resort',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='أعلى سعر'),
        ),
        migrations.AddField(
            model_name='resort',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='وصف SEO'),
        ),
        migrations.AddField(
            model_name='resort',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='عنوان SEO'),
        ),
        migrations.AddField(
            model_name='resort',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='أقل سعر'),
        ),
        migrations.AddField(
            model_name='resort',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='التقييم'),
        ),
        migrations.AddField(
            model_name='resort',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد التقييمات'),
        ),
        migrations.AddField(
            model_name='resort',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد التقييمات'),
        ),
        migrations.AddField(
            model_name='resort',
            name='shares_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المشاركات'),
        ),
        migrations.AddField(
            model_name='resort',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='الرابط المختصر'),
        ),
        migrations.AddField(
            model_name='resort',
            name='status',
            field=models.CharField(choices=[('pending', 'بانتظار الموافقة'), ('active', 'نشط'), ('inactive', 'غير نشط'), ('rejected', 'مرفوض'), ('suspended', 'موقوف')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='resort',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resorts', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المالك'),
        ),
        migrations.AddField(
            model_name='resort',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='رابط الفيديو'),
        ),
        migrations.AddField(
            model_name='resort',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات'),
        ),
        migrations.AddField(
            model_name='resort',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='واتساب'),
        ),
        migrations.AddField(
            model_name='resort',
            name='working_days',
            field=models.CharField(blank=True, max_length=100, verbose_name='أيام العمل'),
        ),
        migrations.AddField(
            model_name='resort',
            name='working_hours',
            field=models.CharField(blank=True, max_length=100, verbose_name='ساعات العمل'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='governorate',
            field=models.CharField(blank=True, max_length=100, verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='name',
            field=models.CharField(max_length=200, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='resort_type',
            field=models.CharField(choices=[('resort', 'منتجع سياحي'), ('hotel', 'فندق'), ('chalet', 'شاليه'), ('cabin', 'كوخ'), ('camp', 'مخيم سياحي'), ('amusement_park', 'مدينة ألعاب'), ('park', 'منتزه'), ('public_garden', 'حديقة عامة'), ('pool', 'مسبح'), ('rest_house', 'استراحة'), ('tourist_farm', 'مزرعة سياحية'), ('tourist_island', 'جزيرة سياحية'), ('archaeological_site', 'موقع أثري'), ('tourist_restaurant', 'مطعم سياحي'), ('tourist_cafe', 'مقهى سياحي')], max_length=50, verbose_name='نوع المكان'),
        ),
        migrations.AddIndex(
            model_name='resort',
            index=models.Index(fields=['resort_type', '-created_at'], name='properties__resort__e88bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='resort',
            index=models.Index(fields=['governorate', 'city'], name='properties__governo_6d861e_idx'),
        ),
        migrations.AddIndex(
            model_name='resort',
            index=models.Index(fields=['status', '-created_at'], name='properties__status_c6f60b_idx'),
        ),
        migrations.AddIndex(
            model_name='resort',
            index=models.Index(fields=['is_verified', '-rating'], name='properties__is_veri_ad62c7_idx'),
        ),
        migrations.AddIndex(
            model_name='resort',
            index=models.Index(fields=['-rating', '-created_at'], name='properties__rating_b8c73e_idx'),
        ),
        migrations.AddField(
            model_name='resortamenity',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='properties.resort', verbose_name='المنتجع'),
        ),
        migrations.AddField(
            model_name='resortbooking',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.resort', verbose_name='المنتجع'),
        ),
        migrations.AddField(
            model_name='resortbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resort_bookings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='resortgallery',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='properties.resort', verbose_name='المنتجع'),
        ),
        migrations.AddField(
            model_name='resortlike',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='properties.resort', verbose_name='المنتجع'),
        ),
        migrations.AddField(
            model_name='resortlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resort_likes', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='resortoffer',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='properties.resort', verbose_name='المنتجع'),
        ),
        migrations.AddField(
            model_name='resortreview',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.resort', verbose_name='المنتجع'),
        ),
        migrations.AddField(
            model_name='resortreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resort_reviews', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='resortservice',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='properties.resort', verbose_name='المنتجع'),
        ),
        migrations.DeleteModel(
            name='ChannelContentShare',
        ),
        migrations.DeleteModel(
            name='ResortImage',
        ),
        migrations.AlterUniqueTogether(
            name='resortamenity',
            unique_together={('resort', 'amenity_type')},
        ),
        migrations.AlterUniqueTogether(
            name='resortlike',
            unique_together={('resort', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='resortreview',
            unique_together={('resort', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='resortservice',
            unique_together={('resort', 'service_type')},
        ),
    ]
