# Generated by Django 6.0.6 on 2026-07-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0097_resortamenity_resortbooking_resortgallery_resortlike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='broker_covers/', verbose_name='غلاف الصفحة'),
        ),
        migrations.AddField(
            model_name='broker',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='broker_profiles/', verbose_name='الصورة الشخصية'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_covers/', verbose_name='غلاف الصفحة'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_profiles/', verbose_name='الصورة الشخصية'),
        ),
    ]
