# Generated by Django 6.0.6 on 2026-07-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0098_broker_cover_image_broker_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='annual_maintenance_fee',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='رسوم الصيانة السنوية'),
        ),
        migrations.AddField(
            model_name='property',
            name='down_payment',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='الدفعة الأولى'),
        ),
        migrations.AddField(
            model_name='property',
            name='finish_condition',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='حالة التشطيب'),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع الأرضية'),
        ),
        migrations.AddField(
            model_name='property',
            name='installments',
            field=models.TextField(blank=True, null=True, verbose_name='الأقساط (إن وجدت)'),
        ),
        migrations.AddField(
            model_name='property',
            name='last_maintenance',
            field=models.DateField(blank=True, null=True, verbose_name='آخر صيانة'),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership_status',
            field=models.CharField(blank=True, choices=[('title_deed', 'طابو'), ('agricultural', 'زراعي'), ('investment', 'استثماري'), ('commercial', 'تجاري'), ('other', 'أخرى')], max_length=30, null=True, verbose_name='حالة الملكية'),
        ),
        migrations.AddField(
            model_name='property',
            name='price_per_meter',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='سعر المتر'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_condition',
            field=models.CharField(blank=True, choices=[('new', 'جديد'), ('used', 'مستعمل'), ('under_construction', 'قيد الإنشاء')], max_length=30, null=True, verbose_name='حالة العقار'),
        ),
        migrations.AddField(
            model_name='property',
            name='purpose',
            field=models.CharField(blank=True, choices=[('sale', 'بيع'), ('rent', 'إيجار'), ('investment', 'استثمار'), ('auction', 'مزاد')], max_length=20, null=True, verbose_name='الغرض'),
        ),
        migrations.AddField(
            model_name='property',
            name='roof_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع السقف'),
        ),
        migrations.AddField(
            model_name='property',
            name='wall_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع الجدران'),
        ),
    ]
