# Generated by Django 6.0.6 on 2026-07-08 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0099_property_annual_maintenance_fee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-is_pinned', '-is_featured', '-is_promoted', '-created_at'], 'verbose_name': 'عقار', 'verbose_name_plural': 'العقارات'},
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties__is_feat_b56ef4_idx',
        ),
        migrations.AddField(
            model_name='property',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='مثبت في الأعلى'),
        ),
        migrations.AddField(
            model_name='property',
            name='pinned_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='مثبت حتى'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_featured', 'is_promoted', 'is_pinned'], name='properties__is_feat_ade979_idx'),
        ),
    ]
