# Generated by Django 6.0.6 on 2026-07-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0100_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_covers/', verbose_name='صورة الغلاف'),
        ),
        migrations.AddField(
            model_name='property',
            name='personal_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_personal/', verbose_name='صورة شخصية'),
        ),
    ]
