# Generated by Django 6.0.6 on 2026-07-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0101_property_cover_image_property_personal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingrequest',
            name='featured_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='نهاية التمييز'),
        ),
        migrations.AddField(
            model_name='buildingrequest',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='مميز'),
        ),
        migrations.AddField(
            model_name='buildingrequest',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='عرض للجمهور'),
        ),
        migrations.AddField(
            model_name='buildingrequest',
            name='publisher_type',
            field=models.CharField(choices=[('user', 'مستخدم'), ('broker', 'دلال'), ('admin', 'إدارة')], default='user', max_length=20, verbose_name='نوع الناشر'),
        ),
    ]
