# Generated by Django 6.0.6 on 2026-07-08 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0102_buildingrequest_featured_until_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الإعلان')),
                ('description', models.TextField(verbose_name='وصف الإعلان')),
                ('service_type', models.CharField(choices=[('construction', 'بناء وتشطيب'), ('electricity', 'كهرباء'), ('plumbing', 'سباكة'), ('carpentry', 'نجارة'), ('painting', 'دهان'), ('hvac', 'تكييف وتبريد'), ('landscaping', 'تنسيق حدائق'), ('security', 'أمن وحراسة'), ('cleaning', 'تنظيف'), ('moving', 'نقل عفش'), ('other', 'خدمات أخرى')], max_length=20, verbose_name='نوع الخدمة')),
                ('project_type', models.CharField(blank=True, max_length=100, verbose_name='نوع المشروع')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع')),
                ('governorate', models.CharField(blank=True, choices=[('BAG', 'بغداد'), ('BAS', 'البصرة'), ('NIN', 'نينوى'), ('ERB', 'أربيل'), ('NAJ', 'النجف'), ('KAR', 'كربلاء'), ('BAB', 'بابل'), ('DHI', 'ذي قار'), ('DIA', 'ديالى'), ('KIR', 'كركوك'), ('ANB', 'الأنبار'), ('WAS', 'واسط'), ('MUT', 'ميسان'), ('MUTH', 'المثنى'), ('QAD', 'القادسية (الديوانية)'), ('SAL', 'صلاح الدين'), ('DUH', 'دهوك'), ('SUL', 'السليمانية'), ('HAL', 'حلبجة'), ('KIRKUK', 'كركوك')], max_length=100, verbose_name='المحافظة')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='السعر')),
                ('price_description', models.CharField(blank=True, max_length=200, verbose_name='وصف السعر')),
                ('completion_time', models.CharField(blank=True, max_length=100, verbose_name='وقت الإنجاز')),
                ('includes', models.TextField(blank=True, verbose_name='ما يشمله العرض')),
                ('requirements', models.TextField(blank=True, verbose_name='المتطلبات')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='service_ads/covers/', verbose_name='صورة الغلاف')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشط'), ('paused', 'متوقف'), ('expired', 'منتهي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('featured_until', models.DateTimeField(blank=True, null=True, verbose_name='نهاية التمييز')),
                ('views_count', models.IntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('inquiries_count', models.IntegerField(default=0, verbose_name='عدد الاستفسارات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
            ],
            options={
                'verbose_name': 'إعلان خدمة',
                'verbose_name_plural': 'إعلانات الخدمات',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrokerServicePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts_count', models.IntegerField(default=1, verbose_name='عدد المنشورات')),
                ('duration_days', models.IntegerField(default=7, verbose_name='عدد الأيام')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('posts_published', models.IntegerField(default=0, verbose_name='المنشورات المنشورة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_promotions', to='properties.broker', verbose_name='الدلال')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_promotions', to='properties.serviceadvertisement', verbose_name='الإعلان')),
            ],
            options={
                'verbose_name': 'ترقية خدمة',
                'verbose_name_plural': 'ترقيات الخدمات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAdvertisementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_ads/images/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='التعليق')),
                ('is_cover', models.BooleanField(default=False, verbose_name='صورة الغلاف')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.serviceadvertisement', verbose_name='الإعلان')),
            ],
            options={
                'verbose_name': 'صورة إعلان',
                'verbose_name_plural': 'صور الإعلانات',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAdvertisementVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='service_ads/videos/', verbose_name='الفيديو')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='service_ads/thumbnails/', verbose_name='الصورة المصغرة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='التعليق')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='المدة (ثواني)')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='properties.serviceadvertisement', verbose_name='الإعلان')),
            ],
            options={
                'verbose_name': 'فيديو إعلان',
                'verbose_name_plural': 'فيديوهات الإعلانات',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200, verbose_name='اسم العمل/الشركة')),
                ('service_type', models.CharField(choices=[('construction', 'بناء وتشطيب'), ('electricity', 'كهرباء'), ('plumbing', 'سباكة'), ('carpentry', 'نجارة'), ('painting', 'دهان'), ('hvac', 'تكييف وتبريد'), ('landscaping', 'تنسيق حدائق'), ('security', 'أمن وحراسة'), ('cleaning', 'تنظيف'), ('moving', 'نقل عفش'), ('other', 'خدمات أخرى')], max_length=20, verbose_name='نوع الخدمة')),
                ('description', models.TextField(blank=True, verbose_name='وصف الخدمات')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='واتساب')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='العنوان')),
                ('governorate', models.CharField(blank=True, choices=[('BAG', 'بغداد'), ('BAS', 'البصرة'), ('NIN', 'نينوى'), ('ERB', 'أربيل'), ('NAJ', 'النجف'), ('KAR', 'كربلاء'), ('BAB', 'بابل'), ('DHI', 'ذي قار'), ('DIA', 'ديالى'), ('KIR', 'كركوك'), ('ANB', 'الأنبار'), ('WAS', 'واسط'), ('MUT', 'ميسان'), ('MUTH', 'المثنى'), ('QAD', 'القادسية (الديوانية)'), ('SAL', 'صلاح الدين'), ('DUH', 'دهوك'), ('SUL', 'السليمانية'), ('HAL', 'حلبجة'), ('KIRKUK', 'كركوك')], max_length=100, verbose_name='المحافظة')),
                ('years_experience', models.IntegerField(default=0, verbose_name='سنوات الخبرة')),
                ('team_size', models.IntegerField(default=1, verbose_name='حجم الفريق')),
                ('working_hours', models.CharField(blank=True, max_length=100, verbose_name='ساعات العمل')),
                ('min_price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='أقل سعر')),
                ('max_price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='أعلى سعر')),
                ('price_unit', models.CharField(blank=True, max_length=50, verbose_name='وحدة السعر (متر مربع، مشروع، إلخ)')),
                ('licenses', models.TextField(blank=True, verbose_name='التراخيص والشهادات')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='service_providers/logos/', verbose_name='الشعار')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='service_providers/covers/', verbose_name='صورة الغلاف')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='التقييم')),
                ('reviews_count', models.IntegerField(default=0, verbose_name='عدد التقييمات')),
                ('completed_projects', models.IntegerField(default=0, verbose_name='المشاريع المكتملة')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('suspended', 'موقوف')], default='active', max_length=20, verbose_name='الحالة')),
                ('is_verified', models.BooleanField(default=False, verbose_name='موثق')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مقدم خدمة',
                'verbose_name_plural': 'مقدمو الخدمات',
                'ordering': ['-is_featured', '-rating', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='serviceadvertisement',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='properties.serviceprovider', verbose_name='مقدم الخدمة'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['service_type'], name='properties__service_bcd132_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['governorate'], name='properties__governo_f1f82f_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['status'], name='properties__status_de6fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['-rating'], name='properties__rating_406e76_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceadvertisement',
            index=models.Index(fields=['service_type'], name='properties__service_db4c70_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceadvertisement',
            index=models.Index(fields=['governorate'], name='properties__governo_fb841b_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceadvertisement',
            index=models.Index(fields=['status'], name='properties__status_4a6ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceadvertisement',
            index=models.Index(fields=['-created_at'], name='properties__created_cdae14_idx'),
        ),
    ]
