# Generated by Django 6.0.6 on 2026-07-08 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0103_serviceadvertisement_brokerservicepromotion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='access_type',
            field=models.CharField(choices=[('public', 'عام'), ('private', 'خاص برقم'), ('invitation_only', 'بدعوة فقط')], default='public', max_length=20, verbose_name='نوع الوصول'),
        ),
        migrations.CreateModel(
            name='AuctionInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_code', models.CharField(max_length=20, unique=True, verbose_name='كود الدعوة')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'مقبول'), ('declined', 'مرفوض'), ('used', 'تم الاستخدام')], default='pending', max_length=20, verbose_name='الحالة')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القبول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='properties.auction', verbose_name='المزاد')),
                ('invited_broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_invitations', to='properties.broker', verbose_name='الدلال المدعو')),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_invitations', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المدعو')),
            ],
            options={
                'verbose_name': 'دعوة مزاد',
                'verbose_name_plural': 'دعوات المزادات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invitation_code'], name='properties__invitat_e35087_idx'), models.Index(fields=['status'], name='properties__status_005180_idx')],
            },
        ),
    ]
