# Generated by Django 6.0.6 on 2026-07-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0104_auction_access_type_auctioninvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerchannel',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='clients_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد العملاء'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='deals_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الصفقات'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='governorate',
            field=models.CharField(blank=True, choices=[('BAG', 'بغداد'), ('BAS', 'البصرة'), ('NIN', 'نينوى'), ('ERB', 'أربيل'), ('NAJ', 'النجف'), ('KAR', 'كربلاء'), ('BAB', 'بابل'), ('DHI', 'ذي قار'), ('DIA', 'ديالى'), ('KIR', 'كركوك'), ('ANB', 'الأنبار'), ('WAS', 'واسط'), ('MUT', 'ميسان'), ('MUTH', 'المثنى'), ('QAD', 'القادسية (الديوانية)'), ('SAL', 'صلاح الدين'), ('DUH', 'دهوك'), ('SUL', 'السليمانية'), ('HAL', 'حلبجة'), ('KIRKUK', 'كركوك')], max_length=100, verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='متصل الآن'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر ظهور'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='office_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='المكتب العقاري'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='rentals_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد التأجيرات'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='sales_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المبيعات'),
        ),
        migrations.AddField(
            model_name='brokerchannel',
            name='website',
            field=models.URLField(blank=True, verbose_name='الموقع الإلكتروني'),
        ),
    ]
