# Generated by Django 6.0.6 on 2026-07-09 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0106_hotelpage_hoteloffer_hotelgallery_hotelfollower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_listings', to='properties.hotelpage', verbose_name='الصفحة'),
        ),
        migrations.AddField(
            model_name='resort',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resort_listings', to='properties.hotelpage', verbose_name='الصفحة'),
        ),
    ]
