# Generated by Django 6.0.6 on 2026-07-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0108_serviceprovidercategory_serviceproviderpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='has_standalone_page',
            field=models.BooleanField(default=False, help_text='تفعيل صفحة مستقلة للدلال لا تظهر عقاراته في الصفحة الرئيسية', verbose_name='صفحة مستقلة'),
        ),
        migrations.AddField(
            model_name='broker',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, null=True, unique=True, verbose_name='رابط الصفحة'),
        ),
    ]
