# Generated by Django 6.0.6 on 2026-07-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0109_broker_has_standalone_page_broker_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broker',
            name='has_standalone_page',
        ),
        migrations.AddField(
            model_name='broker',
            name='page_display_mode',
            field=models.CharField(choices=[('main_only', 'الصفحة الرئيسية فقط'), ('standalone_only', 'الصفحة المستقلة فقط'), ('both', 'الاثنين معاً')], default='main_only', help_text='اختر أين تظهر عقاراتك', max_length=20, verbose_name='طريقة عرض الصفحة'),
        ),
    ]
