# Generated by Django 6.0.6 on 2026-07-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0110_remove_broker_has_standalone_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='address',
            field=models.TextField(blank=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='broker',
            name='background_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, verbose_name='لون الخلفية'),
        ),
        migrations.AddField(
            model_name='broker',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='broker_backgrounds/', verbose_name='صورة الخلفية'),
        ),
        migrations.AddField(
            model_name='broker',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='broker_banners/', verbose_name='بانر الصفحة'),
        ),
        migrations.AddField(
            model_name='broker',
            name='button_color',
            field=models.CharField(blank=True, default='#FF7A00', max_length=7, verbose_name='لون الأزرار'),
        ),
        migrations.AddField(
            model_name='broker',
            name='clients_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد العملاء'),
        ),
        migrations.AddField(
            model_name='broker',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='broker',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='فيسبوك'),
        ),
        migrations.AddField(
            model_name='broker',
            name='font_family',
            field=models.CharField(blank=True, default='Cairo', max_length=50, verbose_name='نوع الخط'),
        ),
        migrations.AddField(
            model_name='broker',
            name='google_maps_url',
            field=models.URLField(blank=True, verbose_name='رابط Google Maps'),
        ),
        migrations.AddField(
            model_name='broker',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='إنستغرام'),
        ),
        migrations.AddField(
            model_name='broker',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='المسمى الوظيفي'),
        ),
        migrations.AddField(
            model_name='broker',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='لينكد إن'),
        ),
        migrations.AddField(
            model_name='broker',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='broker_logos/', verbose_name='الشعار'),
        ),
        migrations.AddField(
            model_name='broker',
            name='mission',
            field=models.TextField(blank=True, verbose_name='رسالتنا'),
        ),
        migrations.AddField(
            model_name='broker',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='broker_og_images/', verbose_name='صورة المشاركة'),
        ),
        migrations.AddField(
            model_name='broker',
            name='page_color',
            field=models.CharField(blank=True, default='#FF7A00', max_length=7, verbose_name='لون الصفحة'),
        ),
        migrations.AddField(
            model_name='broker',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='وصف SEO'),
        ),
        migrations.AddField(
            model_name='broker',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='افصل بين الكلمات بفاصلة', max_length=500, verbose_name='الكلمات المفتاحية'),
        ),
        migrations.AddField(
            model_name='broker',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان الصفحة'),
        ),
        migrations.AddField(
            model_name='broker',
            name='show_address',
            field=models.BooleanField(default=True, verbose_name='إظهار العنوان'),
        ),
        migrations.AddField(
            model_name='broker',
            name='show_email',
            field=models.BooleanField(default=True, verbose_name='إظهار البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='broker',
            name='show_phone',
            field=models.BooleanField(default=True, verbose_name='إظهار رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='broker',
            name='show_properties',
            field=models.BooleanField(default=True, verbose_name='إظهار العقارات'),
        ),
        migrations.AddField(
            model_name='broker',
            name='show_ratings',
            field=models.BooleanField(default=True, verbose_name='إظهار التقييمات'),
        ),
        migrations.AddField(
            model_name='broker',
            name='show_social_media',
            field=models.BooleanField(default=True, verbose_name='إظهار مواقع التواصل'),
        ),
        migrations.AddField(
            model_name='broker',
            name='show_stats',
            field=models.BooleanField(default=True, verbose_name='إظهار الإحصائيات'),
        ),
        migrations.AddField(
            model_name='broker',
            name='show_whatsapp',
            field=models.BooleanField(default=True, verbose_name='إظهار واتساب'),
        ),
        migrations.AddField(
            model_name='broker',
            name='show_working_hours',
            field=models.BooleanField(default=True, verbose_name='إظهار ساعات العمل'),
        ),
        migrations.AddField(
            model_name='broker',
            name='site_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم الموقع'),
        ),
        migrations.AddField(
            model_name='broker',
            name='snapchat',
            field=models.URLField(blank=True, verbose_name='سناب شات'),
        ),
        migrations.AddField(
            model_name='broker',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='تيليجرام'),
        ),
        migrations.AddField(
            model_name='broker',
            name='text_color',
            field=models.CharField(blank=True, default='#333333', max_length=7, verbose_name='لون النص'),
        ),
        migrations.AddField(
            model_name='broker',
            name='tiktok',
            field=models.URLField(blank=True, verbose_name='تيك توك'),
        ),
        migrations.AddField(
            model_name='broker',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='تويتر (X)'),
        ),
        migrations.AddField(
            model_name='broker',
            name='vision',
            field=models.TextField(blank=True, verbose_name='رؤيتنا'),
        ),
        migrations.AddField(
            model_name='broker',
            name='website',
            field=models.URLField(blank=True, verbose_name='الموقع الإلكتروني'),
        ),
        migrations.AddField(
            model_name='broker',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='واتساب'),
        ),
        migrations.AddField(
            model_name='broker',
            name='working_governorates',
            field=models.TextField(blank=True, help_text='افصل بين المحافظات بفاصلة', verbose_name='المحافظات التي يعمل بها'),
        ),
        migrations.AddField(
            model_name='broker',
            name='working_hours',
            field=models.CharField(blank=True, max_length=100, verbose_name='ساعات العمل'),
        ),
        migrations.AddField(
            model_name='broker',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0, verbose_name='سنوات الخبرة'),
        ),
        migrations.AddField(
            model_name='broker',
            name='youtube',
            field=models.URLField(blank=True, verbose_name='يوتيوب'),
        ),
    ]
