# Generated by Django 6.0.6 on 2026-07-12 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0111_broker_address_broker_background_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrenewalrequest',
            name='approval_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP الموافقة'),
        ),
        migrations.AddField(
            model_name='subscriptionrenewalrequest',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP العنوان'),
        ),
        migrations.AddField(
            model_name='subscriptionrenewalrequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرفض'),
        ),
        migrations.AddField(
            model_name='subscriptionrenewalrequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_renewals', to=settings.AUTH_USER_MODEL, verbose_name='تم الرفض بواسطة'),
        ),
        migrations.AddField(
            model_name='subscriptionrenewalrequest',
            name='rejection_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP الرفض'),
        ),
        migrations.AddField(
            model_name='subscriptionrenewalrequest',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
    ]
