# Generated by Django 6.0.6 on 2026-07-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0112_subscriptionrenewalrequest_approval_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الصلاحية'),
        ),
        migrations.AddField(
            model_name='property',
            name='frozen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التجميد'),
        ),
        migrations.AddField(
            model_name='property',
            name='frozen_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='سبب التجميد'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='مجمد'),
        ),
        migrations.AddField(
            model_name='property',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر'),
        ),
    ]
