# Generated by Django 6.0.6 on 2026-07-12 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0113_property_expiry_date_property_frozen_at_and_more'),
    ]

    operations = [
    ]
