# Generated by Django 6.0.6 on 2026-07-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0114_auto_20260712_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('code', models.CharField(max_length=6, verbose_name='رمز التحقق')),
                ('purpose', models.CharField(choices=[('registration', 'تسجيل حساب جديد'), ('password_reset', 'استعادة كلمة المرور'), ('phone_verification', 'التحقق من رقم الهاتف')], max_length=20, verbose_name='الغرض')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تم التحقق')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='محاولات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
            ],
            options={
                'verbose_name': 'رمز تحقق',
                'verbose_name_plural': 'رموز التحقق',
                'ordering': ['-created_at'],
            },
        ),
    ]
