# Generated by Django 6.0.6 on 2026-07-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0115_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='suspension_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='سبب التجميد'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_subscription_based',
            field=models.BooleanField(default=False, verbose_name='مبني على الاشتراك'),
        ),
    ]
