from django.urls import path

from . import views, api, broker_views, dallal_views
try:
    from . import api_views_enterprise as api_enterprise
except ImportError:
    api_enterprise = None

urlpatterns = [
    # Existing template-based routes
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('faq/', views.faq, name='faq'),
    path('terms/', views.terms, name='terms'),
    path('privacy/', views.privacy, name='privacy'),
    path('search/', views.search, name='search'),
    path('advanced-search/', views.advanced_search, name='advanced_search'),
    path('property/<str:slug>/', views.property_detail, name='property_detail'),
    path('property/<str:slug>/inquire/', views.property_inquire, name='property_inquire'),
    path('property/<str:slug>/like/', views.like_property, name='like_property'),
    path('property/<str:slug>/save/', views.save_property, name='save_property'),
    path('property/<str:slug>/report/', views.report_property, name='report_property'),
    path('property/<str:slug>/tour/', views.virtual_tour, name='virtual_tour'),
    path('property/<str:slug>/360/', views.tour_360, name='tour_360'),
    path('property/<str:slug>/video/', views.video_tour, name='video_tour'),
    path('property/<str:slug>/note/', views.property_note, name='property_note'),
    path('property/<str:slug>/note/delete/', views.delete_property_note, name='delete_property_note'),
    path('property/<str:slug>/auction/', views.auction_detail, name='auction_detail'),
    path('property/<str:slug>/auction/bid/', views.place_bid, name='place_bid'),
    path('property/<str:slug>/auction/auto-bid/', views.toggle_auto_bid, name='toggle_auto_bid'),
    path('property/<str:slug>/auction/access-code/', views.auction_access_code, name='auction_access_code'),
    path('auctions/', views.auctions_list, name='auctions_list'),
    path('auctions/<int:auction_id>/bids/', views.auction_bids, name='auction_bids'),
    path('channels/', views.channels_view, name='channels'),
    path('channel/brokers/', views.channel_brokers_view, name='channel_brokers'),
    path('channel/users/', views.channel_users_view, name='channel_users'),
    path('channel/offices/', views.channel_offices_view, name='channel_offices'),
    path('channel/dallal/', views.channel_dallal_view, name='channel_dallal'),
    path('favorites/', views.favorites, name='favorites'),
    path('saved/', views.saved_properties, name='saved_properties'),
    path('my-properties/', views.my_properties, name='my_properties'),
    path('property/create/', views.create_property, name='create_property'),
    path('property/<int:property_id>/edit/', views.edit_property, name='edit_property'),
    path('property/<int:property_id>/delete/', views.delete_property, name='delete_property'),
    path('property/<int:property_id>/image/<int:image_id>/delete/', views.delete_property_image, name='delete_property_image'),
    path('property/<int:property_id>/image/<int:image_id>/set-primary/', views.set_primary_image, name='set_primary_image'),
    path('property/<int:property_id>/image/upload/', views.upload_property_image, name='upload_property_image'),
    path('property/<int:property_id>/video/upload/', views.upload_property_video, name='upload_property_video'),
    path('property/<int:property_id>/video/<int:video_id>/delete/', views.delete_property_video, name='delete_property_video'),
    path('property/<int:property_id>/tour/create/', views.create_tour_point, name='create_tour_point'),
    path('property/<int:property_id>/tour/<int:point_id>/edit/', views.edit_tour_point, name='edit_tour_point'),
    path('property/<int:property_id>/tour/<int:point_id>/delete/', views.delete_tour_point, name='delete_tour_point'),
    path('property/<int:property_id>/360/create/', views.create_tour_360, name='create_tour_360'),
    path('property/<int:property_id>/360/<int:tour_id>/edit/', views.edit_tour_360, name='edit_tour_360'),
    path('property/<int:property_id>/360/<int:tour_id>/delete/', views.delete_tour_360, name='delete_tour_360'),
    path('hotels/', views.hotels_list, name='hotels_list'),
    path('resorts/', views.resorts_list, name='resorts_list'),
    path('hotels/<str:slug>/', views.hotel_detail, name='hotel_detail'),
    path('resorts/<str:slug>/', views.resort_detail, name='resort_detail'),
    path('hotels/<str:slug>/book/', views.book_hotel, name='book_hotel'),
    path('resorts/<str:slug>/book/', views.book_resort, name='book_resort'),
    path('hotels/<str:slug>/review/', views.review_hotel, name='review_hotel'),
    path('resorts/<str:slug>/review/', views.review_resort, name='review_resort'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('password-reset/', views.password_reset, name='password_reset'),
    path('password-reset/done/', views.password_reset_done, name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.password_reset_confirm, name='password_reset_confirm'),
    path('reset/done/', views.password_reset_complete, name='password_reset_complete'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/properties/', views.dashboard_properties, name='dashboard_properties'),
    path('dashboard/properties/create/', views.dashboard_create_property, name='dashboard_create_property'),
    path('dashboard/properties/<int:property_id>/edit/', views.dashboard_edit_property, name='dashboard_edit_property'),
    path('dashboard/properties/<int:property_id>/delete/', views.dashboard_delete_property, name='dashboard_delete_property'),
    path('dashboard/properties/<int:property_id>/activate/', views.dashboard_activate_property, name='dashboard_activate_property'),
    path('dashboard/properties/<int:property_id>/deactivate/', views.dashboard_deactivate_property, name='dashboard_deactivate_property'),
    path('dashboard/properties/<int:property_id>/feature/', views.dashboard_feature_property, name='dashboard_feature_property'),
    path('dashboard/properties/<int:property_id>/unfeature/', views.dashboard_unfeature_property, name='dashboard_unfeature_property'),
    path('dashboard/properties/export/', views.export_properties, name='export_properties'),
    path('dashboard/properties/import/', views.import_properties, name='import_properties'),
    path('dashboard/messages/', views.dashboard_messages, name='dashboard_messages'),
    path('dashboard/messages/<int:message_id>/', views.dashboard_message_detail, name='dashboard_message_detail'),
    path('dashboard/messages/<int:message_id>/reply/', views.dashboard_reply_message, name='dashboard_reply_message'),
    path('dashboard/messages/<int:message_id>/delete/', views.dashboard_delete_message, name='dashboard_delete_message'),
    path('dashboard/messages/send/', views.dashboard_send_message, name='dashboard_send_message'),
    path('dashboard/messages/bulk/', views.dashboard_bulk_message, name='dashboard_bulk_message'),
    path('dashboard/notifications/', views.dashboard_notifications, name='dashboard_notifications'),
    path('dashboard/notifications/<int:notification_id>/mark-read/', views.dashboard_mark_notification_read, name='dashboard_mark_notification_read'),
    path('dashboard/notifications/mark-all-read/', views.dashboard_mark_all_read, name='dashboard_mark_all_read'),
    path('dashboard/favorites/', views.dashboard_favorites, name='dashboard_favorites'),
    path('dashboard/favorites/<int:favorite_id>/remove/', views.dashboard_remove_favorite, name='dashboard_remove_favorite'),
    path('dashboard/saved/', views.dashboard_saved, name='dashboard_saved'),
    path('dashboard/saved/<int:saved_id>/remove/', views.dashboard_remove_saved, name='dashboard_remove_saved'),
    path('dashboard/settings/', views.dashboard_settings, name='dashboard_settings'),
    path('dashboard/settings/profile/', views.dashboard_settings_profile, name='dashboard_settings_profile'),
    path('dashboard/settings/security/', views.dashboard_settings_security, name='dashboard_settings_security'),
    path('dashboard/settings/notifications/', views.dashboard_settings_notifications, name='dashboard_settings_notifications'),
    path('dashboard/settings/preferences/', views.preferences_settings, name='preferences_settings'),
    path('dashboard/settings/account/', views.account_management, name='account_management'),
    path('dashboard/user-settings/', views.settings_hub, name='settings_hub'),
    path('dashboard/activity/', views.activity_page, name='activity_page'),
    path('dashboard/bulk-messages/create/', views.bulk_message_create, name='bulk_message_create'),
    path('dashboard/bulk-messages/', views.bulk_message_list, name='bulk_message_list'),
    path('dashboard/broker-statistics/', views.broker_statistics_view, name='broker_statistics'),

    # Notifications
    path('dashboard/notifications/', broker_views.notifications_view, name='notifications'),

    # Broker system routes
    path('dashboard/broker/', broker_views.broker_panel, name='broker_panel'),
    path('dashboard/brokers/', broker_views.broker_list, name='broker_list'),
    path('dashboard/brokers/create/', broker_views.broker_create, name='broker_create'),
    path('dashboard/brokers/<int:broker_id>/edit/', broker_views.broker_edit, name='broker_edit'),
    path('dashboard/brokers/<int:broker_id>/toggle/', broker_views.broker_toggle_active, name='broker_toggle_active'),
    path('dashboard/brokers/<int:broker_id>/delete/', broker_views.broker_delete, name='broker_delete'),
    path('dashboard/brokers/<int:broker_id>/renew/', broker_views.broker_renew_subscription, name='broker_renew_subscription'),
    path('dashboard/brokers/export/', broker_views.export_brokers, name='export_brokers'),
    path('dashboard/brokers/activity-log/', broker_views.activity_log, name='activity_log'),
    path('dashboard/brokers/statistics/', broker_views.broker_statistics, name='broker_statistics_admin'),
    path('dashboard/brokers/messaging/', broker_views.broker_messaging, name='broker_messaging'),
    path('dashboard/brokers/main-panel/', views.main_broker_panel, name='main_broker_panel'),
    # Broker channel management
    path('dashboard/broker/channel/settings/', broker_views.broker_channel_settings, name='broker_channel_settings'),
    path('dashboard/broker/channel/stats/', broker_views.broker_channel_stats, name='broker_channel_stats'),
    path('dashboard/subscription-plans/', views.subscription_plans_list, name='subscription_plans_list'),
    path('dashboard/subscription-plans/create/', views.subscription_plan_create, name='subscription_plan_create'),
    path('dashboard/subscription-plans/<int:plan_id>/edit/', views.subscription_plan_edit, name='subscription_plan_edit'),
    path('dashboard/subscription-plans/<int:plan_id>/delete/', views.subscription_plan_delete, name='subscription_plan_delete'),
    path('dashboard/map/', broker_views.properties_map, name='properties_map'),
    path('dashboard/map/api/properties/', broker_views.map_api_properties, name='map_api_properties'),
    path('dashboard/map/api/nearby-places/', broker_views.map_api_nearby_places, name='map_api_nearby_places'),
    path('dashboard/map/api/directions/', broker_views.map_api_directions, name='map_api_directions'),
    path('dashboard/map/api/offices/', broker_views.map_api_offices, name='map_api_offices'),
    path('dashboard/map/api/brokers/', broker_views.map_api_brokers, name='map_api_brokers'),
    path('dashboard/map/api/favorite-areas/', broker_views.map_api_save_favorite_area, name='map_api_save_favorite_area'),
    path('dashboard/map/api/comparison/', broker_views.map_api_add_to_comparison, name='map_api_add_to_comparison'),
    path('dashboard/map/api/comparison/list/', broker_views.map_api_comparison_list, name='map_api_comparison_list'),
    path('dashboard/map/api/comparison/<int:comparison_id>/remove/', broker_views.map_api_remove_from_comparison, name='map_api_remove_from_comparison'),
    path('dashboard/map/api/update-location/', broker_views.map_api_update_property_location, name='map_api_update_property_location'),
    path('dashboard/map/api/bulk-update-coordinates/', broker_views.map_api_bulk_update_coordinates, name='map_api_bulk_update_coordinates'),
    path('dashboard/map/api/validate-coordinates/', broker_views.map_api_validate_coordinates, name='map_api_validate_coordinates'),
    path('dashboard/join-requests/', broker_views.join_requests_list, name='join_requests_list'),
    path('dashboard/join-requests/<int:request_id>/approve/', broker_views.join_request_approve, name='join_request_approve'),
    path('dashboard/join-requests/<int:request_id>/reject/', broker_views.join_request_reject, name='join_request_reject'),
    path('dashboard/office/', broker_views.office_panel, name='office_panel'),
    path('dashboard/office/presence/', broker_views.office_presence_settings, name='office_presence_settings'),
    path('dashboard/office/presence/update/', views.update_presence_status, name='update_presence_status'),
    path('office/<int:office_id>/presence/', broker_views.get_office_presence, name='get_office_presence'),
    path('office/<int:office_id>/subscribe/', broker_views.subscribe_presence_notification, name='subscribe_presence_notification'),
    path('dashboard/admin/presence/', broker_views.admin_presence_dashboard, name='admin_presence_dashboard'),
    path('dashboard/admin/presence/<int:presence_id>/edit/', broker_views.admin_update_presence, name='admin_update_presence'),
    path('broker/<int:broker_id>/subscribe/', broker_views.toggle_broker_subscription, name='toggle_broker_subscription'),
    path('broker/<int:broker_id>/notification-settings/', broker_views.update_broker_notification_settings, name='update_broker_notification_settings'),
    path('subscriptions/', broker_views.user_subscriptions, name='user_subscriptions'),
    path('dashboard/broker/subscriptions/', broker_views.broker_subscription_stats, name='broker_subscription_stats'),
    path('dashboard/admin/broker-subscriptions/', broker_views.admin_broker_subscriptions, name='admin_broker_subscriptions'),
    
    # Dallal system routes
    path('dashboard/dallal/settings/', dallal_views.dallal_settings, name='dallal_settings'),
    path('dashboard/dallal/subscriptions/', dallal_views.dallal_subscriptions_list, name='dallal_subscriptions_list'),
    path('dashboard/dallal/subscriptions/create/', dallal_views.dallal_subscription_create, name='dallal_subscription_create'),
    path('dashboard/dallal/subscriptions/<int:subscription_id>/edit/', dallal_views.dallal_subscription_edit, name='dallal_subscription_edit'),
    
    # New API endpoints for Next.js frontend
    path('api/health/', api.api_health, name='api_health'),
    path('api/properties/', api.api_properties, name='api_properties'),
    path('api/property/<str:slug>/', api.api_property_detail, name='api_property_detail'),
    path('api/featured/', api.api_featured_properties, name='api_featured_properties'),
    path('api/settings/', api.api_site_settings, name='api_site_settings'),
    path('api/search/suggestions/', api.api_search_suggestions, name='api_search_suggestions'),
    path('api/statistics/', api.api_statistics, name='api_statistics'),
    path('api/subscription/expire/', views.subscription_expire_notification, name='subscription_expire_notification'),
]

# Enterprise API endpoints (only if available)
if api_enterprise:
    urlpatterns += [
        path('api/v1/system/status/', api_enterprise.api_system_status, name='api_system_status'),
        path('api/v1/system/errors/', api_enterprise.api_error_logs, name='api_error_logs'),
        path('api/v1/export/', api_enterprise.api_export_data, name='api_export_data'),
        path('api/v1/search/', api_enterprise.api_search, name='api_search'),
        path('api/v1/notifications/', api_enterprise.api_notifications, name='api_notifications'),
        path('api/v1/notifications/<int:notification_id>/read/', api_enterprise.api_mark_notification_read, name='api_mark_notification_read'),
        path('api/v1/sessions/', api_enterprise.api_sessions, name='api_sessions'),
        path('api/v1/keys/', api_enterprise.api_api_keys, name='api_api_keys'),
        path('api/v1/performance/', api_enterprise.api_performance_metrics, name='api_performance_metrics'),
    ]
